### ISSUE TITLE
Add DHCP options in GUI

### ISSUE THREAD

**Issue by CoolAEW** [aredn/aredn#1006]
**Is your feature request related to a problem? Please describe.**
We use Cisco IP phones that connect to a central FreePBX instance, we have a TFTP server with config files for the phones to provision from. To get this to work properly we have to SSH in to each node and add option 150 with the IP of the PBX. This config gets lost on fw updates.

**Describe the solution you'd like**
A way somewhere in the gui to add custom DHCP options.

**Describe alternatives you've considered**
Manually SSH into nodes and add DHCP options

**Additional context**
`echo "dhcp-option=150,xx.xx.xx.xx" >> /etc/dnsmasq.conf`
`/etc/init.d/dnsmasq restart`

**Comment by aanon4** [comment]
Would an extra file you could add options to, and which is preserved across reboot and installs, suffice for now?

**Comment by aanon4** [comment]
Such as something like this https://github.com/aredn/aredn/pull/1007

**Comment by CoolAEW** [comment]
That would be great to have, but a way to add options through GUI later would also be nice 👍

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1073 might be what you're looking for.
