### ISSUE TITLE
Lost RF on one node after upgrading to nightly build 20231211-d697fc0 

### ISSUE THREAD

**Issue by CoolAEW** [aredn/aredn#1008]
### Describe the bug
After upgrading to 20231211-d697fc0 one of my 2 nodes lost contact on RF.
Both nodes are Ubiquiti NanoBeam AC Gen2 and are fairly similar in setup, both linking to 1 node each on RF and have DtD connection between them. Only one node have lost RF, the other works.

- [ ] Does this issue still occur on the latest version? (**Required**)
Does not occur on 3.23.12, only nightly

### Expected behavior
Normal upgrade with functioning links

### Screenshots
![image](https://github.com/aredn/aredn/assets/5229105/99bfdd61-0c29-4cd6-8294-a5021d939c29)
![image](https://github.com/aredn/aredn/assets/5229105/eeae866e-0e0a-45ab-a4df-1748e785f959)

### Additional context
None

**Comment by aanon4** [comment]
What does the neighbor information look like?

**Comment by CoolAEW** [comment]
![image](https://github.com/aredn/aredn/assets/5229105/f9061f26-57c0-422c-8cb3-404475ca0bb5)
![image](https://github.com/aredn/aredn/assets/5229105/433507b9-9582-4231-bdb4-b93d90fd0ba3)

I should add that reverting to 3.23.12 fixes the issue, but I have reinstalled nightly for testing

**Comment by CoolAEW** [comment]
No, they link with one node each plus the DtD, i expect to see a link to "LA3T-26" from LA3T-20-1

**Comment by aanon4** [comment]
When you restore 3.23.12.0 (I assume you will) could you post the same data? Also, if you could post the support data for the problem node both with nightly and with 12 that would be helpful too.

**Comment by CoolAEW** [comment]
Downgraded to 12, this is how it looks now.
![image](https://github.com/aredn/aredn/assets/5229105/fa54ee9d-e1be-4d2c-b678-6ebfad93e88d)
![image](https://github.com/aredn/aredn/assets/5229105/f0d374b5-6af8-49bd-8d9b-03c10dce57c3)

[supportdata-LA3T-20-1-3.23.12.0-202312112003.gz](https://github.com/aredn/aredn/files/13639921/supportdata-LA3T-20-1-3.23.12.0-202312112003.gz)
[supportdata-LA3T-20-1-NIGHTLY-202312111946.gz](https://github.com/aredn/aredn/files/13639922/supportdata-LA3T-20-1-NIGHTLY-202312111946.gz)

**Comment by CoolAEW** [comment]
Both remote nodes are Ubiquiti NanoBridge M5
I'll try the next nightly when it's released.

Also, here's the support data from the node which is currently working with the current nightly build.
[supportdata-LA3T-20-2-NIGHTLY-202312121620.gz](https://github.com/aredn/aredn/files/13649889/supportdata-LA3T-20-2-NIGHTLY-202312121620.gz)

**Comment by aanon4** [comment]
Thanks.
A new nightly should be available to test.

**Comment by CoolAEW** [comment]
Loaded the newest nightly and that seems to have resolved the issue.

**Comment by aanon4** [comment]
Could I send you a custom build to also try?

**Comment by CoolAEW** [comment]
Yes, send it over and I'll download it later today

**Comment by aanon4** [comment]
[aredn-kn6plv-wireless-mon-ac-e7181b73-ath79-generic-ubnt_nanobeam-ac-gen2-squashfs-sysupgrade.bin.zip](https://github.com/aredn/aredn/files/13665754/aredn-kn6plv-wireless-mon-ac-e7181b73-ath79-generic-ubnt_nanobeam-ac-gen2-squashfs-sysupgrade.bin.zip)

Give this a try when you have a moment.  Please give it 5 minutes (ie plenty of time) to make a connection after it reboots on the node previously not connecting over wifi.

There's a bug in the firmware for Mikrotik which requires some workarounds in AREDN to make it connect when it initially fails. As this Ubiquiti firmware also comes from the same provider, it's possible it has the same bug. I've enabled the workaround here to test this idea.  Thanks for helping out - much appreciated.

**Comment by CoolAEW** [comment]
Ok, tried the build now and gave it 20mins, but it still haven't connected to the remote node. It shows up in the mesh status list, but only with IP. On the neighbours list it shows as Idle.
![image](https://github.com/aredn/aredn/assets/5229105/fc15e4ac-3b55-4ab3-a4d3-d9cb958b1b1d)
![image](https://github.com/aredn/aredn/assets/5229105/ae7daa9d-9f82-4a7e-a012-19900a20d178)
[supportdata-LA3T-20-1-202312132349.gz](https://github.com/aredn/aredn/files/13666511/supportdata-LA3T-20-1-202312132349.gz)

**Comment by aanon4** [comment]
Thanks. I guess this firmware isn't viable then.

**Comment by aanon4** [comment]
If you have a moment to try today's nightly on your nodes, that'd be fantastic.

**Comment by CoolAEW** [comment]
20231214-b2fb79d?
I just installed it, it works.

**Comment by aanon4** [comment]
Yes, and thanks. I'll close this now.
