### ISSUE TITLE
Corrupt mesh status current neighbor node name on TP-Link CPE 710 on 3.23.12.0

### ISSUE THREAD

**Issue by alchemy33** [aredn/aredn#1009]
Node name of TP-Link CPE 710 V1 appears incorrect on Mesh Status page of RF connected nodes.  The expected node name would be "KE3KQ-5G-ROFO" in the Current Neighbors field.  The displayed name is "dtdlink.KE3KQ-5G-ROFO /KE3KQ-5G-ROFO.local.mesh". This name is evident on nodes of Mikrotik SXT 2 & 5 GHz and GL-USB150 2 GHz

This was also like this in 10/18/23 nightly builds and also remains this way in current firmware version release 3.23.12.0

Expected behavior is the node name to be displayed on other nodes as "KE3KQ-5G-ROFO".  If dtd then this be appended after the node name and not as a prefix.  The "/" and repeat of the node local address seems related.  I suspect that this naming structure is related to other observations but this is the most obvious.  All this is RF, as I do not tunnel.  Installation of the current release firmware was uneventful.

I am attaching 2 images.  One is the basic node status screen of the TP-Link CPE710 v1.  The second is the mesh status page from an RF connect Mikrotik SXT node displaying the incorrect node name.

Images in comment post following.

Thanks for looking into this!

**Comment by alchemy33** [comment]
Image of basic TP-Link CPE 710 v1 node screen.

![IMG_0942](https://github.com/aredn/aredn/assets/37740800/02c04be4-aa76-4d8e-986d-5ecd0538b5fe)

Image of how node name is displayed on an RF connected node

![IMG_0941](https://github.com/aredn/aredn/assets/37740800/e914a427-58d9-43ff-8d21-21709c69cba6)

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1128

**Comment by aanon4** [comment]
This fixes the problem you're seeing. However, it's an install level fix so probably wont help you unless you reinstall the node from scratch.

**Comment by alchemy33** [comment]
Wonderful!   I installed the CPE710 factory.bin and sysupgrade.bin nightly 3/27/24 files last night and can confirm the node name fix as noted in #1128.  Thanks Tim!
