### ISSUE TITLE
Services are not being advertised

### ISSUE THREAD

**Issue by kc2cbd** [aredn/aredn#1016]
### Describe the bug
In the latest nightly Services are not being advertised.

- [ ] Does this issue still occur on the latest version? (**Required**)
 YES

### Expected behavior
Services to be advertised

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.
![image](https://github.com/aredn/aredn/assets/25018130/6d97719c-fa3f-43c1-973b-d981be0bb1b8)

**Comment by aanon4** [comment]
Nightly?

**Comment by kc2cbd** [comment]
Thanks.
Is there something I can do that will make it work for the time being?

**Comment by aanon4** [comment]
Just go back to the release until tomorrow's nightly.

**Comment by aanon4** [comment]
If you could verify that today's nightly fixes the services issue, that'd be fantastic.

**Comment by kc2cbd** [comment]
Issue seems to be fixed
