### ISSUE TITLE
New nightly builds don't show up when already on a nightly build

### ISSUE THREAD

**Issue by CoolAEW** [aredn/aredn#1020]
### Describe the bug
When trying to update from one nightly build to another nightly build no build shows up. I'll have to downgrade to a stable build before nightly builds shows up again.

- [ x] Does this issue still occur on the latest version? (**Required**)

### Expected behavior
When refreshing the available firmware list i expect the newest nightly build to show even when I'm already running a previous nightly build

### Screenshots
Here i expect to see "20231214-b2fb79d" in the list of available updates
![image](https://github.com/aredn/aredn/assets/5229105/6f59dbc3-d22c-4543-a545-74cdc7b554ac)

### Additional context
None

**Comment by Orv** [comment]
I've found that it occasionally takes two or three tries for the latest nightly build to show up in the refreshed list.  But it eventually appears.

**Comment by CoolAEW** [comment]
Ok, after 3 refreshes it showed up. But the refresh took a long time aswell.
![image](https://github.com/aredn/aredn/assets/5229105/4ed3abee-e776-4388-ade5-a390dc818325)

**Comment by aanon4** [comment]
I dont have a good explanation, at least when it comes to the code on the node and the code on the server. Neither has changed recently.

**Comment by dman776** [comment]
I have been running the AFS updater manually while I figure out why the nightly build fails on that step.Thanks,DarrylOn Dec 14, 2023, at 11:46 AM, Tim Wilkinson ***@***.***> wrote:﻿
I dont have a good explanation, at least when it comes to the code on the node and the code on the server. Neither has changed recently.

**Comment by aanon4** [comment]
@dman776 It should be fixed and you shouldnt have to do that anymore.
