### ISSUE TITLE
MikroTik RBLHG-5HPnD-XL antenna specs in error

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1032]
### Describe the bug
Antenna gain and beamwidth for MikroTik RBLHG-5HPnD-XL are incorrect
- [ ] Does this issue still occur on the latest version? (**Required**)
Yes
### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.

### Additional context
Gain should be 27 dBi; beamwidth should be 6.4 degrees

**Comment by aanon4** [comment]
Do you want to post a screenshot? Because the data in the radio file reads 27/6.4

**Comment by Orv** [comment]
![image](https://github.com/aredn/aredn/assets/1124405/bf89c90e-dd7a-44fa-a126-400b4c77ddab)

**Comment by Orv** [comment]
Very confusing discussion in the AREDN forums.   radio file is correct.
