### ISSUE TITLE
(Request) Ubiquiti Routerstation support

### ISSUE THREAD

**Issue by alphafox02** [aredn/aredn#105]
I realize it’s old and not many my have it laying around, but could the original routerstation be taken into account? I see the ar71xx profile is being used. I realize the combination of WiFi cards can change, but maybe there’s a profile for a certain recommended type of pci card for those with ones still laying around.

**Comment by dman776** [comment]
consider once we upgrade to Openwrt 21.02.x

**Comment by cTurtle98** [comment]
> consider once we upgrade to Openwrt 21.02.x

this has been done now

**Comment by alphafox02** [comment]
That’s incredible, and guess what I have the original router station sitting right here with two older compex 802.11 ath9 cards!
