### ISSUE TITLE
20240102-6d8528f: MikroTik SXTsq 5 ac (RBSXTsqG-5acD): No DHCP offer on ethernet port

### ISSUE THREAD

**Issue by nc8q** [aredn/aredn#1050]
Loaded Nightly 20240102 onto my SXTsq-5ac.
My workstation did not obtain an IP address via DHCP.
Loaded 3.23.12.0 and my workstation obtained and then it obtained an IP address via DHCP.

### Expected behavior
I expected my workstation to obtain an IP address via DHCP.
### Screenshots

![nc8q-sxtsq-5ac-DHCP-reserved](https://github.com/aredn/aredn/assets/60478779/26db681b-da20-4d63-aba6-5af904d33c15)

Workstation does not obtain reserved IP address.

**Comment by aanon4** [comment]
Did this start happening on a particular nightly?

**Comment by aanon4** [comment]
Closing due to no feedback to help debug.
