### ISSUE TITLE
Enhancement - Status of Upload/Download Xfer to node firmware

### ISSUE THREAD

**Issue by NickSchmitz** [aredn/aredn#1165]
Would like real time progress bar for data transfer of upload/download of firmware to node.

When updating node over remote link/tunnel it can take minutes to xfer data. 
More minutes to program node, re-boot, etc. 

Would like to see FW got there, programming started. Any further details possible.

Current best case you get display of retries after the fact when xfer fails.
But only if data connection NOT reset.

**Comment by Orv** [comment]
This appears to have been implemented in the latest nightly build.   Load & recheck, report results.

**Comment by aanon4** [comment]
Kind of. We now show progress while flashing, but not while downloading the firmware.

**Comment by NickSchmitz** [comment]
Yes, that is the point - I've had problems in data xfer. Upload local image
just starts, top bar goes back & forth for minutes, then connection resets.
No feedback.

I'd like to see feedback data xfer is proceeding correctly. It appears we
now have a timer set for the minutes the flashing / reboot should take
Nb240417.

 When the image it downloaded from the repository, I've seen an error log
stating x%, bytes, errors, etc - dumped after a crash.

Real time feedback pls.

**Comment by NickSchmitz** [comment]
Which build?

20240905-b316964  Doesn’t demo this fix

New UI - Mesh    260    nodes    734    devices

      Old UI - host entries: 260 nodes / 734 total devices

**Comment by NickSchmitz** [comment]
Also NOT implemented with:
firmware version:model: | 20240906-f5ef0ec GL.iNet GL-AR750
