### ISSUE TITLE
hAP-AC2 all tunnels showing LQ 50%

### ISSUE THREAD

**Issue by AI7NC** [aredn/aredn#1170]
### Describe the bug
Device has been running 2 days since last reboot. All tunnels indicate 50% LQ in the status page. Neighbor status page indicate 100% quality. MTR to the tunnelled nodes indicate no packet loss and jitter << average ping.

### Interventions tried
Rebooting my device does not resolve the issue. Disable/enable tunnels didn't resolve. 

Running 3.23.12.0 - [ ] Does this issue still occur on the latest version? (**Required**)

### Expected behavior
Tunnels are expected to indicate 100/100 based on packet loss testing.

### Screenshots
Screenshots and support data attached. 

### Additional context
![4 21 24_Issue](https://github.com/aredn/aredn/assets/77077873/1cc30849-1da8-4cea-895f-6fda4d64c548)
![4 21 24_Issue2](https://github.com/aredn/aredn/assets/77077873/3dfbaa88-30ff-4a24-8c0d-211bd413f696)
[supportdata-AI7NC-QTH-hAP-202404211011.gz](https://github.com/aredn/aredn/files/15052835/supportdata-AI7NC-QTH-hAP-202404211011.gz)

**Comment by KenHorse** [comment]
I am seeing similar with the exceptions some tunnels report 100% NLQ while others report either 50% or even 33%. MTR likewise shows no packet loss. I am running 20240516-5069f0e on a hAP AC2

**Comment by aanon4** [comment]
Closing as there's been no feedback on this for a while. Reopen if necessary.
