### ISSUE TITLE
3.24.4.0 for Rocket M5 XW wrong file from the software picker

### ISSUE THREAD

**Issue by k6ccc** [aredn/aredn#1179]
When using the software picker for 3.24.4.0 and enter "Rocket", the 3rd entry is "Ubiquiti Rocket M XW"  That results in the file named: aredn-3.24.4.0-ath79-generic-ubnt_bullet-m-xw-squashfs-sysupgrade.bin

The node reports that to be the wrong file (as expected) and will not accept it.

However if you select the 5th entry "Ubiquiti Rocket M5 XW XW" you do get the correct file:
aredn-3.24.4.0-ath79-generic-ubnt_rocket-m-xw-squashfs-sysupgrade.bin

**Comment by aanon4** [comment]
Fixed.
