### ISSUE TITLE
Where is blockknownencryption?

### ISSUE THREAD

**Issue by ham-k7dev** [aredn/aredn#1184]
### Describe the bug
(https://github.com/aredn/aredn/blame/3.24.4.0/files/www/cgi-bin/status#L303) directions there say: "Obtain the blockknownencryption package from the AREDN&trade; website OR refresh the Package list". I have not found it in either place.

- [x] Does this issue still occur on the latest version? (**Required**)

### Expected behavior
**blockknownencryption** be available

Is this it this? https://github.com/aredn/aredn_packages/blob/develop/blockknownencryption/files/20-blockknownencryption
It uses iptables, which isn't used with the current version of AREDN, correct? Does blockknownencryption just need to be translated to "nft"? Or maybe adding the ports in the aredn_packages link above as REJECT rules to this file? https://github.com/aredn/aredn/blob/3.24.4.0/files/etc/config.mesh/firewall

**Comment by aanon4** [comment]
This package has never been ported to the current AREDN versions as it requires someone to rewrite the firewall rules from iptables to ntf. Happy for someone to do that.
