### ISSUE TITLE
On WorldMap, DtD links do not show up

### ISSUE THREAD

**Issue by k6ccc** [aredn/aredn#1191]
On the worldMap.arednmesh.or web meshmap, DtD links do not show up.  If you click on a node that has DtD link, the DtD links will show on the list, but not on the map.
If you look at this location:
https://worldmap.arednmesh.org/#17.65/34.109573/-117.852522
There should be several DtD links as shown on the edited version file uploaded.

![No DtD links](https://github.com/aredn/aredn/assets/36935831/7ea084bb-5dbf-4522-96a0-f855477b3f96)

**Comment by k6ccc** [comment]
Listing of one of the nodes that actually has DtD links
![No DtD links 2](https://github.com/aredn/aredn/assets/36935831/c4dc673f-92c4-4f38-ae4b-073296e7d22d)

**Comment by aanon4** [comment]
This is by design. Short distance DTD links are not shown as it adds unnecessary visual clutter.
