### ISSUE TITLE
WorldMap Data Export Issue

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1194]
### Describe the bug
At least the .csv export from the WorldMap appears to exclude WireGuard tunnels.

- [ ] Does this issue still occur on the latest version? (**Required**)
Yes

### Expected behavior
All versions of tunnels should be included in all the data exports formats

**Comment by aanon4** [comment]
Looks like an error in sysinfo.json where the node doesnt count these when generating the data.

**Comment by Orv** [comment]
This works as expected.
