### ISSUE TITLE
hAPac2 on 3.24.4.0 changes 172.31 address on tunnel server on every reboot

### ISSUE THREAD

**Issue by KQ6EO** [aredn/aredn#1198]
### Describe the bug

After 3.24.4.0 upgrade every reboot causes the tunnel server 172,31.x.x IPs to change and he URL line goes blank.  Tunnels setup with correct IP still works even thought it shows a different IP than when it was created.  You get an invalid URL message when you try to add a tunnel node.

- [ ] Does this issue still occur on the latest version? (**Required**)

Started with 3.24.4.0 release upgrade

### Expected behavior

Before the 172.31.x.x address range did not change and the URL did not disappear.

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.

**Comment by aanon4** [comment]
Could you add the support data? Issues like this are often the result of some specific configuration corruption.

**Comment by KQ6EO** [comment]
[supportdata-KQ6EO-HAP-TSTC-202405132010.tar.gz](https://github.com/aredn/aredn/files/15314739/supportdata-KQ6EO-HAP-TSTC-202405132010.tar.gz)

**Comment by aanon4** [comment]
So in this file:

```/etc/config.mesh/vtun```

There should be a line which reads

```config network```

But it's not there. Without it, the node cannot save the ip range and tunnel name. You can log into the node and put it back by hand (make sure there's a blank line before and after it) to fix the problem for now. Then reboot and try setting the tunnels up again.

Not sure why it's missing yet.

**Comment by aanon4** [comment]
Following up on this - the `config network` option exists in the base install in the correct file, and there's no code that could remove it. So I'm not sure how it could not be there.
