### ISSUE TITLE
Can openwifi be supported?

### ISSUE THREAD

**Issue by BloodBladeW** [aredn/aredn#1231]
### What is the hardware/platform
openwifi

### Links
[openwifi](https://github.com/open-sdr/openwifi)

### Additional context
This is an open source Wi-Fi design based on an SDR that is compatible with many kinds of RF development boards.

I think supporting this open source design allows for more freedom than the closed source RF modules used in commercial Wi-Fi devices.

**Comment by aanon4** [comment]
Support for something like this has a couple of prerequisites:  First, a setup I can buy, and second, this setup running OpenWRT out of the box.
