### ISSUE TITLE
hAP2 in NAT mode with WG tunnel, LAN devices can not access anything over WG tunnel, but it can over Wifi/DtD

### ISSUE THREAD

**Issue by Marx1** [aredn/aredn#1242]
### Describe the bug
a hAP2 in NAT mode, any lan devices can not access any devices/nodes across the WG tunnel; however they can access across a RF link.

- [ ] Does this issue still occur on the latest version? (**Required**)
Tested on production and nightly.

### Expected behavior
WG tunnels act the same from LAN -> WG as LAN -> Mesh/RF

### Screenshots
Traceroute from lan device on W6CX-FieldDay-Logging connected to KG6MDW-HAP2 via WG tunnel over t-mobile:
![image](https://github.com/aredn/aredn/assets/4861651/e628a149-b370-467d-b95e-4b82760ba3e0)

Traceroute from lan device on W6CX-FieldDay-Logging connected to KG6MDW-HAP2 via 5ghz mesh, and t-mobile disconnected (DNS hadn't populated yet):
![image](https://github.com/aredn/aredn/assets/4861651/b8c9a611-90c4-4555-9efd-4c9dd14a769c)

### Additional context
This sounds more like rule issues that Tim fixed in #1216 I don't have enough brain cycles to dig though the code right now to try and understand why it's happening - I'll see if I can do it later.

Attached are support dumps from both devices.

[supportdata-W6CX-FieldDay-Logging-202406132057.tar.gz](https://github.com/user-attachments/files/15829005/supportdata-W6CX-FieldDay-Logging-202406132057.tar.gz)
[supportdata-KG6MDW-HAP2-202406131358.tar.gz](https://github.com/user-attachments/files/15829006/supportdata-KG6MDW-HAP2-202406131358.tar.gz)

**Comment by aanon4** [comment]
Could you let me know if this works correctly over a legacy (non-wireguard) tunnel? That'll help me track down the problem.

**Comment by Marx1** [comment]
Hi Tim,

I switched over the the legacy tunnel, and at the same time realized KG6MDW-HAP2 was still on production, so I upgraded to nightly as a second check-

Legacy Tunnel does not work:
![image](https://github.com/aredn/aredn/assets/4861651/b2bb586a-1330-4e2e-96b1-04c0dec13620)


Neither does Wireguard (verifying with both ends on nightly):
![image](https://github.com/aredn/aredn/assets/4861651/6c0f6aee-d047-42ab-b91b-6ff3ddeca593)


So I'm thinking this is more of a case that there are limited users using NAT mode, and initiating a connection form the LAN targeting a mesh endpoint.

**Comment by aanon4** [comment]
NAT mode isn't used much. At least it's consistently broken which makes it easier to work out. Thanks.

**Comment by Marx1** [comment]
Np, Thanks  for having it. I have a couple of good use cases - for this one the NAT/LAN will be the logging network for Field day, and I want it to be able to access AREDN for resources like NTP/PSK and PBX etc while not exposing all of the devices and log server directly to AREDN.

We use it on Mt Diablo for the same reasons.

**Comment by aanon4** [comment]
Another question - does it work across a DTD connection? Looking at the code I think it should only work across wifi right now .. but because that seems slightly unbelievable, can you check? Thanks.

**Comment by aanon4** [comment]
Any chance you can see the ping packets arrive at the target? I'm wondering if it's the replies which are having trouble.

**Comment by Marx1** [comment]
here's via DTD:

![image](https://github.com/aredn/aredn/assets/4861651/b228da1c-1b20-46fd-bbd7-278975908ac3)
![image](https://github.com/aredn/aredn/assets/4861651/d89878fa-aa01-44d4-94fb-6debe8592e2b)


here's via WG:

![image](https://github.com/aredn/aredn/assets/4861651/1e597167-5262-4369-bab0-ae38da5865ae)


I think you're on to something. It acts like connection tracking in Nat isn't working.

tcpdump on w6cx-fieldday-log WG Interface shows tx and rx:
![image](https://github.com/aredn/aredn/assets/4861651/9c2605d9-5fba-4d86-9ab4-891cca0875a1)

but br-lan only shows the TX from my bench pc:

![image](https://github.com/aredn/aredn/assets/4861651/7bd25ac2-2036-487d-be4f-edb82281ebad)

**Comment by aanon4** [comment]
So the nat firewall configuration has some special rules, and those rules are very old (9-ish years) despite being re-written when the firewall changed. I suspect they were never updated when tunnels were added. Also I think there may be better support in vanilla OpenWRT these days for what these old rules were doing. So I'll see if going that route will fix this, but the changes are a little more complexed.

**Comment by aanon4** [comment]
I've sent you a test image for the hAPac2

**Comment by Marx1** [comment]
Thanks, I got it installed and tested - 

here's over WG: 
![image](https://github.com/aredn/aredn/assets/4861651/201a30c1-6763-4661-8fa0-b59293a63984)

here's  over the legacy tunnel:
![image](https://github.com/aredn/aredn/assets/4861651/8436dc4d-b551-48ef-9f93-9ab350ea8526)

doesn't seem to be working

**Comment by Marx1** [comment]
Here's it from DTD:
![image](https://github.com/aredn/aredn/assets/4861651/dac4a776-9fbf-42ad-a583-abde01201306)

I need to physically move it closer for rf link, but I think this shows it's a all-or-nothing as you suspected.

**Comment by aanon4** [comment]
I sent over another test build. Looks like they were messing with the ip rules, so despite the firewall being correct, the reply packets didn't go the right way through the routing tables. I'm really not sure whey they made it this complicated originally.

**Comment by Marx1** [comment]
NEW software provided 2:41pm:

Over legacy tunnel:
![image](https://github.com/aredn/aredn/assets/4861651/083b6abc-639f-41e5-b2df-d9328e6c372f)

over WG:

![image](https://github.com/aredn/aredn/assets/4861651/c82bdcd3-3d56-47f0-9232-a92ff88b4973)


and DTD:

![image](https://github.com/aredn/aredn/assets/4861651/4b5a5ceb-713c-4103-91c7-43f94f3d022d)


Looks good to me. Do you want me to test RF also?

**Comment by aanon4** [comment]
It shouldnt be necessary. Thanks for testing.

**Comment by Marx1** [comment]
NP thanks for working on it before FD!

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1243

**Comment by aanon4** [comment]
Please reopen if this is still a problem.
