### ISSUE TITLE
MTR on Aredn?

### ISSUE THREAD

**Issue by NickSchmitz** [aredn/aredn#1246]
I'd like a little help on using/loading MTR to
diagnose my Aredn network.

In particular:
1. Where do I get the MTR ipk for Aredn? 
2. is it mtr-nojson 0.95.3? 
      https://openwrt.pkgs.org/23.05/openwrt-pack
4. How do I tracerout & ping Nodes? Like this?
   https://github.com/Homebrew/homebrew-core/issues/92374

Thanks in advance for the elmer!

Nick AI7OH

**Comment by NickSchmitz** [comment]
Nevermind, maybe...

I found this:
https://fornex.com/en/help/win-linux-mtr/

We'll see if this is the answer.

Nick AI7OH

**Comment by aanon4** [comment]
The AREDN forums of Slack might be a better place to find this sort of help.
