### ISSUE TITLE
AREDN Online Map Data Upload fails - last many nightlies including RC Candidate 20240618

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#1247]
### Describe the bug
A clear and concise description of what the bug is
Upload Data to AREDN Servers fails with the following message:  
Configuration NOT saved!
ERROR: Cannot update online map.

- [ ] Does this issue still occur on the latest version? (**Required**)
- [ ] Yes - for the last several weeks of nightlies including 20240618

### Expected behavior
I expect for it to upload successfully and report as such.

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.
Sample of the text is listed in the description above.

### Additional context
Problem is device independent.  Multiple nodes of different model and manufacture yield the same result.

**Comment by aanon4** [comment]
Nothing to do with the AREDN code - the service is currently offline.

**Comment by k1ky** [comment]
Copy that - I noted that particular map product is currently unavailable.  The "world map" does work and is picking up and publishing our nodes.

**Comment by k1ky** [comment]
Will anxiously await the return of the "static" map. (Any estimate of restoration?) Closing this issue since not related to firmware.

**Comment by k1ky** [comment]
3.24.6.0 Map Data upload working - old original MeshMap is back online and functioning.
