### ISSUE TITLE
Latest Nightly Build on hAP AC2 not showing new GUI

### ISSUE THREAD

**Issue by KenHorse** [aredn/aredn#1264]
### Describe the bug
Using FireFox, cleared the cache but don't see any difference in GUI

Latest nightly - 20240816-0432bf3 

### Expected behavior
Expected new GUI ala YT video

I don't think a screenshot is neccesary

**Comment by aanon4** [comment]
Could you add a screen shot of the node's status? Thanks.

**Comment by KenHorse** [comment]
Argghh, I just noticed the new button to select the new GUI. Sorry, it's good
