### ISSUE TITLE
No Commit function available when deleting legacy tunnels.

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1266]
### Describe the bug
On a tunnel server with many tunnels, when deleting disabled legacy tunnels Commit button doesn't appear,

- [ ] Does this issue still occur on the latest version? (**Required**)  Yes, new UI.

### Expected behavior
This is the Ventura County tunnel server, an ac2 with the largest known number of tunnels on the AREDN network.
Note - this function worked with my home ac2, which only has a few tunnels
[supportdata-K6PVR-VC-TUNNEL-SRV-2024-8-16-11-26.tar.gz](https://github.com/user-attachments/files/16640495/supportdata-K6PVR-VC-TUNNEL-SRV-2024-8-16-11-26.tar.gz)

**Comment by aanon4** [comment]
I'm assuming they dont actually get deleted?

**Comment by KD4WLE** [comment]
I'm seeing the same with Wireguard tunnels on a Proxmox node, There is no commit button after removing the tunnel.

**Comment by aanon4** [comment]
Same question I asked above - do the tunnel actually get deleted?

**Comment by aanon4** [comment]
Also, as I can't reproduce this, I'm probably going to need access to a node with this problem.

**Comment by KD4WLE** [comment]
Hit me up off list, and ill let you lose in kd4wle-titusville-tunnelserv.local.mesh

***@***.***


From: Tim Wilkinson ***@***.***>
Date: Saturday, August 17, 2024 at 12:14 AM
To: aredn/aredn ***@***.***>
Cc: Sean Haga (KD4WLE) ***@***.***>, Comment ***@***.***>
Subject: Re: [aredn/aredn] No Commit function available when deleting legacy tunnels. (Issue #1266)

Also, as I can't reproduce this, I'm probably going to need access to a node with this problem.

**Comment by aanon4** [comment]
Apparently Javascript in the browser and Javascript in OpenWRT disagree on exactly how to decode a url encoded string. Not sure exactly how yet.

**Comment by aanon4** [comment]
... sort of. It seems url encoded arguments are limited to 4k in length, so the problem here is that there are lots of tunnels and so the argument gets too long. I will split it up to avoid this issue.

**Comment by Orv** [comment]
Now works as expected (at least deleting one tunnel)
