### ISSUE TITLE
new UI :wifi signal tool page

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn#1276]
Note: wifi signal tool page docent work / display data in when in wan wifi client mode.

Version Nighty 20240816-0432bf3

![image](https://github.com/user-attachments/assets/63f4e330-5d61-4a86-a02f-dafd3de75385)

**Comment by aanon4** [comment]
What does the current UI do for this case?

**Comment by mathisono** [comment]
In the old UI, im unable to find the wifi scan. It appears to be hidden. The old UI dose show the following: 
![image](https://github.com/user-attachments/assets/22dc03a1-5ffb-400d-b493-c813ed83e55d)

**Comment by mathisono** [comment]
I dont see a cell with WAN info, consider adding one for wan info.

**Comment by aanon4** [comment]
Done
