### ISSUE TITLE
New UI: Provide information about local devices (e.g. IP address)

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn#1279]
"lan devices" don't show any info regrading the device besides the name. The request is to add the ip address beside the name. The Ip Address would be a clickable link. Allso consiter Combining info for from the Lan DHCP in to the same cell.

Curent UI
![image](https://github.com/user-attachments/assets/4d2d1bb8-d751-446e-b6bc-dd2bfc77de64)

Suggested Look:
![image](https://github.com/user-attachments/assets/d0958b05-ac8e-4a19-91ed-a4011e4b5ae5)

**Comment by aanon4** [comment]
Not going to change the information shown for local nodes on the main page, but have made them clickable like neighbor nodes.
