### ISSUE TITLE
Login not being persisted

### ISSUE THREAD

**Issue by aa3jc** [aredn/aredn#1286]
If you open up a node, click on "New UI", and click on the admin drawing at the top right, you must enter the password each time as Chromes Password Manager does not work or offer to save the login data

**Comment by aanon4** [comment]
I dont see this on Chrome, Firefox or Safari. Login is maintained using a cookie. Do you have anything installed on your browser which might be messing with that?  Also, can you be more specific about "each time" - thanks.

**Comment by aa3jc** [comment]
I flashed the new Nightly that just was released, the Password Manager is now working!  Thanks!
