### ISSUE TITLE
New UI: Add additional icons to sidebar for ez of navigation

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn#1290]
Add an icon that links to the config mode, from status mode UI. Then for the Config mode UI add an icon that links to context menu containing all config pages. Similar to the Tools icon.  

![image](https://github.com/user-attachments/assets/4f689912-c000-4fa9-88b9-20da11f321a9)

**Comment by mathisono** [comment]
![image](https://github.com/user-attachments/assets/a31911a8-86d1-440a-bf15-6115314ac9ea)

**Comment by aanon4** [comment]
No plans to chance how the navigation is done.
