### ISSUE TITLE
NLQ percentage not calculated properly.

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1293]
### Describe the bug
NLQ links showing at 500% on certain links.

- [ ] Does this issue still occur on the latest version? (**Required**)
Yes
### Expected behavior
Expected 100%
### Screenshots

![image](https://github.com/user-attachments/assets/2b655c56-d302-4e22-a5c2-e306ce1fb745)

[supportdata-W6BI-SHACK-NODE-2024-8-17-12-7.tar.gz](https://github.com/user-attachments/files/16646266/supportdata-W6BI-SHACK-NODE-2024-8-17-12-7.tar.gz)

**Comment by aanon4** [comment]
What are the weights on these tunnels? And are they the same at each end? I assume I've got some math wrong related to tunnel weights.

**Comment by Orv** [comment]
Client end: In the old UI, the tunnel weight is set to 5 .  In the new UI, no Wgt values are shown for any tunnels.
Server end: The tunnel weight is set to the default of 1.

**Comment by aanon4** [comment]
Is it also 500% if you open the dialog?

**Comment by Orv** [comment]
Yes.
