### ISSUE TITLE
New UI: Firmware tab (fetch & update) location

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn#1294]
New UI: Firmware tab (fetch & update) location

The "fetch & update" button is pushed to the bottom of the tab. It lost from view. The "fetch & update" button is outside of the field of view. Im suggesting the "fetch & update" be locked to the top of the tab or up with the tabs header text, between "Firmware
configuration" and the "Help" button.   

![image](https://github.com/user-attachments/assets/5b27bd68-3c35-4cdd-bd6a-00e52c30e804)

![image](https://github.com/user-attachments/assets/a161aa6c-9eaa-4b00-9846-9eb26479258d)

**Comment by aanon4** [comment]
Not quite what you suggested, but keeping it in view seems like a good idea. So I'm locking it at the bottom.
