### ISSUE TITLE
Minor visual glitch

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1295]
### Describe the bug
A little "scroll arrow" appears on the Time menu, but there's no scroll (see screenshot)
- [ ] Does this issue still occur on the latest version? (**Required**)
Yes
### Expected behavior
Shouldn't appear
### Screenshots

![image](https://github.com/user-attachments/assets/66146250-4ff0-4d3e-b489-82defb0ab0c0)

**Comment by aanon4** [comment]
I dont see it on any of my browsers (Safari, Firefox, Chrome on Mac)

**Comment by Orv** [comment]
Just noticed it's also at the top.  This is Firefox on Linux.  I'll check Chrome also.

![image](https://github.com/user-attachments/assets/67959dc8-e81e-48da-a251-448fb95e364e)

**Comment by Orv** [comment]
I was in error.  Those screenshots are from Chrome on Linux.  Those visual artifacts do NOT appear in Firefox on Linux (Kubuntu 24.04).

**Comment by k6ccc** [comment]
This laptop has a fairly low vertical resolution, on the time setting popup, there is a scroll bar with the arrows at top and bottom.  Using Firefox.

**Comment by aanon4** [comment]
As this appears to be a browser rendering anomaly, I'm going to hope they fix their browser.
