### ISSUE TITLE
New UI: Firmware tab (Firmware &Hardware type) location

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn#1296]
New UI: Firmware tab (Firmware &Hardware type) location

Move Firmware & Hardware type from the scroll area and place them up with the header and help button. 
This will compact the tabs footprint. It's not a fillable field..

![image](https://github.com/user-attachments/assets/f120e65e-9502-414a-85ea-47e13bb01bdc)

**Comment by aanon4** [comment]
I'll think about how this data might be compressed without ruining the general dialog layout. I wont put it in the header or footer however.

**Comment by aanon4** [comment]
New design makes this smaller.
