### ISSUE TITLE
Tunnel Notes not migrating or displayed new UI

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#1306]
### Describe the bug
Tunnel Client and Server Connection notes are not transferred/displayed in the new UI

- [x] Does this issue still occur on the latest version? (**Required**)
Yes - N20240818 

### Expected behavior
Expect to see existing notes of Tunnel Clients and Server entries in old UI in the new UI

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.

**Comment by aanon4** [comment]
Looks like I just got this completely wrong, not only forgetting to save new notes, but also getting the name of the notes wrong too. Will fix that today.

**Comment by aanon4** [comment]
We did an extra build today, so if you want to update your node again and let me know if this is fixed, that'd be lovely.

**Comment by k1ky** [comment]
Yes, that fixed it!
