### ISSUE TITLE
Reboot functions broken in nightly build 20240818-f38f753

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1308]
### Describe the bug
Reboot function no longer works.

- [ ] Does this issue still occur on the latest version? (**Required**)
Yes
### Expected behavior
A node reboot should occur

### Additional context
I'd add a support data file, but the function to generate one also no longer appears to work.

**Comment by aanon4** [comment]
You mean rebooting from the top/right menu? It works when I try it. Do any of the other menu items work/not work?

**Comment by aanon4** [comment]
Okay, I can reproduce it one some nodes but not others. Seems likely this is related to changes to allow copy-n-paste to work again. Will look at it.

**Comment by aanon4** [comment]
Scrub that. Looks to be crashing the web server on MIPS devices only.
