### ISSUE TITLE
Commit button missing when setting 24 hour time - nightly build 20240818-f38f753

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1309]
### Describe the bug
A Commit button doesn't appear after setting 24 hour time and closing the Time window
- [ ] Does this issue still occur on the latest version? (**Required**)
Yes
### Expected behavior
Expected a Commit button, to allow time format change to be committed.

**Comment by aanon4** [comment]
Works okay for me.

**Comment by aanon4** [comment]
Looks like this is crashing uhttp on MIPS devices only.
