### ISSUE TITLE
Daily Watchdog Hour finer control

### ISSUE THREAD

**Issue by edkraus** [aredn/aredn#1311]
I would like to use the **Daily Watchdog Hour** feature in Advanced Config to rest some nodes daily.  Some sites have many nodes so I don't want to lose control of the site or have OLSR go crazy with five or six nodes rebooting all at once.  I would like to specify to the minute the time of day when the node reboots.  As of now I can say 1 or 2 for 01:00 or 02:00 but what I would like is to be able to restart one node at 01:00 and the next at say 01:10 then 01:20 ... and so on.

**Comment by aanon4** [comment]
Seems like a good use case. It may have to wait a release cycle as we're trying to limit the current work to the new UI.
