### ISSUE TITLE
hAP ac lite not displaying firmware status

### ISSUE THREAD

**Issue by WT3** [aredn/aredn#1332]
MikroTik RouterBOARD 952Ui-5ac2nD (hAP ac lite) not displaying firmware status in new user interface. (IE. update available or up to date.)

![image](https://github.com/user-attachments/assets/956b2071-ba07-424a-aec7-7711ab031047)

Bill -WB3CQK

**Comment by aanon4** [comment]
Give it a bit. It checks every hour if it doesnt know the status, and once a day if it does.

**Comment by aanon4** [comment]
Let me know if this status doesnt show up by tomorrow or I will close this bug then - thanks.

**Comment by WT3** [comment]
Ok I will keep an eye on it.

Thanks,
Bill

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aanon4** [comment]
This is how it looks to me:
<img width="316" alt="Screenshot 2024-08-20 at 3 32 30 PM" src="https://github.com/user-attachments/assets/dac774f3-1275-4195-9ef9-48d030266615">
Looks okay.

**Comment by WT3** [comment]
Ok thanks for checking it. I am our of the house at the moment and can't check  from here.

Bill
________________________________
