### ISSUE TITLE
Notes missing from tunnels in new UI

### ISSUE THREAD

**Issue by KD4WLE** [aredn/aredn#1336]
### Describe the bug
New UI - Notes in Tunnels (server) didn't move from old UI. Switching back to the old UI reveals the comments. 

- [ ] Does this issue still occur on the latest version? (**Required**)
Yes

### Expected behavior
Notes should be in new UI.

**Comment by aanon4** [comment]
What version are you running? This was fixed and the fix confirmed to be working.

**Comment by KD4WLE** [comment]
My error.. i forgot to update this node to latest.  this is now resolved.
