### ISSUE TITLE
Display difference between old and new UI

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1337]
### Describe the bug
In the old UI, the DHCP configuration shows the starting and ending IP addresses in the pool.
In the new UI, it appears to show the starting and ending ACTIVE (issued) addresses.  The old version would be preferable in my opinion

- [ ] Does this issue still occur on the latest version? (**Required**)
Yes
### Expected behavior
Same behavior between old and new UIs

### Screenshots
![image](https://github.com/user-attachments/assets/422f8669-b951-44a1-8ecd-6039afa683c3)

![image](https://github.com/user-attachments/assets/2b5688f9-698d-4b16-98c7-cf6032f53b87)

**Comment by aanon4** [comment]
You're on today's nightly, yes? I dont see this today. What's the node name so I can look?

**Comment by aanon4** [comment]
Worth noting that if you change the DHCP size value from 5 to 13 *before* todays update, these values will be wrong. Best to change it again.

**Comment by aanon4** [comment]
Looks like it was set to 13 when this feature was broken. Now that's correct. the fix was to change it to 29 and then back to 13 again and commit.
