### ISSUE TITLE
Cancel Button for all Windows

### ISSUE THREAD

**Issue by K5RA** [aredn/aredn#1358]
In the new UI, 20240822 nightly build and previous, neither the Firmware config nor Packages config window has a Cancel Button.  Pressing Done will cause window to disappear, but is confusing since other windows have way to exit back to Admin screen.

Each window of the new UI should have a Cancel button.  Add Cancel button to Firmware config and Packages config windows.

System: hAP ac lite, latest nightly, r-pi 5B, latest bookworm.

**Comment by aanon4** [comment]
These windows dont have Cancel buttons because the actions you take within them cannot be cancelled but take place immediately. This is unlike other windows where Cancel will abort what changes you have made.
