### ISSUE TITLE
can't upgrade from nightly to anythign else

### ISSUE THREAD

**Issue by charlieh0tel** [aredn/aredn#1374]
### Describe the bug

my hap-ac3 was on 3.24.6.0.

i upgraded to nightly 20240818-4c57f60  to test the new UI.

i can no longer upgrade to the next nightly or back to 3.24.6.0.

I get:

Firmware CANNOT be updated
upgrade is not available

- [ ] Does this issue still occur on the latest version? (**Required**)

yes.

### Expected behavior
Able to upgade to next nightly or back to 3.24.6.0

### Screenshots

![image](https://github.com/user-attachments/assets/bfa36683-0cb0-4cc1-b2a5-dc87626f553b)

**Comment by aanon4** [comment]
You need to use the new UI to upgrade or downgrade.

**Comment by aanon4** [comment]
I will try to keep both working - https://github.com/aredn/aredn/pull/1375

**Comment by aanon4** [comment]
Procedure:

To go back to 3.24.6.0 please use the firmware tools in the new UI. Refresh the download list and select the previous release.
Once downgraded you will need to restore the original firmware location in the advanced settings. You'll find a blank field towards the bottom of them in the Firmware section. To restore the default path press the "Set to Default" button then hit "Save".

**Comment by charlieh0tel** [comment]
i flashed the latest nightly using the new UI.

thank you es 73.
