### ISSUE TITLE
pop-up images

### ISSUE THREAD

**Issue by nc8q** [aredn/aredn#1383]
**Is your feature request related to a problem? Please describe.**
In the New UI:
In the configuration pop-up images:
I cannot tell if there is a color difference in slider buttons.
I cannot tell what a button left or button right indicates...on/off,enable/disable

**Describe the solution you'd like**
A configuration page instead of an overlaid image pop-up.
I cannot do a clear print-screen because text in the grayed-out background also goes to the printer. 

**Describe alternatives you've considered**
How do I display/share tunnel credentials?

**Additional context**
![0](https://github.com/user-attachments/assets/24d6abf9-7abf-48d2-b47d-fb6b99cb333c)

**Comment by K5RA** [comment]
New UI Documentation / Node Admin Guide / Add Tunnel / Wireguard Server gives instructions for getting server credentials that you can copy/paste into message to client.

**Comment by aanon4** [comment]
@nc8q Not sure here .. are you saying the the grey / green contrast it difficult to see?

**Comment by nc8q** [comment]
Hi, Tim:
The gray and dark-gray contrast is hard to see.
Without a comparison I cannot tell if the box was gray or darker-gray.
If the box is gray, what state does that signify?
If the box is darker-gray, what state does that signify?
![buttons](https://github.com/user-attachments/assets/768329a9-a7a2-4c32-9019-1d1019bae3f8)

**Comment by aanon4** [comment]
I must be missing something still - sorry. When the switch is off, it is red. When the switch is on it is either gray (unconnected) or green (connected). There is no darker-gray.

**Comment by nc8q** [comment]
I have deuteratopia.
I have a difficult time distinguishing among gray, red, and green,
It is not rare for me to be on a rooftop in bright sunlight configuring an AREDN node with a laptop.
I do well with radio buttons, drop-down text boxes, and hyperlinked text.
I fail when logic states are presented with only color options.
May I/we have a '1' or a '0' in the gray, red, or green rectangles?
73, Chuck

**Comment by aanon4** [comment]
So what I'd prefer to do is develop a theme which is more appropriate for people with deuteranopia, in a similar way to the recent addition of the High Contract theme for people wanting larger text and less subtle grey levels.  The problem is that I dont understand what works and what doesn't; so I need to write a guide so someone who know what they're doing can make such a thing.
