### ISSUE TITLE
NEW UI: Local Devices disappeared

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn#1385]
NEW UI: Local Devices and & Local Services disappeared after amending legacy local service enters.

I pulled the first screen shot, pulled support data and then rebooted the node....

The second screen shot shows the node after a reboot, the new ui is broken, while the old ui sill show the amended entry.

  
![Screenshot_2024-08-24_17-55-13_no lan serveces](https://github.com/user-attachments/assets/cd719384-4015-4a6f-89dc-9d35b10251ec)
[supportdata-W6BB-RFS-HUB4-2024-8-24-18-2.tar.gz](https://github.com/user-attachments/files/16738498/supportdata-W6BB-RFS-HUB4-2024-8-24-18-2.tar.gz)

--------
![Screenshot_2024-08-24_17-55-13_reboot no lan serveces](https://github.com/user-attachments/assets/f712f1b8-74d0-4686-bbb1-e8013a3ff4b1)

![Screenshot_2024-08-24_17-55-13_reboot old ui no lan serveces](https://github.com/user-attachments/assets/884eebd5-c5c4-4f14-8fd3-144d896c8213)

**Comment by aanon4** [comment]
What were the specific changes? Can you back out the changes one by one and see if you can work out which specific change causes the problem? Thanks.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1387

**Comment by mathisono** [comment]
all i did was set an service icon/type
