### ISSUE TITLE
Cursor Behavior in LAN DHCP config

### ISSUE THREAD

**Issue by K5RA** [aredn/aredn#1389]
PR #1376 reduced slightly the size of the base font on the Front Page and other windows.  Intent may have been to allow all characters of IP and MAC addresses in the LAN DHCP window to show in their cells.  This was not achieved.  However, cursor operations as described in study below permit all characters to be accessed.  Given that this is not something that is often necessary, making the Front Page as readable as possible should have priority.  
The size of the base font should be taken back to what it was in nightly 20240823.  

A Study of Cursor Behavior in  LAN DHCP config   window, AREDN new UI, 20240824 nightly build 
Test run on hAP ac lite and RP5B with latest bookworm and latest Chromium (V126…)

Address Reservations
	hostname    pointy cursor changes to vertical line when moves into cell
		one click sets line cursor between letters
		double click selects one word under cursor
		triple click selects whole entry
		in each case, cursor responds to direction arrow keys

	ip addr	nothing happens when cursor moves across cell
		one click opens a drop-down list of IPs, with the IP named in the cell highlighted 
                           N.B. - moving cursor can cause highlighted address to change
		next click closes the list

	mac addr     pointy cursor changes to vertical line when moves into cell
		one click sets vertical line cursor in the cell
		click, hold, and drag to make selection or expose ends of address
			direction arrow keys move cursor to expose ends
		two clicks select a mac address digraph or colon
			direction arrow keys move cursor to expose ends 
		three clicks select whole address
			direction arrow keys move mac address to expose ends

Active Addresses
	Hostname  pointy cursor changes to vertical line when moves into cell
		one click does nothing
		double click highlights one word
		triple click highlights whole name
		direction arrow keys appear to do nothing in hostname cells

	ip addr	pointy cursor changes to vertical line when moves into cell
		one click does nothing
		click, hold, and drag moves IP to make selection or expose ends
                        right/left direction arrow keys move address to expose ends
		two clicks highlight whole name
			right/left direction arrows move whole IP to expose ends

	mac addr	  pointy cursor changes to vertical line when moves into cell
		one click does nothing
		click, hold, and drag to make selection or expose ends of address
			right/left direction arrow keys move cursor to expose ends
		two clicks selects a mac address digraph or colon
			right/left direction arrow keys move cursor to expose ends
		three clicks selects whole mac address
			right/left direction arrow keys move selection to expose ends

end

**Comment by aanon4** [comment]
Not sure what the goal of this request is now.
