### ISSUE TITLE
UBNT Rocket M5XW doesn't show notes in New UI after upgrade N-20240824

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#1390]
### Describe the bug
Node Notes aren't shown un new UI after upgrade from 3.24.5.0 to N-20240824.  

- [x] Does this issue still occur on the latest version? (**Required**)
- [x] Yes N-20240824

### Expected behavior
Expect Notes to be shown.  They still exist on old UI screen.

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.
New UI: 
<img width="473" alt="image" src="https://github.com/user-attachments/assets/0673fec7-d344-4cac-906f-68ed5870ec5b">
Old UI:
<img width="731" alt="image" src="https://github.com/user-attachments/assets/5648aa1e-a787-44a4-92a6-acdaea727adf">

### Additional context
I do have another RKM5XW that has upgraded to N-20240824 that shows description ok in New UI, so this may be an isolated occurrence.

**Comment by k1ky** [comment]
Support Data File attached
[supportdata-KI4LMR-RKM5XW-103-LOVE-130TWR-000-2024-8-24-22-23.tar.gz](https://github.com/user-attachments/files/16738904/supportdata-KI4LMR-RKM5XW-103-LOVE-130TWR-000-2024-8-24-22-23.tar.gz)

**Comment by aanon4** [comment]
Looks like it's because the description text has an = in it; which should be fine.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1391

**Comment by k1ky** [comment]
Yup - that was it.  I thought we were past the special characters limitation.  Thanks!

**Comment by aanon4** [comment]
New code - new bugs :-) Fixed tomorrow.

**Comment by k1ky** [comment]
Tried 20240825 and inserted "=" in notes in old UI and it now reflects the description in both old and new IU.
