### ISSUE TITLE
New Device: GL-AR750S-EXT "SLATE"

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#14]
Request to Add this new "Gigabit" model or review compatibility with existing code to support this device.  Featuring Gigabit Ethernet ports.
We have a couple of these devices on hand and available for testing as needed.

**Comment by dman776** [comment]
consider for Openwrt 21.02.x support

**Comment by stuieordie** [comment]
Has the GL-AR750S-EXT been added yet? I'm tempted to try the AR-750 firmware.

**Comment by ae6xe** [comment]
The ar750 creta is supported inow.  the ar750 slate is not yet available.  We have to upgrade to current openwrt to inherit this support.  I have early images for the slate I've been trying to move forward, but still some critical functionality not yet working.

**Comment by aanon4** [comment]
There is a nightly build for this device now, but it's untested as we dont have hardware. If anyone wants to give it a try and report back please do.

**Comment by k1ky** [comment]
Can you point us to the "correct" nightly for this unit to test?  There appear to be several that could be confusing.

**Comment by aanon4** [comment]
The unhelpful answer is that I don't know. I dont have one of these so I've no way to find out.

**Comment by k1ky** [comment]
See issues #729 and #730 
Closing this issue in favor of them.
