### ISSUE TITLE
Base setup UI error after reboot. FW: 3.24.4.0-ath79 glinet_gl-ar300m16

### ISSUE THREAD

**Issue by bi7jta** [aredn/aredn#1406]
Hello, 
I got an error in this version firmware, 

`aredn-3.24.4.0-ath79-generic-glinet_gl-ar300m16-squashfs-sysupgrade.bin`

### Screenshots
![image](https://github.com/user-attachments/assets/2f950b26-abe7-4665-9dc8-e58df82977e1)
 
See is a web browser (JS) issue

**Comment by aanon4** [comment]
Could you provide an image of the main status page? Also, can you describe the exact steps you've taken to get to this point?

**Comment by bi7jta** [comment]
> Could you provide an image of the main status page? Also, can you describe the exact steps you've taken to get to this point?

After reset value , it work again . I guess the wrong settings cause this issue.

![image](https://github.com/user-attachments/assets/bfdc1f07-4f86-4b58-90f9-edd860f8e427)
