### ISSUE TITLE
Change "Antenna Elevation" label to read "Antenna Declination"

### ISSUE THREAD

**Issue by wu2s** [aredn/aredn#1407]
**Is your feature request related to a problem? Please describe.**
The label Elevation is easily confused with the Height above Ground. Declination may more accurately convey a sense of antenna tilt from horizontal.
**Describe the solution you'd like**
Change the one word label.
**Describe alternatives you've considered**

**Additional context**

**Comment by K5RA** [comment]
If you check declination in Wiki or Google, you will find no definition bearing on the location of an antenna.  I am most familiar with declination meaning difference between magnetic north and true north, less so the hour-angle & declination coordinates describing locations of celestial bodies.  "Azimuth" and "elevation" are standard terms used to define the orientation of directional antennas, and those terms should probably continue to be used in AREDN.

**Comment by wu2s** [comment]
One of the beauties of the English language is its ambiguity. If elevation is commonly understood among the radio community as meaning the up- or down-tilt of an antenna, then it should remain as it is.

**Comment by wu2s** [comment]
No change needed
