### ISSUE TITLE
New UI - Search box does not appear on mesh page in older browser

### ISSUE THREAD

**Issue by m0xzl** [aredn/aredn#1415]
### Describe the bug
On the "mesh" page of the new UI the "Search the mesh..." box does not appear at the top of the page.
This is observed on a RPi/Buster/Chromium setup (fully updated).
The search box appears OK on other computers/browsers.
Firmware version: 20240827-83f94d7

### Expected behavior
A "Search the mesh..." box/control should be shown top centre.

### Screenshots
![image](https://github.com/user-attachments/assets/80f4b9c7-5b4e-4f7c-b8b2-86e9d4f5ae98)

### Additional context
This computer setup also had the Login problem previously but now seems OK.

**Comment by aanon4** [comment]
Search uses features not available on older browsers, so the search box is hidden if those features are not available.
