### ISSUE TITLE
Firmware Up to Date Badge Not Working?

### ISSUE THREAD

**Issue by K5RA** [aredn/aredn#1417]
System has 20240827 nightly.  20240828 nightly was available at about 0700 local (R - GMT-5) time.  At 0715, status badge in Firmware section showed Up to date.  At about 0730, in Firmware configuration window, Download Firmware was refreshed, and drop-down list of stable builds and new nightly build showed.  Front Page was refreshed several times with both icons in upper left.  Same situation at 0830.   20240828 nightly was fetched and installed at that time.  

System: hAP ac lite, 20240827 nightly; R-Pi 5B with latest bookworm, Chromium 126 (latest).  

Firmware status badge should update when Front Page is refreshed

**Comment by aanon4** [comment]
A node checks for an update every 24 hours. It is not intended to be a realtime indication.

**Comment by K5RA** [comment]
Thanks.
