### ISSUE TITLE
NLQ still > 100% 

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1419]
### Describe the bug
NLQ still shows > 100% on some remote nodes (with tunnel weight >1 )

- [ ] Does this issue still occur on the latest version? (**Required**)
Yes - both ends current
### Expected behavior
Should never be > 100%
### Screenshots

![image](https://github.com/user-attachments/assets/06185606-86c6-4f4f-87a0-3a7eb57c96ec)

[supportdata-W6BI-SHACK-NODE-2024-8-28-13-52.tar.gz](https://github.com/user-attachments/files/16788825/supportdata-W6BI-SHACK-NODE-2024-8-28-13-52.tar.gz)

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1420

**Comment by aanon4** [comment]
Fixed?

**Comment by Orv** [comment]
Works as expected.
