### ISSUE TITLE
New UI cannot handle unlisted DHCP option numbers

### ISSUE THREAD

**Issue by pmilazzo** [aredn/aredn#1425]
### Describe the bug
The New UI can neither create nor display DHCP options with a code (tag octet) that is not in the list of known option types. Only known options can be chosen in the &lt;select&gt; element, and previously configured options with an unknown code are displayed as an empty field.

The known options support many but not all DHCP use cases. There are many more defined options than the ones known to dnsmasq, and it is common for manufacturers to require private DHCP codes for certain devices.

- [X] Does this issue still occur on the latest version? (**Required**)

### Expected behavior
The direct way to support unknown options would be to use a &lt;datalist&gt; element in place of the &lt;select&gt; element. This element is now supported in most major browsers on most platforms, but not all.

The old UI used a special "[other option number]" choice in the &lt;select&gt; element:
![step1](https://github.com/user-attachments/assets/44491ee2-8cfd-423e-be90-47dd80b92bca)

...which, when selected, would swap out the &lt;select&gt; element for a numeric input field:
![step2](https://github.com/user-attachments/assets/59db5d30-f357-4ccf-9519-4efaa43ab516)

When the option was added to the table, the formerly unknown option code would be interpolated into the &lt;select&gt; element:
![step3](https://github.com/user-attachments/assets/94cb5dc6-0c26-422e-af86-294e2d011007)

Sadly, when this configuration is displayed in the new UI, the option code remains unknown:
![newUI](https://github.com/user-attachments/assets/aa50edab-742c-4761-bd72-ae4138f230ee)

**Comment by aanon4** [comment]
So I think the way to go here is to use a feature called 'datalist' which provides autocomplete to input fields (originally implemented in 2011 ... I discovered them today). This should allow someone to enter a number or select from a dropdown list of known options.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1430

**Comment by pmilazzo** [comment]
Great idea! The &lt;datalist&gt; approach seems to work well (I tried it in Chrome on Linux and Edge and Firefox on Windows).

One trick it helps to know: the input field will only display the list when empty. So, to switch to a different choice you first have to clear the input field and then re-open the list.

**Comment by aanon4** [comment]
On Safari (and it's probably a browser dependent thing) the list will re-open as soon as you start typing so long as there's a partial match.

**Comment by aanon4** [comment]
@pmilazzo close?

**Comment by pmilazzo** [comment]
Yes, close it. I'm happy.
