### ISSUE TITLE
Allow a node's config to be backed up and restored

### ISSUE THREAD

**Issue by aanon4** [aredn/aredn#1428]
Provide a mechanism to save a node's current configuration and allow this to be restored at a later date.

Notes: it's probably useful to allow a config to be backed up from one type of and restored to another, even with different hardware. It wont be possible to guarantee it will work though and it's too hard to try to work out what combinations are okay. The same goes for firmware versions - might be okay to restore with a different firmware, but might not. Need some warning around this.

**Comment by mathisono** [comment]
about time....

Thanks
