### ISSUE TITLE
Unable to set static WAN ip

### ISSUE THREAD

**Issue by kodiakastu** [aredn/aredn#1434]
### Describe the bug
I just provisioned a VM with the today's nightly (20240830). First time trying to setup a VM. When I set a static IP in the new UI, the IP turns to null ( see 1st screenshot).
 
Tried to setup in OLD UI, but when you change the wan type, you're missing half of the fields.

### Expected behavior
The static IP should be saved.

### Screenshots
![image](https://github.com/user-attachments/assets/f79e265e-89da-4e00-95ae-6c0074a8acac)
![image](https://github.com/user-attachments/assets/348d74cb-3f1d-4820-bfd9-c8408053f6d1)

### Additional context
I have 3 adapters set in proxmox and they're configured like this:
![image](https://github.com/user-attachments/assets/7e2aab28-2ff5-46d1-9aad-44d9e66ed3c4)

If I left WAN on DHCP it works as intended.

**Comment by aanon4** [comment]
Please attach a screenshot of the open network setup dialog. Also please add the support data. Thanks.

**Comment by kodiakastu** [comment]
Like this ?
![image](https://github.com/user-attachments/assets/52095d45-fc65-4bc8-907a-8360dff16bdb)
[supportdata-VA2LRM-LPLN-Q01-VM00-2024-8-30-19-54.tar.gz](https://github.com/user-attachments/files/16822822/supportdata-VA2LRM-LPLN-Q01-VM00-2024-8-30-19-54.tar.gz)

**Comment by aanon4** [comment]
Thanks. Did you enter values into those boxes?

**Comment by kodiakastu** [comment]
Yes. Before I click done:
![image](https://github.com/user-attachments/assets/bf3b51aa-4142-453d-844c-f195eca75e62)
Once I click done:
![image](https://github.com/user-attachments/assets/f3aa3046-69db-423c-80e2-eefe0f20b255)
Once I click commit:
![image](https://github.com/user-attachments/assets/9384edc0-7e74-4669-a10c-8af35e9097f8)

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1435

**Comment by aanon4** [comment]
Should be fixed tomorrow

**Comment by kodiakastu** [comment]
That was quick! When does the nightly builds ? I'll update as soon as I can to test.

**Comment by aanon4** [comment]
They're usually available by 13:00 UTC each day

**Comment by aanon4** [comment]
Let me know if today's build works for you.

**Comment by kodiakastu** [comment]
Works as intended on my current vm. Thanks again!
