### ISSUE TITLE
Portable Theme Capability Vanished

### ISSUE THREAD

**Issue by K5RA** [aredn/aredn#1448]
After experience an hour ago with Portable Theme not working, I looked at Basics screen.  Portable Theme switch not in window.  Confirmed I was in Home node.  Tried it three times.  Rebooted node.  Portable Themes switch is back.  

More data.  Start in Home node, new UI.  Open Basics window.  Portable Theme switch is present and green.  Cancel Basics window.  Hop to a Neighborhood Node.  It is showing old UI, and running 20240701 nightly.  Hop back to Home node.  Open Basics window.  Portable Themes switch is not present.  Cancel Basics window.  Click AREDN logo in upper left.  Open Basics window.  Portable Theme switch is present.  

Desired behavior is that Basics window show Portable Themes switch after switching back to Home node.

**Comment by aanon4** [comment]
You must be on "localnode" or "localnode.local.mesh" to see this option.

**Comment by K5RA** [comment]
OK.  I see that the AREDN logo hop goes to localnode.local.mesh:8080 from nodes that have 3.24.6.0 or even some nightly builds.  Recent nightlys go to localnode.local.mesh/
