### ISSUE TITLE
Knightly Build 20240902-2ac72eb CSS formatting

### ISSUE THREAD

**Issue by smfichera** [aredn/aredn#1450]
### Describe the bug
I updated my hAP lite to Knightly Build 20240902-2ac72eb and the css formatting is not displaying correctly.  Looking at the html source I see references to localnode.local.mesh in the head.  This particular node is a dtd.  The node that resolves to localnode is not yet on the knighly build firmware because it is a production tunnel server that I only run final releases on so there is no place for the browser to pull the .css file.  I tried multiple themes with the same result.

- [X] Does this issue still occur on the latest version? (**Required**)

### Expected behavior
Formatting of the page has a problem

### Screenshots
![image](https://github.com/user-attachments/assets/ec1489bd-dab6-47bd-9ff8-81d94da75327)

### Additional context
Rebooted the node in addition to the reboot during and upgrade.  Also deleted browser cache.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1449

**Comment by aanon4** [comment]
Please update.
