### ISSUE TITLE
unable to open DHCP settings when DHCP is disabled

### ISSUE THREAD

**Issue by ko0ooo** [aredn/aredn#1467]
### Describe the bug
One of my nodes is configured as an access point for my cell phone.   The phone gets its IP from my primary node, so the DHCP on the AP is disabled.

There may come a time when I'll need to bypass my network and talk directly to that node.  Having it issue an IP would help.

After logging in to the AP using the new UI, I'm unable to access the LAN settings to activate the DHCP.  I can when reverting to the old UI.   If the AP is configured as DHCP, no problems accessing the LAN settings.

thanks...

Richard     ko0ooo

### Expected behavior
Be able to configure/modify the LAN settings when DHCP is disabled.

### Screenshots
![lan dhcp](https://github.com/user-attachments/assets/dac2b544-95a3-4986-9032-9d17ac3c13ea)

**Comment by aanon4** [comment]
You need to enable the LAN which is in the Network panel.

**Comment by aanon4** [comment]
http://docs.arednmesh.org/en/latest/arednGettingStarted/node_admin.html#network-settings

**Comment by ko0ooo** [comment]
that was it..    thanks...

Richard    ko0ooo
