### ISSUE TITLE
Supported Devices errata

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1477]
### What is your question
The Supported Devices Matrix lists the Litebeam M5 as untested but released.  It lists an ath79 target, but no image is listed.   Entry should be corrected - either image created, or listed as unsupported - or something...

**Comment by aanon4** [comment]
I dont see it listed as supported anymore in OpenWRT. I'll update SUPPORTED DEVICES to remove it.

**Comment by Orv** [comment]
The Supported Devices page appears unchanged ( https://www.arednmesh.org/content/supported-devices-0 )

**Comment by aanon4** [comment]
I updated github only. I dont have access to the website.

**Comment by Orv** [comment]
How does that page get updated?
