### ISSUE TITLE
New UI - mac-address text box to short

### ISSUE THREAD

**Issue by KQ6EO** [aredn/aredn#1479]
### Describe the bug
On the "LAN DHCP" page the text box for the mac-address is to short and cuts off the last one or two characters.
I am using the Firefox browser.

**Comment by aanon4** [comment]
Could you add a screenshot please.

**Comment by KQ6EO** [comment]
[KQ6EO-HAP-TSTC admin.pdf](https://github.com/user-attachments/files/16940116/KQ6EO-HAP-TSTC.admin.pdf)
