### ISSUE TITLE
mac-address text box to short

### ISSUE THREAD

**Issue by KQ6EO** [aredn/aredn#1480]
### Describe the bug
[KQ6EO-HAP-TSTC admin.pdf](https://github.com/user-attachments/files/16940153/KQ6EO-HAP-TSTC.admin.pdf)

Sorry I accidently closed the original bug report

The new GUI's mac-address text box on the "LAN DHCP" page is too short and cuts off the last character or two of the mac-address.
I am using the Firefox browser.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/issues/1479
You could have just reopened it - but not to worry.

**Comment by aanon4** [comment]
Anyway, I'm not sure what the PDF image is of, but it's like you have no CSS loaded for some reason.

**Comment by aanon4** [comment]
<img width="1090" alt="Screenshot 2024-09-09 at 11 13 55 PM" src="https://github.com/user-attachments/assets/afb749de-0cee-4a38-ba3e-ea25d2775625">
This is what mine looks like.

**Comment by aanon4** [comment]
Maybe you used the print feature to get that "screenshot"?  I'm going to need a real screenshot.

**Comment by K5RA** [comment]
You might want to review closed issues #1371, #1376, and #1389 which address this.

**Comment by KQ6EO** [comment]
![Screenshot 2024-09-10 120058](https://github.com/user-attachments/assets/2a7275fa-62e4-4eb4-ae88-1259203b8d15)

The problem is only happening on the "High-Contrast" theme.  As K5RA noted you can click in the text box of the "Address Reservations" section and move right to see the rest of the mac address.  This does not work in the "Active Leases" section.

**Comment by K5RA** [comment]
Double clicking on either IP adr or mac adr in Active Leases allows to you see either end of the value by using the right and left direction arrow keys.  Easiest way is to use Light Theme if you are going to be in the window a while.

**Comment by aanon4** [comment]
> The problem is only happening on the "High-Contrast" theme.
Ah - you should have said at the beginning. Yes, the High Contrast theme makes text bigger and in some cases it wont fit as well. It's a trade off as the dialog sizes are fixed. I will continue to tweak things a little to try to improve these compromises.
