### ISSUE TITLE
Firmware Update to Mikrotik hAP Lite reports "Error: Unknown Error"

### ISSUE THREAD

**Issue by km6aow** [aredn/aredn#1485]
### Describe the bug
When updating firmware, an unknown error is flagged, but the update proceeds.

- [ ] Does this issue still occur on the latest version? (**Required**) 
- [ ] I'm on the current nightly build.

### Expected behavior
We shouldn't see a red error banner for a successful update.

### Screenshots
![Screenshot 2024-09-09 at 10 11 28 AM](https://github.com/user-attachments/assets/a8e0a86a-4829-41a2-8ed6-8b49a35d58a1)

### Additional context
This hAP is downloading firmware from a mirror if that makes any difference.

**Comment by aanon4** [comment]
Please attached support data - thanks.

**Comment by aanon4** [comment]
I stuck your local repo into as the download source for a node here, and it worked just fine. So I'm going go assume something network related is going on.

**Comment by km6aow** [comment]
No worries. If it works elsewhere, I can live with the "warning" as the update does in fact succeed. Thanks!

**Comment by km6aow** [comment]
The computer from which I did that was WiFi connected and has multiple APs it knows about here. As soon as the hAP drops its WiFi signal, that machine automatically rejoins another AP in the house. It never does get to the "updating" screen.
