### ISSUE TITLE
Special Characters in description field sometimes not interpreting properly

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#1495]
### Describe the bug
Special Character "'" for feet in description isn't always interpreted properly in new UI. N-2024-0912 and maybe a few nightlies before this.

- [ ] Does this issue still occur on the latest version? (**Required**)
- [ ] Yes - N-20240912

### Expected behavior
Expect special characters to display properly.

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.
<img width="231" alt="image" src="https://github.com/user-attachments/assets/40f9ea00-a608-42c1-bcdf-5bbfdee3d40c">
[supportdata-KL7AA-SUMMIT-MANT19s-25MST310-2024-9-12-17-46 (1).tar.gz](https://github.com/user-attachments/files/16987453/supportdata-KL7AA-SUMMIT-MANT19s-25MST310-2024-9-12-17-46.1.tar.gz)

**Comment by k1ky** [comment]
I "believe" that I added this description information from the new UI GUI side after initial firmware install.  It shows the same graphical character on the Old UI side as well.

**Comment by aanon4** [comment]
Yeah. I dont escape much in the description text. Just enough so it doesnt break the config file. I need to look for a definitive list of characters I need to care about.

**Comment by k1ky** [comment]
I use ', (, ) and | mostly - nothing too fancy

**Comment by aanon4** [comment]
But < and > dont work either - so I need a proper list. I just need to look for it.

**Comment by aanon4** [comment]
> I use ', (, ), @, - and | mostly - nothing too fancy

Which of these doesnt work?

**Comment by k1ky** [comment]
So far only "'" foot mark is all that I have seen so far.

**Comment by k1ky** [comment]
Interesting that it shows okay in the description entry box but not on the display.
Entry:
<img width="244" alt="image" src="https://github.com/user-attachments/assets/7a0a6407-4051-45bd-b954-8127a70e1232">
Display:
<img width="243" alt="image" src="https://github.com/user-attachments/assets/bb7e7bb1-8fc5-4917-8ebd-31f4dec9715b">

**Comment by k1ky** [comment]
Seems to be some issue during firmware upgrade.  I am able to edit it and displays fine.

**Comment by k1ky** [comment]
Confirmed that translation is okay when going from Nightly 08 to 12, will investigate further if needed.

**Comment by aanon4** [comment]
I can do better though
https://github.com/aredn/aredn/pull/1497

**Comment by kodiakastu** [comment]
It's not just about some special caracters. This doesn't fix french diacritics and leave other things broken. 

If I save thru old UI I can get away with a lot of weird things, even emojis. As soon I change something in new UI it breaks everything. When it breaks, a lot of Â appears. 

I tried the opposite way: I save something in new ui, is fine, but when I reload the page it's broken again, but not in the dialog box and is broken in old ui. 

What changed between old and new UI that requires to change the way we store the node's description?

I used ``- ⚠➡🏠😊😂🤣 - !"/$?&*()_+#|\<>{};:`,.'^ - ±@£¢¤¬¦²³¼½¾¸¨ - à é ê è`` as a test string. Let me know if it's too much ;)

**Comment by aanon4** [comment]
So this is a different bug. The fixes before were to escape character which are problematic for HTML to show because they means something special (< and > for example). This is just a utf8 encoding issue. Supposedly HTML5 is utf8 by default so I shouldnt need to specify it .. but that seems not to be the case. So ...
https://github.com/aredn/aredn/pull/1504

**Comment by kodiakastu** [comment]
Was this early enough to be included in today's nightly?

**Comment by aanon4** [comment]
Looks like the automated build failed last night so running again this morning. Will be available in a couple of hours if you check by hand.

**Comment by kodiakastu** [comment]
#1504 Fixes new ui but breaks old ui

**Comment by aanon4** [comment]
No plans to fix the old UI.

**Comment by kodiakastu** [comment]
I also checked sysinfo.json: it displays correctly when I save in new UI.

I don't know if the description is used somewhere else.
