### ISSUE TITLE
Clicking 'whole AREDN mesh' button isnt selecting closest or quickest supernode

### ISSUE THREAD

**Issue by KD4WLE** [aredn/aredn#1500]
### Describe the bug
Clicking 'whole AREDN mesh' button isnt selecting closest or quickest supernode. Both the local node and the super node are on the same VM and show as 'Local Nodes' , however the localnode picks a Supernode that shows as 'Fair'(2.2), bypassing both my own supernode and another tagged as 'Good'(1.2)

For good mesure, I have also check this from a node outside of the VM with the same unexpected result.

- [x] Does this issue still occur on the latest version? (**Required**)
- [ Yes, Both Supernode and node are on latest nightly] 

### Expected behavior
Should select the closest and/or fastest node

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/4d4d737d-1cb5-4e8c-848d-b8ee7ee7d9f1">

**Comment by aanon4** [comment]
Please attach the support data for the node.

**Comment by KD4WLE** [comment]
From: Tim Wilkinson ***@***.***>
Date: Friday, September 13, 2024 at 4:48 PM
To: aredn/aredn ***@***.***>
Cc: Sean Haga (KD4WLE) ***@***.***>, Author ***@***.***>
Subject: Re: [aredn/aredn] Clicking 'whole AREDN mesh' button isnt selecting closest or quickest supernode (Issue #1500)

Please attach the support data for the node.

**Comment by aanon4** [comment]
And you cant attach it by email.

**Comment by KD4WLE** [comment]
Well then.. 

[supportdata-KD4WLE-Titusville-One-2024-9-13-20-49.tar.gz](https://github.com/user-attachments/files/16999190/supportdata-KD4WLE-Titusville-One-2024-9-13-20-49.tar.gz)

**Comment by aanon4** [comment]
You probably need to give me telnet access I'm afraid - nothing obvious looks wrong (clearly it is though).

**Comment by KD4WLE** [comment]
Enabled.

**Comment by aanon4** [comment]
You also need to send me the password (email address is in my github profile)

**Comment by aanon4** [comment]
Thanks
https://github.com/aredn/aredn/pull/1503

**Comment by KD4WLE** [comment]
Seems to be resolved. Thank you!
