### ISSUE TITLE
Errors during firmware updates

### ISSUE THREAD

**Issue by m0xzl** [aredn/aredn#1543]
### Describe the bug
Errors have been encountered during FW updates this morning.
This is a follow-on from issue #1521 
Similar problems encountered on two nodes:
* M0XZL-GL1: AR150 (from: 20240917-ef66a2a, to: 20240918-0a3d322). Error msg "ERROR: Firmware not compatible with this device."
* M0XZL-GL10: AR150 (from: 20240917-ef66a2a, to: 20240918-0a3d322). Error msg "ERROR: Unknown error"

### Expected behavior
FW update should complete without errors. If there is an error the message should be helpful in determining what action to take next.

### Screenshots
AR150 (M0XZL-GL1)
![image](https://github.com/user-attachments/assets/65367a2a-c83f-4b61-9bc0-841c8976d3a0)
![image](https://github.com/user-attachments/assets/82a55653-f464-4161-9623-34572687e5fa)

AR150 (M0XZL-GL10)
![image](https://github.com/user-attachments/assets/e245d3f5-a8fd-4538-9fb8-4b24fa559f1e)
![image](https://github.com/user-attachments/assets/54bf5edf-bc56-43e4-8d9c-24ddb737ef85)

### Additional context
* All controls on the modal performed as expected.
* Repeats of the update process were successful in both cases.

**Comment by m0xzl** [comment]
Sorry, I attempted to paste in the support data files but it doesn't seem to have worked. Trying again.
[supportdata-M0XZL-GL1-2024-9-19-7-35.tar.gz](https://github.com/user-attachments/files/17054765/supportdata-M0XZL-GL1-2024-9-19-7-35.tar.gz)

[supportdata-M0XZL-GL10-2024-9-19-6-37.tar.gz](https://github.com/user-attachments/files/17054766/supportdata-M0XZL-GL10-2024-9-19-6-37.tar.gz)

**Comment by aanon4** [comment]
Timing wise, I think you need to have 20240918-0a3d322 installed to get the latest changes to the Upgrade Firmware fixes (they were committed on the 17th, so in the 18th's build). So the *next* updates would be the most interesting ones.

**Comment by m0xzl** [comment]
Understood

**Comment by aanon4** [comment]
Closing as there has been nothing added in two weeks.
