### ISSUE TITLE
Tools menu doesn't close after Support Data extract

### ISSUE THREAD

**Issue by m0xzl** [aredn/aredn#1544]
### Describe the bug
Once a Support Data file has been downloaded via the 'Tools' menu, the pop-up menu window does not close.

### Expected behavior
Once the download is complete the pop-up menu should close.

### Screenshots
![image](https://github.com/user-attachments/assets/ef0702ec-be35-4b3f-ac5e-d055b4633797)

### Additional context
* When you return from using other facilities on the 'Tools' menu the pop-up menu is closed.

**Comment by aanon4** [comment]
Oddly tricky to do as I dont want to close the menu until the download is done, and the download isnt easy for the front end to detect.

**Comment by m0xzl** [comment]
Understood. Not really a problem, just an anomaly I spotted.

**Comment by aanon4** [comment]
Spoke too soon ...
https://github.com/aredn/aredn/pull/1546
