### ISSUE TITLE
Max Distance doesn't match Old UI vs. New UI

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#1549]
### Describe the bug
Maximum distance is different in new UI as compared to Old UI in some cases. (LQM not enabled)
Update: LQM=ON, the numbers seem to match except no 2 digit decimal.

- [ ] Does this issue still occur on the latest version? (**Required**)
- [ ] Yes - N-20240919

### Expected behavior
Expect the Max Distance and any other values to match between UI's.

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.
<img width="270" alt="image" src="https://github.com/user-attachments/assets/ee3c33f8-84c7-44d0-a5b6-2c73419679b1">
New UI shows 50 miles
<img width="197" alt="image" src="https://github.com/user-attachments/assets/cc329183-8a36-40d3-9aa0-fad9b54a7334">
Old UI shows 1.24 miles.  Would also be nice for the new UI to show the decimal value to 2 places to match old UI

**Comment by aanon4** [comment]
You pesky people who turn LQM off.
https://github.com/aredn/aredn/pull/1550

**Comment by aanon4** [comment]
Can you verify this has been fixed? Thanks.

**Comment by k1ky** [comment]
Looking much better - I am able to make changes in either the new and old UI and the numbers somewhat track with LQM enabled and Disabled.
