### ISSUE TITLE
Unable to remove xlink, unresponsive config window.

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn#1566]
After attempting to remove 1 of 2 xlink from this node, the node returned to the main page, but XLinks still indicates 2 of 2 XLinks for  status. 

When returning to the XLinks config page, it blank.
 
![Screenshot_2024-09-22_21-40-08](https://github.com/user-attachments/assets/d1378f66-53e5-4ee1-9870-d5d6e76bc205)

[supportdata-W6CX-NORTH-HUB2-2024-9-22-21-42.tar.gz](https://github.com/user-attachments/files/17092806/supportdata-W6CX-NORTH-HUB2-2024-9-22-21-42.tar.gz)

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1561
Will be fixed tomorrow, but will require hand-editing a file on your node.
