### ISSUE TITLE
Tunnel Server Deletion

### ISSUE THREAD

**Issue by Linus-007** [aredn/aredn#1570]
There seems to be no way from the GUI to delete a tunnel server entry. Is this expected or designed this way?
Firmware: 3.24.6.0

**Comment by aanon4** [comment]
There are two UIs and four kinds of tunnel. Can you provide more information?

**Comment by aanon4** [comment]
Ah - see you're referring to the old UI (given the version number). No plans to change anything in the old UI at this point. Tunnels work as designed there, with their inherit limitations.
