### ISSUE TITLE
New MikroTik RouterBOARD 952Ui-5ac2nD 5gh radio not on untill switching to 2.4

### ISSUE THREAD

**Issue by KD4WLE** [aredn/aredn#1585]
### Describe the bug
New flash - 5Ghz radio isnt 'active' until switching radios to 2.4 and back. no frequency displayed, cant hear other radios next to it. 

- [Yes ] Does this issue still occur on the latest version? (**Required**)

### Expected behavior
Radio should be active

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.
<img width="464" alt="image" src="https://github.com/user-attachments/assets/d80bc075-c869-492a-b296-7cc55c51ec08">

### Additional context
[supportdata-N4TDX-Edgewater-GW-2024-9-30-1-24.tar.gz](https://github.com/user-attachments/files/17182676/supportdata-N4TDX-Edgewater-GW-2024-9-30-1-24.tar.gz)

**Comment by aanon4** [comment]
The odd thing here is that the radio should come up on 2.4 not 5 (it picks wlan0 by default, which is the 2.4 radio). Just want to check that the support data is from the device *before* you fixed the issue by switching radios on and off?

**Comment by aanon4** [comment]
As there seem to be a bunch of wireguard tunnels in the support data, I'm guessing the support data is not from when the failure was observed :-(

**Comment by aanon4** [comment]
The data you sent over is very odd. There's no wifi device defined at all for some reason, and there are multiple entries on the setup file which really cant be there given the code which generates them. And channel 131 isnt the default for any configuration.

If you could reflash one of your extra devices, send over the support data and a screenshot of the main page before configuring anything, that might help.

**Comment by aanon4** [comment]
Just want to confirm that you were using nightly as both the initial ramdisk boot image and the initial install image, and not going into the old UI at any point?

**Comment by KD4WLE** [comment]
I may have used an older ramdisk in the initial load with a newer nightly sysupgrade bin.

Yes, looking at the timestamp on the rb.elf file, indeed reads 1/12/24 and aredn-20240927-179ce13-ath79-mikrotik is in my download directory for the sysupgrade. I’ll update the rb.elf and reflash, see if the problem persists tonight.

From: Tim Wilkinson ***@***.***>
Date: Sunday, September 29, 2024 at 11:59 PM
To: aredn/aredn ***@***.***>
Cc: Sean Haga (KD4WLE) ***@***.***>, Author ***@***.***>
Subject: Re: [aredn/aredn] New MikroTik RouterBOARD 952Ui-5ac2nD 5gh radio not on untill switching to 2.4 (Issue #1585)

Just want to confirm that you were using nightly as both the initial ramdisk boot image and the initial install image, and not going into the old UI at any point?

**Comment by KD4WLE** [comment]
Also:

https://downloads.arednmesh.org/snapshots/targets/ath79/mikrotik/aredn-20240928-9d091e0-ath79-mikrotik-mikrotik_routerboard-952ui-5ac2nd-initramfs-kernel.bin

File not found.

From: Sean Haga (KD4WLE) ***@***.***>
Date: Monday, September 30, 2024 at 5:55 AM
To: aredn/aredn ***@***.***>, aredn/aredn ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [aredn/aredn] New MikroTik RouterBOARD 952Ui-5ac2nD 5gh radio not on untill switching to 2.4 (Issue #1585)
I may have used an older ramdisk in the initial load with a newer nightly sysupgrade bin.

Yes, looking at the timestamp on the rb.elf file, indeed reads 1/12/24 and aredn-20240927-179ce13-ath79-mikrotik is in my download directory for the sysupgrade. I’ll update the rb.elf and reflash, see if the problem persists tonight.

From: Tim Wilkinson ***@***.***>
Date: Sunday, September 29, 2024 at 11:59 PM
To: aredn/aredn ***@***.***>
Cc: Sean Haga (KD4WLE) ***@***.***>, Author ***@***.***>
Subject: Re: [aredn/aredn] New MikroTik RouterBOARD 952Ui-5ac2nD 5gh radio not on untill switching to 2.4 (Issue #1585)

Just want to confirm that you were using nightly as both the initial ramdisk boot image and the initial install image, and not going into the old UI at any point?

**Comment by aanon4** [comment]
File not found - yes, there's a new nightly now with a different version number. We dont keep the old ones.

**Comment by KD4WLE** [comment]
Re-flashed with today's nightly

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/1f781d5e-53ad-4e33-8bb8-2567d779426d">

[supportdata-KD4WLE-Setup1-2024-3-22-22-17.tar.gz](https://github.com/user-attachments/files/17195405/supportdata-KD4WLE-Setup1-2024-3-22-22-17.tar.gz)

**Comment by aanon4** [comment]
Thanks for this.
This should fix the issue https://github.com/aredn/aredn/pull/1588
However .. it's a workaround as I still dont undetstand what's really at the root of this. However, I plan to do some other work on the initial setup for the next release, so I'll revisit.
