### ISSUE TITLE
admin ui web interface

### ISSUE THREAD

**Issue by dod1450** [aredn/aredn#1601]
### Describe the bug

- [x] Does this issue still occur on the latest version? (**Required**)

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.

**Comment by dod1450** [comment]
I am no longer seeing a web GUI html page When I press the new UI I don't think the developer are seeing this?

**Comment by aanon4** [comment]
Sorry - you need to provide a much more detailed description about what's going on.
