### ISSUE TITLE
PowerBeam-M2-400 Has Different Radio Model Name

### ISSUE THREAD

**Issue by K5RA** [aredn/aredn#1620]
I upgraded a two-year old UBNT PowerBeam-M2-400 from 3.22 to 3.24.10.0.  The Firmware window shows  (ath79/generic) UBNT (powerbeam-m2-xw) but the Radio block on Admin Page says Radio model is Ubiquity NanoBeam M2 International.  

I expect Radio model to be same as vendor M/N: PowerBeam-M2-400.

Screenshot and Support Data provided.

PowerBeam is fed from POE brick.  Other side of PoE is RP5B with up to date bookworm and Chromium browser.  Support Data was taken before NTP was fixed.

[20241011_22h43m51s_grim](https://github.com/user-attachments/assets/e2ea51c7-09d2-4c2b-b69c-71211e263f84)
[supportdata-K5RA-PBE400-1-2024-3-23-0-29.tar.gz](https://github.com/user-attachments/files/17348689/supportdata-K5RA-PBE400-1-2024-3-23-0-29.tar.gz)

**Comment by RAndrewThomas** [comment]
This might be an upstream (OpenWRT) issue.

Your 'data.txt' and '/tmp/sysinfo/boardid' both say boardid is 0xe2c2

aredn/openwrt/staging_dir/target-mips_24kc_musl/root-ath79/usr/share/libiwinfo/devices.txt says 'NanoBeam M2 Intl" for "Device Name" when "subsystem device id" == 0xe2c2.  There is no entry in that file with "Device Name" == "PowerBeam M2*"

I don't have a PowerBeam M2 (PBE-M2-400) or I'd double check its board_id.  Interestingly that file TXT doesn't have an entry for my NanoBeam M5 (NBE-M5-400) so I will check it's board_id

**Comment by K5RA** [comment]
Thank you for this information.  I have the device upgraded to 3.24.10.0, and it appears to work.  There are three other AREDN devices running on my bench, and it sees all of them.  

The box that holds the radio/antenna feed part is labeled PBE-M2-400-US.  The text below the SKU code is (K) 74ACB9FE8B4F.  The test date on the UBNT tag  is 08/23/20.  I bought the node from a reseller about 02/25/2022.  The nameplate on the back of the feed assemble has the following markings: 
M/N:  PBE-400-M2
FCC ID: SWX-NBM2HP
IC: 6454A-NBM2HP
Could UBNT have used a NanoBeam board in the PowerBeam product, and listed the old FCC and IC certifications?

**Comment by RAndrewThomas** [comment]
Oh, I bet you're absolutely spot-on there.  I just looked on both a PowerBeam M5 (PBE-M5-400) and a NanoBeam M5 (NBE-M5-400) and they BOTH have the FCC ID: SWX-NBM5HP.  Now I've got two board_id's to check ;)

**Comment by K5RA** [comment]
I guess it is what it is.  I know what radio I have, and will put that in the description.  No need to leave this issue hanging out.
