### ISSUE TITLE
Wifi Signal does not display both LOCAL and REMOTE bars

### ISSUE THREAD

**Issue by KenHorse** [aredn/aredn#1627]
When using WiFi Signal, there is no display for the REMOTE side. Also notice LOCAL display moves up and down (see screenshots)
![Screenshot 2024-10-13 at 13-10-23 AH6LE-TEST admin](https://github.com/user-attachments/assets/75dd5b92-4427-492a-8ed1-3559931f36bc)
![Screenshot 2024-10-13 at 13-25-11 AH6LE-PARRETT-5AC2-PTP admin](https://github.com/user-attachments/assets/675dce39-a371-4ae6-9e1e-a196338f06fa)

1013 Nightly build. Seeing issue on Powerbeams M5 XW, 5AC 400 and 5AC Gen2. Browser is latest FireFox

**Comment by aanon4** [comment]
Please provide support data for both end of the link you are testing. Grab this data immediately after running the test. Thanks.

**Comment by KenHorse** [comment]
[supportdata-5AC Gen2-2024-10-13-20-43.tar.gz](https://github.com/user-attachments/files/17357028/supportdata-5AC.Gen2-2024-10-13-20-43.tar.gz)
[supportdata-M5 XW-2024-10-13-13-42.tar.gz](https://github.com/user-attachments/files/17357031/supportdata-M5.XW-2024-10-13-13-42.tar.gz)

**Comment by aanon4** [comment]
Thanks. Which way were you running the test just before you got the support data?

**Comment by aanon4** [comment]
Also, could you redo the screenshots but without cropping out the rest of the UI? Thanks.

**Comment by KenHorse** [comment]
I re-ran the tests from both ends again and grabbed supportdata again. Also screenshots from each end
![Screenshot 2024-10-13 at 14-21-08 5AC Gen2 admin](https://github.com/user-attachments/assets/915ba8be-aaf8-457d-80ea-4c6babff3422)
![Screenshot 2024-10-13 at 14-20-18 M5 XW admin](https://github.com/user-attachments/assets/3ffae9c5-c7a0-4d25-aaa0-ebb3a2fed5f0)
[supportdata-5AC-GEN2-2024-10-13-21-24.tar.gz](https://github.com/user-attachments/files/17357114/supportdata-5AC-GEN2-2024-10-13-21-24.tar.gz)
[supportdata-M5-XW-2024-10-13-14-23.tar.gz](https://github.com/user-attachments/files/17357115/supportdata-M5-XW-2024-10-13-14-23.tar.gz)

**Comment by aanon4** [comment]
You need to select a node - there is no remote average. Did you try that?

**Comment by KenHorse** [comment]
Dang, didn't even occur to me...duh.... Yea, that works fine. Close this!

**Comment by aanon4** [comment]
I will update the Help.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1628
