### ISSUE TITLE
Enhancement: Tool to View GPS Data

### ISSUE THREAD

**Issue by K5RA** [aredn/aredn#1641]
Propose an enhancement to AREDN for a tool to be used with data from a GPS dongle to provide a display like that of the   XGPS app  in a Raspberry Pi.  Tool would provide list of satellites available and indication if used or not, graphic showing GPS constellation, time and location values and error estimates, etc.  See screen shot.  
![20241021_08h03m18s_grim_CR](https://github.com/user-attachments/assets/5fcd69c3-f716-4fa0-a856-f011b67633f3)

**Comment by K5RA** [comment]
Tool would be used with nodes like hAP ac lite and hAP ac2 that have USB-A port to accept the GPS dongle.

**Comment by aanon4** [comment]
I'm inclined to leave this to someone to write an external package for rather than including it by default.

**Comment by aanon4** [comment]
Someone should write a package for this feature.
