### ISSUE TITLE
Ubiquiti PBE-5AC-500 Firmware check failed on flashing

### ISSUE THREAD

**Issue by combatlord** [aredn/aredn#1649]
### Describe the bug
Try to flash new Aredn Firmware via TFTP-Client results in "Firmware check Failed"

Tried with the following FW Versions:
aredn-3.24.4.0-ath79-generic-ubnt_powerbeam-5ac-500-squashfs-factory.bin
aredn-3.24.6.0-ath79-generic-ubnt_powerbeam-5ac-500-squashfs-factory.bin
aredn-3.24.10.0-ath79-generic-ubnt_powerbeam-5ac-500-squashfs-factory.bin

Nightly:
aredn-20241024-7d9ac7e-ath79-generic-ubnt_powerbeam-5ac-500-squashfs-factory.bin

I also downgrade the AirOs to XC.v8.7.0.42152.200203.1256.bin but the results are the same

### Expected behavior
Flash successfull Aredn Firmware without failure.

### Screenshots
![aredn_pbe-5AC-500-flash_failed](https://github.com/user-attachments/assets/57177d26-ff65-436c-bfdb-32e867b45e9b)
![select_firmware_pbe5ac-500](https://github.com/user-attachments/assets/2aa21e71-5496-4e4e-a8be-32e0c9541a91)

### Additional context
I see that other Powerbeams have the same failure, so it seems that is a generic bug.

**Comment by aanon4** [comment]
Please follow these instructions: https://docs.arednmesh.org/en/latest/arednGettingStarted/installing_firmware.html#ubiquiti-802-11ac-first-install-process

**Comment by K5RA** [comment]
Daunting.

**Comment by combatlord** [comment]
OK, thanks for the tip. I'll try it and give a feedback.

**Comment by combatlord** [comment]
It works like in @aanon4's link.
I didn't realize that this chapter was for the powerbeam.
So that pointed me in the wrong direction.

Thanks to aanon4.
It's not a bug, it's user error on my part.
Sri.
