### ISSUE TITLE
NB 20241029 update from 3.24.10.0 leaves node in first boot state

### ISSUE THREAD

**Issue by k6ccc** [aredn/aredn#1659]
It's back.

NB 20241028 fixed the problem I reported with NB 20241027 where it would leave the node in first boot state.  However the first node I updated to 20241029 had the same problem.  This is one of the two nodes that I could not access from home because it is at work.  This is a Mikrotik LHG 5HPnD-XL.  Came in this morning and sure enough it was in first boot state.  Loaded 20241029 and the problem remained.  Node was running with an IP of 192.168.1.1 and the main screen showed most field at default, however if you select a field (location and RF for example) it would show correct data.  OK, let's go back to 3.24.10.0  Everything was restored properly and the RF link connected.  Tried NB 20241029, and back to the 192.168.1.1 with default data.

Next step will be to remote into the computer at home where I can get NB 10241028 and try that.

Support data file attached.

[supportdata-K6CCC-RB-LHG-5HPnD-XL-2024-10-27-16-49.tar.gz](https://github.com/user-attachments/files/17557819/supportdata-K6CCC-RB-LHG-5HPnD-XL-2024-10-27-16-49.tar.gz)

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1660

Apparently I'm a slow leaner
