### ISSUE TITLE
Disable DHCP server on mesh LAN

### ISSUE THREAD

**Issue by r1de** [aredn/aredn#1661]
**Is your feature request related to a problem? Please describe.**
Cannot disable DHCP on LAN in new UI.
There should be a way to disable DHCP _server_ on mesh LAN.
If you have more than 1 AREDN node that shares the LAN segment you do not want more than 1 DHCP server on that LAN segment.

**Describe the solution you'd like**
An on/off toggle, checkbox, _something_

Old UI had this:
![DHCPServerCheckbox](https://github.com/user-attachments/assets/9d48353a-ec3b-4fe1-b90d-5a09f3fbb361)

Unless I am missing something, I could not find where to do that in the new UI _anywhere_.

Sorry to add to you workload @aanon4 :smile:

**Comment by aanon4** [comment]
https://docs.arednmesh.org/en/latest/arednGettingStarted/node_admin.html#network-settings

Set the LAN size to disabled.
