### ISSUE TITLE
New UI: Word Wrapping in Tunnels Section

### ISSUE THREAD

**Issue by AI7BQ** [aredn/aredn#1662]
### Describe the bug
UI Enhancement: Aesthetic/legibility issue. Dual-word labels "active clients," "allocated clients," "active servers," and "allocated servers" merge at certain browser widths/zoom levels (see exhibit A). To prevent this, force line breaks between words (see exhibit B).

- [x] Does this issue still occur on the latest version? (**Required**)... Yes.

### Expected behavior
Under all settings of browser width and zoom level, the dual word descriptors appear on two lines (left justified) as shown in exhibit B.

### Screenshots
Exhibit A:
![image](https://github.com/user-attachments/assets/4cadd719-f2a4-4cc3-9706-df63fb1ad628)

Exhibit B:
![image](https://github.com/user-attachments/assets/743c3ffb-5542-422f-97e5-9d00a58f48c6)

### Additional context
None

**Comment by aanon4** [comment]
Going to stay with the current layout.
