### ISSUE TITLE
Nightly 20241030 on lhgg-5-ac-xl does not display LAN DHCP lease.

### ISSUE THREAD

**Issue by nc8q** [aredn/aredn#1663]
### Describe the bug
Nightly 20241030 on lhgg-5-ac-xl issues but does not display LAN DHCP lease.

Yes, as of 20241031 09:49 UTC.

### Expected behavior
Expected the lease to be displayed

### Screenshots
http://nc8q.ddns.net:4880/20241030

### Additional context
None, yet.

**Comment by kodiakastu** [comment]
Hello, I'm having the same issue on a VM. 

It seems that the gui DHCP range is "offset" from the subnet. On my side, DHCP is working and i'm receiving addresses on the right subnet, but the gui is thinking the DHCP should be on an other one and nothing is showing on the webpage.

![image](https://github.com/user-attachments/assets/a86e2f0d-343d-4f7a-8de3-2a0f473f5e23)
![image](https://github.com/user-attachments/assets/80b5e81a-f9a2-4231-8d21-db38106a0e4e)
![image](https://github.com/user-attachments/assets/1523267e-cb9c-49c3-ada3-73df26ca2ad7)


[supportdata-VA2LRM-LPLN-Q01-VM00-2024-10-31-9-37.tar.gz](https://github.com/user-attachments/files/17588496/supportdata-VA2LRM-LPLN-Q01-VM00-2024-10-31-9-37.tar.gz)

**Comment by aanon4** [comment]
Always fun to find out the values we store were always wrong but the bug hidden by other things.
https://github.com/aredn/aredn/pull/1664

**Comment by kp4djt** [comment]
I see the same thing on a hAP ac lite I use on the road. Just updated it last night, I have 4 devices on the LAN 3 wired and one WiFi, but only two IP assignments shown.

**Comment by kodiakastu** [comment]
Great to see you're always that fast LOL! Do you know when this will be merged ?

**Comment by aanon4** [comment]
Will be merged this evening.

**Comment by kodiakastu** [comment]
Everything is back to normal, Thanks!
