### ISSUE TITLE
Main display fails to appear on GL AR750 after installing NB 20241107

### ISSUE THREAD

**Issue by wu2s** [aredn/aredn#1678]
### Describe the bug
After installing NB 20241107 on two GL AR750, the whole UI is not visible.
A screenshot would just show a blank page.

- [ ] Does this issue still occur on the latest version? (**Required**)

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.

**Comment by aanon4** [comment]
What version was this node previously running?

**Comment by wu2s** [comment]
Local network issue resolved

**Comment by wu2s** [comment]
The previous day’s build NB 20241106
