### ISSUE TITLE
Update Mikrotik hAP AC3 nightly build fails

### ISSUE THREAD

**Issue by wu2s** [aredn/aredn#1698]
### Describe the bug
Attempted several times to update a Mikrotik hAP AC3 several times from NB 20241115 to NB 20241116 using the normal update procedure (Download firmware, fetch and update). The device fetches and updates, and then displays the Updating screen/Reboot as normal. Upon returning to the main screen after a reboot, the firmware is not updated and remains at NB 2024115. This was tried several times.

Looking at the log on the device I see 3 messages:

- [ ] Does this issue still occur on the latest version? (**Required**)
Yes NB 20241115

### Expected behavior

user.info upgrade: The device is supported, but the config is incompatible to the new image (1.0->1.1). Please upgrade without keeping config (sys upgrade -n).

user.info upgrade: Config cannot be migrated from swconfig to DSA

daemon.err https[1259]: Image check failed

### Support data
Please add the support data for all nodes mentioned in this bug report (**Required**)

[supportdata-WU2S-H3-X-2024-11-17-17-23.tar.gz](https://github.com/user-attachments/files/17791698/supportdata-WU2S-H3-X-2024-11-17-17-23.tar.gz)

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.
Successful update as normal.
![WU2S-H3-X](https://github.com/user-attachments/assets/ba5de857-0b97-42ed-b2b3-82e7cbc857bb)

**Comment by aanon4** [comment]
There was a bug in some nightlies which causes this on some specific devices. To fix type the following once logged in:
```
uci set system.@system[0].compat_version="1.1"
uci commit system
```
You should then be able to upgrade. Let me know if this works.

**Comment by wu2s** [comment]
Yes, that did it. Thank you.
