### ISSUE TITLE
Minor UI tunnel display issue

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1707]
### Describe the bug
Inconsistent labeling in tunnel Connection details.

- [x] Does this issue still occur on the latest version? (**Required**)
Yes
### Expected behavior

When Connection details are displayed for a Wireguard client, it's still labeled as "Password".  To reduce confusion it should match the label in the tunnel config:  "Wireguard key"

![WG Tunnel info](https://github.com/user-attachments/assets/21e02c78-6aef-4fa5-ad3d-ee800828dad8)

**Comment by aanon4** [comment]
Please verify this fix - thanks

**Comment by Orv** [comment]
Verified!  Looks good.
