### ISSUE TITLE
40 MHz bandwidth, Mikrotik SXTsq-5ac. No 'n snr', no 'miles', poor 'mbps'

### ISSUE THREAD

**Issue by nc8q** [aredn/aredn#1715]

**Comment by aanon4** [comment]
I assume this involves two nodes, so please provide specific details of both. Also note that support data is required from all nodes referenced and this has not been included.

**Comment by nc8q** [comment]
Hi, Tim:
I was starting to post the bug report, but testing was done with nightly 20241121.
I will get 20241122 and redo the support data files. Standby. ;-)

**Comment by nc8q** [comment]
http://nc8q.ddns.net:4880/aredn/
Link information updated.
'n snr' and 'miles' values appeared overnight. 
'mbps' still poor.
Got support data on 'red', but unable to download support data on 'yel'. I am remote now.
Next updating to nightly 20241122.

**Comment by nc8q** [comment]
Pursuing 40 MHz bandwidth on a pair of Mikrotik SXTsq-5ac devices.
I am showing much lower 'mbps' than expected.
I am getting much higher 'mbps' on a 20 MHz bandwidth link at much lower 'snf'/'n snr'.
Current supportdata and screenshots at 
http://nc8q.ddns.net:4880/aredn
and
http://nc8q.ddns.net:4880/aredn/20241125

73, Chuck

**Comment by aanon4** [comment]
Please add the information here - not on a remote website - thanks.
Also, how does the 40 MHz link actually perform vs 20? Looking at reported SNR/NSNR/MBPS doest tell us anything really.

**Comment by aanon4** [comment]
I guess we also need to clarify what this bug is, what needs to be fixed, and what success looks like.
