### ISSUE TITLE
DHCP reservations for 44-net LAN don't work

### ISSUE THREAD

**Issue by iannucci** [aredn/aredn#1722]
### Describe the bug
I recently migrated the LAN of one of my nodes to 44-net.  Machines and VMs on this LAN acquired their DHCP addresses from the node.  I added these DHCP address / MAC pairs to the Address Reservations.

But when client VMs and machines renew their DHCP address, the address is not always maintained per the Address Reservation.  See the screenshots below.

- [X] Does this issue still occur on the latest version?

Yes -- 20241126-f0270c4f

### Expected behavior
Address Reservations should be maintained on 44-net LAN just as they were on 10-net LAN.

### Support data

[supportdata-W6EI-SouthCourt-hAP-2024-11-26-18-11.tar.gz](https://github.com/user-attachments/files/17938108/supportdata-W6EI-SouthCourt-hAP-2024-11-26-18-11.tar.gz)

#### Reservations
[Reservations.pdf](https://github.com/user-attachments/files/17938113/Reservations.pdf)
#### In use
[In Use.pdf](https://github.com/user-attachments/files/17938114/In.Use.pdf)

**Comment by aanon4** [comment]
As a complete aside to the actual bug, I note that the screenshot of the reservations has the checkbox wrapped rather than on the same line. I cannot in anyway make this happen on any browser on either Linux of Mac, although I've seen this before. Any idea why this happens for you?

**Comment by aanon4** [comment]
Back to the actual bug - could you upgrade to 20241127 and retry - this could be related to a general configuration bug which was fixed yesterday.

**Comment by iannucci** [comment]
Will do

**Comment by iannucci** [comment]
Behavior is not changed with 20241127-3faeefe5.

Bob

**Comment by aanon4** [comment]
Could you attached updated support data? Thanks.

**Comment by aanon4** [comment]
Thanks.
So every reservation created for the DHCP system seems to be off by 3 compared to what the UI thinks is going on.
Not sure yet if this is just for the 44net option or more generally.

**Comment by aanon4** [comment]
Question. When you switch this node over to using the 44net allocation, did you then enter all these reservations, or where they already there?

**Comment by iannucci** [comment]
I switched to a new piece of hardware entirely (hAP).  No reservations carried over.  I added the VMs and computers to the hAP's LAN, waited for them to acquire a DHCP address, and then in the UI I added them as reservations.  Within an hour, there were some mis-matches.  The screen shots included in this bug report represent changes overnight.

And when I upgraded to to the most recent nightly, I noticed there was a mismatch very shortly after the upgrade.  That is, I had the address in the reservation table, I upgraded, and the VM renewed its DHCP reservation and got a different address in a matter of minutes after the upgrade.

**Comment by iannucci** [comment]
Here is an interesting sequence of events.

My MacBook Pro had a DHCP address ending in 112.  I added a reservation for 112.

Some time later, with the reservation for 112 still showing in the table, the computer's actual address and the "currently in use" address changed to 109.

I removed the 112 reservation and created a 109 reservation.  I saved the changes.

On my Mac, I then attempted to renew the reservation for 109.  It **remained** for a couple of minutes but then changed to 106.  There already was a reservation for 106 for a completely different MAC address.

Without changing the reservation table (still at 109), I renewed the DHCP address again on my Mac.  No change initially (remained 106).  Tried renewing several more times, and the assigned address stayed at 106.  

I then changed the reservation from 109 back to 112 and renewed the Mac's DHCP address.  The address on the Mac changed to 109 after about a minute.

So it seems that on renewal, the reservation table is being consulted, but the issued address is three lower.

**Comment by aanon4** [comment]
Looks like there was an assumption the DHCP range would start at an offset of 2 from the network base address. The expected sequence was NETBASE, GATEWAY, FIRST DHCP ADDRESS, ... In your config you had set this different which is entirely permissible, but the code creating the reservations didn't account for this. This has always been possibly in NAT mode but I guess no one noticed the issue. Anyway, fixed here:
https://github.com/aredn/aredn/pull/1726
