### ISSUE TITLE
Node Status Local Devices have Link Icons

### ISSUE THREAD

**Issue by K5RA** [aredn/aredn#1737]
System: hAP-ac-lite with 2024-12-02 NB, RP5B with latest bookworm and Chromium.  See same effect seen with the hap-ac-lite and  Win 11 PC with Firefox 133.0.

When I upgraded from 3.24.10.0, my two Local Devices  show link icons  

![Screenshot (37)](https://github.com/user-attachments/assets/cdfc1c37-87bb-486a-9118-b79911d12f60)
![Screenshot (38)](https://github.com/user-attachments/assets/49f2593d-3c7d-4ea2-8beb-35fdc7328efd)

to right of device name on the Node Status page. One is a local RP5B, other is a local VoIP phone. On Mesh Status page, no icon is associated with either local device.

Expected behavior:   link icon is not displayed in Node Status display with Local Devices that are not links.

[supportdata-K5RA-HAP-FB-2024-12-2-21-8.tar.gz](https://github.com/user-attachments/files/17986982/supportdata-K5RA-HAP-FB-2024-12-2-21-8.tar.gz)

**Comment by aanon4** [comment]
What happened when you clicked on them?

**Comment by K5RA** [comment]
In Node Status screen: 
    Clicking on the rp5b1 device brings up Apach2 Debian Default Page.
    Clicking on VoIP-fb brings up Grandstream 1625 log-in page..

**Comment by aanon4** [comment]
So this is doing exactly what it is now designed to do. The local device section will now detect if the device has a http(s) page it can open, and will turn the device name into a link if so. These auto-generated links are *not* published services so will not be published on the mesh page. They are convenience links if you are using the node directly.

This was a feature request. Glad it works.
