### ISSUE TITLE
DHCP leases not displayed

### ISSUE THREAD

**Issue by KenArck** [aredn/aredn#1754]
### Describe the bug
Latest nightly (20241207-cbfbad9d) running x86 Proxmox. Working DHCP leases are not displayed, only reservations are

- [ ] Does this issue still occur on the latest version? (**Required**)
Nightly 20241207-cbfbad9d

### Expected behavior
Expect to see all active DHCP leases displayed

### Support data
Please add the support data for all nodes mentioned in this bug report (**Required**)

### Screenshots
Please include a screenshot of your system information (if possible) if the specific system environment is relevant to the bug.

[supportdata-AH6LE-ProxMoxNode-QTH-2024-12-7-18-53.tar.gz](https://github.com/user-attachments/files/18050565/supportdata-AH6LE-ProxMoxNode-QTH-2024-12-7-18-53.tar.gz)

**Comment by KenArck** [comment]
![Screenshot 2024-12-07 185446](https://github.com/user-attachments/assets/672db7ed-35bf-470b-82fd-438611549a7c)
![Screenshot 2024-12-07 185446](https://github.com/user-attachments/assets/596917a7-c6c8-4e67-a56c-81892012f5ea)

**Comment by aanon4** [comment]
How long did you wait? Leases will only repopulate as the devices renew them. I dont see this on my nodes.

**Comment by KenArck** [comment]
I waited 20 minutes or so. I came back to it later and they're displayed. Sorry for the false flag.
However, I do notice the AREDN logo no longer spins when refreshing the page (for example, clicking the !). Should I start a new issue or ignore it?

**Comment by aanon4** [comment]
It only spins if the update takes more than a certain period of time. I never see it spin on proxmox because the underlying machine is usually fast enough. This hasn't changed.

**Comment by KenArck** [comment]
OK. Yea, I can't believe how slow the hAP AC2 seems to have been in comparison to this one.
