### ISSUE TITLE
new ui feature request - Non context HELP should open new browser tab instead of replacing node webpage

### ISSUE THREAD

**Issue by KenArck** [aredn/aredn#1759]
Seems kinda not great that when you open HELP from the User Icon dropdown, that it replaces the UI webpage you're working on. 

Opening HELP in a new tab makes a lot more sense

Pretty simple actually.....

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1760

**Comment by KenArck** [comment]
Last night's nightly now opens a new tab when non contextual HELP is called
