### ISSUE TITLE
MikroTik hAP ac3 - LAN WiFI Encryption Not Working

### ISSUE THREAD

**Issue by JPurp** [aredn/aredn#1766]
### Describe the bug
MikroTik hAP ac3 LAN WiFI SSID not broadcast when WPA/WPA2 configured.

- [x] Does this issue still occur on the latest version? (**Required**)

### Support data
[supportdata-KI6CVM-IDEC-Mobile-2024-12-12-17-40.tar.gz](https://github.com/user-attachments/files/18115498/supportdata-KI6CVM-IDEC-Mobile-2024-12-12-17-40.tar.gz)

### Additional context
MikroTik hAP ac3 is running 12/12 nightly to address dtd networking issues and web UI bug (1761). When configuring LAN WiFi I see the following;

WPA2 - SSID not broadcast. Can't connect to network (also tried hidden).
WPA - SSID not broadcast. Can't connect to network.
None - Working

I have tested different unlicensed channels (1, 6, 11) as well as changing SSID and done soft/power off reboots. Result is consistent.

**Comment by aanon4** [comment]
Looks like this support data is for 'none'. Could you add one for 'wpa' or 'wpa2' ?

**Comment by aanon4** [comment]
Also please make sure the password is valid (I think at least 8 characters) as we dont check this in the UI at the moment. Finally, if you dont see the network then please do a reboot and check again in case there's a problem there.

**Comment by JPurp** [comment]
Resolved

The issue was minimum password length. I left the default AREDN password and tried other there were <8. Once a proper password it came right up.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1767

Thanks for confirming.
