### ISSUE TITLE
DTD SWCONFIG Options by GUI - Feature Request

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#19]
Enhancement request to be able to view port configuration(s) and  change the DTD VLAN configuration of ports on AirRouters,  HAP and compatible GLInet  and similar future network switch type devices through the GUI.  Retain changes through the upgrade procedure and make it easy to change the Network Port configuration(s) through the node graphical interface instead of manually editing the swconfig file to support more than one DTD connection.

**Comment by k1ky** [comment]
Although not directly related, how about migrating the swconfig file during upgrades? This would streamline our upgrades of MESH nodes that have customized DTD ports set up.

**Comment by ae6xe** [comment]
The settings won’t be compatible on all devices after openwrt upgrade.  But maybe from this upgrade forward is an option.

**Comment by cTurtle98** [comment]
just wanted to point out that this is similar to #466 and #588

**Comment by aanon4** [comment]
With some more modern devices offering configuration (not via swconfig mind) this wont be implemented.
