### ISSUE TITLE
Status.lua - node count differs

### ISSUE THREAD

**Issue by dman776** [aredn/aredn#192]
Nanostation M2
dump_perl2 build
The status and status.lua pages differ in the total and node counts.
status has: 342 and 85  (total/nodes)
status.lua has: 343 and 86  (total/nodes)

**Comment by aanon4** [comment]
So they do derive the information in slightly different ways - the lua code asks OLSRD for its routes and then filters them while the perl just looks at the routing table (and applies the same filters).
Is this consistently the case? Quickly looking at a couple of my own nodes and they reports the same numbers both ways. Anything worth noting about this M2 node?

**Comment by ae6xe** [comment]
timing difference?  The olsr maintained route tables will have delayed updates, than what olsrd plugins will return live.

**Comment by dman776** [comment]
this node is plugged into a hapACLite's DTD port.
i hit refresh on both pages simultaneously.    It is repeatable.   the .lua page counts are always +1

**Comment by aanon4** [comment]
Can you post a screen grab of the setup page so I can see the configuration? Not sure why it would be +1 off and my nodes not.

**Comment by dman776** [comment]
<img width="804" alt="Screen Shot 2021-12-16 at 3 28 02 PM" src="https://user-images.githubusercontent.com/7685648/146451635-0eae824d-1254-4eb4-9b84-e6dc64911be7.png">

**Comment by dman776** [comment]
[supportdata-K5DLQ-UNSM2-100-202107291506.tar.gz](https://github.com/aredn/aredn/files/7730511/supportdata-K5DLQ-UNSM2-100-202107291506.tar.gz)

**Comment by aanon4** [comment]
Accidentally counting the default route - fixed - https://github.com/aredn/aredn/pull/190/commits/c866d2e519a560b36a4a5ba769dd75f2c9ec2c48

**Comment by aanon4** [comment]
Can we close this now?
