### ISSUE TITLE
Need consistent hardware identification

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#195]
While Mikrotik, TP-Link and GL.iNet have a field for "machine" type, indicating the hardware type, Ubiquiti uses a hexadecimal board ID, which needs to be looked up to determine what hardware it is.

What's needed is a consistent field within some downloadable file that accurately identifies the hardware the AREDN software is running on.  This will enable accurate metrics to be generated.

**Comment by aanon4** [comment]
Is there some structure to this that would be ideal? For example - manufacturer,devicename,revision (not saying this it the ideal, but perhaps you get the idea)?

**Comment by Orv** [comment]
For purposes of metrics, manufacturer, and device ID (name) would be fine.  Revision is probably overkill

**Comment by Orv** [comment]
This has been resolved with a nightly build.
