### ISSUE TITLE
Improvements to SPM web page

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#199]
1. At the top of the Supported Product Matrix, it currently says
"Current As of AREDN™ 3.21.4.0 (updated on 07/12/2021)"
Recommended improvement:
"Last updated on <whatever the date support for a new product was added>"  If it's added via a nightly build, then it should be flagged as such (although I'm not sure how it's flagged with ** as listed at the bottom of the page)

2. Take the RED=STOP off the bottom since we don't typically post unsupported devices.

3. Do we still use the ORANGE=CAUTION"?   If not it should be deleted.

4. Same with the "GREY=N/A".

5.And maybe we could increase interest by adding the products Joe is working on and highlighting them in Yellow (Researching).

**Comment by dman776** [comment]
changes made
