### ISSUE TITLE
Tunnel server will not start and Adv Conf textbox remains blank

### ISSUE THREAD

**Issue by VA2XJM** [aredn/aredn#209]
Just updated an hAP ac lite to V3.22.1.0. The tunnel server was not accepting connections and telnet to port 5525 was not working. So SHHed into the node to get the following output:

```
root@VE2ATU-FN08LF-Gateway:~/vtun# /etc/init.d/vtund restart
uci: Entry not found
/etc/rc.common: /etc/init.d/vtund: line 10: arithmetic syntax error
```
So I went ON this:
```
root@VE2ATU-FN08LF-Gateway:~/vtun# cat /etc/init.d/vtund
#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=84
STOP=85

CLIENT_CONF=/tmp/vtun/vtund.conf

# Starting tun interface is tun50
TUNNUM=$((50 + `uci get aredn.@tunnel[0].maxclients`))
MAXTUNNUM=$(($TUNNUM + `uci get aredn.@tunnel[0].maxservers` - 1))
```

Since it is an update and I went to the "advanced Conf" to set the value. Surprise, when saving, it keeps the textbox blank. Blank textbox apply for : aredn.@tunnel[0].maxclients, aredn.@tunnel[0].maxservers, aredn.@meshstatus[0].lowmem and aredn.@meshstatus[0].lowroutes.

aredn.@downloads[0].pkgs_freifunk was blank but when set to default and saved, it worked as supposed.

EDIT:
Replacing `uci get aredn.@tunnel[0].maxclients` and `uci get aredn.@tunnel[0].maxservers` with hard value fixed part of it.
Replacing `MAXTUNNUM=$(($TUNNUM + `uci get aredn.@tunnel[0].maxclients` - 1))` with hard value in /etc/init.d/vtundsrv has been needed too.

**Comment by dman776** [comment]
this should be fixed in the latest nightly builds.   Please verify.
