### ISSUE TITLE
how to report a PHP vulnerability?

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn#230]
for dev team, I'm getting scanned by the campus bot again. Who should I DM this report too.

73

**Comment by dman776** [comment]
We don’t use PHP on our nodes at all

Thanks,
Darryl

**Comment by mathisono** [comment]
ya I'm looking closer now and it looks like its one of the dockers, for a speed that I run. On one of my nodes.

Please close this it not AREDN's problem! 
73
