### ISSUE TITLE
Reboot command fails from Setup, but not Administration

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#231]
Under build 906, the Reboot button under Setup yields "Bad Gateway", but works as expected under Administration

Note this was observed on two separate Mikrotik hAP AC Lite routers, but NOT on a Mikrotik RBLHG-2nD.

Support Data will be emailed to KN6PLV

**Comment by aanon4** [comment]
Please wait for the next build and re-test (some fixes only went in this morning).

**Comment by Orv** [comment]
Will do.

**Comment by aanon4** [comment]
Possibly a dup of https://github.com/aredn/aredn/issues/223 but currently can't and don't have a way to reproduce. More information greatly appreciated.

**Comment by ab7pa** [comment]
This issue can be closed.
