### ISSUE TITLE
Installing iperfspeed on Nightly 913 stops the internet working

### ISSUE THREAD

**Issue by aanon4** [aredn/aredn#233]
Upgrading to Nightly 913 and then installing the iperfspeed package stops the internet working. Originally reported by @k1ky in https://github.com/aredn/aredn/issues/223

**Comment by aanon4** [comment]
Notes:
node-setup is failing to regenerate /etc/dnsmasq.conf after iperfspeed is installed, meaning it no longer hands out a default route to clients but will continue to operate correctly as a node in the network (which doesn't depend on dnsmasq).

**Comment by k1ky** [comment]
Note: Confirmed that there are NO issues noted with VTUN installed on N-913.

**Comment by aanon4** [comment]
For @k1ky: Incorrect handling of the dmz flag was removing the default route given out by DHCP. This didn't take effect until the node-setup script was first run after the update, which in this case happens as part of the iperfspeed package install process. So, once that install happened, the node no longer handed out a default route to your computer connecting via LAN. If you have a chance to check the next nightly build that would be much appreciated.
