### ISSUE TITLE
Remove cron

### ISSUE THREAD

**Issue by aanon4** [aredn/aredn#272]
The only thing cron does now is update aredn messages every 12 hours. Absorb this functionality into manager.lua and remove cron to save memory.

**Comment by ab7pa** [comment]
Cron does allow you to set the AREDN message refresh rate to any interval you desire.  If integrated into manager.lua there should still be a way for node owners to update their message refresh rate, maybe as an Advanced Configuration setting?

**Comment by aanon4** [comment]
There's no UI to change this setting currently? You just edit the file by hand?
