### ISSUE TITLE
Services not being deleted.  Still advertised on the mesh.

### ISSUE THREAD

**Issue by mre33** [aredn/aredn#29]
Running 3.18.9.0 on a NSM2 XM
--------------------------------------------
I set up a service and didn't like the name of it so I renamed it and saved the changes a few times.  On my local mesh status page everything looked fine and it showed the service with the last name I used.  I then went to a neighbor's mesh status page and discovered that every name I used was listed under my advertised services.  I then completely deleted all services and saved the changes but when I refreshed and examined the neighbor's (tun) mesh status page they were still displayed.  Apparently what was showing up correctly on my local mesh status page was fine but what was being sent out over the mesh was not being deleted internally.  After several attempts to reset the services page and clear the internal memory by rebooting the node I finally gave up, pressed and held the reset button to bring the node back to ground zero.  I rebuilt it all from the ground up, this time carefully entering my services.  Now my local mesh status and my neighbor's mesh status agree and only list my active services.

Now I am new to AREDN so I very well could be overlooking something but this appears to be a bug.  It appears that when you delete a service it is not being deleted from the internal memory that is sent out over the mesh.  The local node will look fine but remote nodes will still see the deleted services.
--------------------
I posted this on the arednmesh.org forum and was advised to re-post it here.  This bug should be easy to verify with two connected nodes.  Rename or delete services from one node and see if they get deleted from the mesh status screen of the neighbor node.

**Comment by aanon4** [comment]
Killing this one finally - https://github.com/aredn/aredn_packages/pull/11
