### ISSUE TITLE
Feature Request: GPS interface to MESH Location field

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#30]
Feature Request to explore methods to automatically populate the Map Coordinates Fields in MESH nodes from GPS, Cellphones, etc. We have a member who has written code to publish AREDN nodes on APRS.fi . We now have mobile MESH units with cameras online and it would be an advantage to be able to track the position of these nodes automatically. The only piece missing at this point is the GPS interface.

**Comment by n2mh** [comment]
Is there a gpsd opkg package? That might be the basis of a solution.

**Comment by slomobileAdmin** [comment]
> 
[
](https://openwrt.org/docs/guide-user/advanced/networked.gps?s%5B%5D=gps)

**Comment by aanon4** [comment]
Done
