### ISSUE TITLE
TUNNEL Connection Does not "Re-acquire" after reboot

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#31]
Tunnel connection does not automatically "reconnect" after reboot of Client unit Nightly 713.  Tunnel server still has a "blue cloud" even though the links are not shown and there is no blue cloud on the rebooted tunnel client side.  Must either reboot the tunnel server or disable/re-enable server port for that node to reconnect. 

There should be some sort of "activity" checking and automatic restart procedure for non-functioning tunnel connections on the server end.

This particular case is a UBNT AirRouter Client Nightly 713 and Tunnel Server Microtik hAP AC Lite Nightly 705.  This has been a problem for quite some time and is not a "new" issue.

**Comment by dman776** [comment]
no longer needed. PR#302 fixed this in nightly builds 1049+
