### ISSUE TITLE
1064 Tunnel Password Requirements

### ISSUE THREAD

**Issue by W9IKU** [aredn/aredn#311]
1063 does not allow symbols for passwords in tunnels.

**Comment by aanon4** [comment]
Specifically which symbols are no longer allowed?

**Comment by W9IKU** [comment]
It was the @ symbol in a working tunnel. It would not accept the config.

On 3/20/22, Tim Wilkinson ***@***.***> wrote:
> Specifically which symbols are no longer allowed?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/aredn/aredn/issues/311#issuecomment-1073356123
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
--
Greg Hovland
***@***.***
920-544-3614

**Comment by aanon4** [comment]
Fix here https://github.com/aredn/aredn/pull/312
