### ISSUE TITLE
Feature Request- Add Node to Node push message feature within native  AREDN FW

### ISSUE THREAD

**Issue by ZL2TB** [aredn/aredn#34]
Propose a simple push (i.e. when sent the  msg pops up on selected node if PC logged into that node or directly connected to it monitoring MESH ) message button is added native to MESH FW to send short msgs to a selected node over the MESH. A basic engineering communications channel. As simple as possible to save code space. Could provide last resort comms via the MESH if no node with "meshchat" is available too.

**Comment by dman776** [comment]
AREDN Alerts feature for AREDN and local controlled messages added.
