### ISSUE TITLE
Tunnel sans Crypto

### ISSUE THREAD

**Issue by ke4ahr** [aredn/aredn#344]
I formally request an option for non-encrypted tunnels. Using manual configuration of OpenVPN, is possible to provide the encryption of "none" to connect two endpoints, e.g.: "cipher none". The reasons for doing that are to leverage VPN capabilities without the overhead or to comply with anti-encryption policies such as those from the USA FCC.

It has become clear to me that there are options for interconnecting meshes over other Part 97 networks. To that end, it may be time to support GRE or preferably, another VPN that supports TCP or UDP connections while allowing no cipher, but still supporting hashing functions (as hashes are an authenticity system, not a cryptographic function).

GRE will work inside of a private mesh, provided port-forwarding isn't necessary. It's better to have both options however.

Another way to solve this problem is by simply disabling encryption on the port 5255 daemon already in use.

**Comment by dman776** [comment]
current tunnels do not use encryption.
