### ISSUE TITLE
Move aam from Adv Config to Alerts display

### ISSUE THREAD

**Issue by ab7pa** [aredn/aredn#354]
There are two **aam** settings on Advanced Configuration that might be better positioned on the Alerts display itself. They could be eliminated from Adv Config and put on the display to which they apply.
![aam_refresh](https://user-images.githubusercontent.com/69524416/166713322-72097d8f-da52-47e5-bef7-8a9647750585.png)
![aam_purge](https://user-images.githubusercontent.com/69524416/166713352-9593bf82-48d7-46b6-8a83-c3f4bdd5197d.png)

Suggest providing buttons that would allow users to _Update_ or _Remove_ alerts from the Alerts display. Below is a mockup of a possible solution.
![alert-buttons](https://user-images.githubusercontent.com/69524416/166713627-42b56bf5-5102-46b9-a066-d9906cfb9543.png)

**Comment by aanon4** [comment]
I assume these buttons aren't there if there are no messages? And while there's no need for Remove then, how about Update?

**Comment by ab7pa** [comment]
From what I can see, the entire alert banner (with any included buttons) will not be displayed unless there are messages.  On lines 85-90 of /usr/lib/lua/aredn/html.lua the alert_banner() function ensures that the message files exist and have size > 0.  A _Remove_ button would temporarily clear the alert banner -- of course it doesn't actually remove messages from the source [alert.localpath], so after alert.pollrate then any messages on the source server would reappear.  An _Update_ button would issue an on demand poll to fetch any new or changed messages that have been updated between the alert.pollrate polls.

**Comment by ab7pa** [comment]
Sounds like this feature is not widely used enough to merit time spent improving it.  I was mainly trying to think of ways to keep the Adv Config page from becoming a hodge-podge of random settings, by putting functions into the UI where similar items are located.  Will close this issue for now.  THX
