### ISSUE TITLE
Missing .local.mesh in Neighbor Status page links

### ISSUE THREAD

**Issue by aanon4** [aredn/aredn#362]
I like the new Neighbor Status page - but there is one problem.
The Neighbor node names are a link, but the link does not include ".local.mesh" resulting in not being found.
Unlike the Mesh Status page, where anything with a link includes ".local.mesh"
Otherwise, great work!

_Originally posted by @k6ccc in https://github.com/aredn/aredn/issues/360#issuecomment-1131877030_

**Comment by ae6xe** [comment]
Many devices have domain search paths and defaults.  My work laptop will not resolve a short-name, e.g. "ae6xe-node" and will always add only my approved work domains to attempt to resolve.   It's a security thing.   Only way to ensure these links work across all devices, is to ensure a FQDN (fully qualified domain name).
