### ISSUE TITLE
Feature Request: 5GHz MESH on Microtik hAP Lite

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#37]
Formalizing the request for 5GHz MESH operation on the Microtik hAP Lite (all models ACL, 2 and 3) with the ability to re-task the 2.4GHz radio as Wi-Fi AP operation.  As an additional feature explore the possibility of operating both 2.4GHz and 5 GHz Radios in MESH mode creating a "bridge" to couple devices together on the same network.

**Comment by cTurtle98** [comment]
was the issue with this that aredn only operates in 802.11n but part 97
the 5ghz radio is an 802.11ac and there isnt drivers for that for part 97 operations right now

am I correct?

**Comment by dman776** [comment]
Correct

**Comment by cTurtle98** [comment]
with the new drivers in the latest nightly that adds support for ac devices... is this being re-visited?

**Comment by ab7pa** [comment]
This should now be possible on quite a few of the supported radio models: Mikrotik hAP ac lite / ac2 / ac3 as well as the GL.iNet AR750 / 750S.

**Comment by k1ky** [comment]
Issue #726 should take place of this as there are now more options and models involved.
