### ISSUE TITLE
Incorrect Channel Selection Wi-Fi AP Mode on 5GHz devices N-1348

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#385]
Wi-Fi AP Model Channel Selection shows Channels 1-11 (2GHz) instead of 5.0 GHz Channels on various 5GHz Single-Band Models.  Verified this issue exists on UBNT Nanostation M5, M5XW, Rocket M5, PowerBeam M5-400-ISO and Nanobridge M5.  I suspect this is uncharted territory and may exist on prior Firmware versions.  I have attached a screen shot and various Support files for several models
[supportdata-K1KY-VARIOUS-2022-202206071729.zip](https://github.com/aredn/aredn/files/8858222/supportdata-K1KY-VARIOUS-2022-202206071729.zip)
.

**Comment by aanon4** [comment]
Let me take a look. Unfortunately I don't have a 5GHz only device on my desk.

**Comment by k1ky** [comment]
Same issue verified with Mikrotik LHG5 as well.

**Comment by aanon4** [comment]
Definitely a "dump_perl" lua bug. Will fix it now.

**Comment by aanon4** [comment]
This should fix if. I ran a test on a local NSM5 node to make sure the correct UI now shows up.

**Comment by k1ky** [comment]
Excellent!  Next up will be to test the WI-Fi as WAN on the 5GHz models.  I figured we would get past this issue first!

**Comment by k1ky** [comment]
N-1357 fixes this issue.  Thanks for the quick response!
