### ISSUE TITLE
Expected internet traffic when operating tunnel - 800+MB/day?

### ISSUE THREAD

**Issue by nathantcampbell** [aredn/aredn#389]
Hi,

We have a couple nodes that are remote and operating via a tunnel through a cellular hotspot until we get RF links out to them. We've found that even with no device-driven traffic, the HAP consumes about 850 MB / day or 3 MB per minute. It is our suspicion this is related to OLSR updates? We're on the Willamette Valley Mesh network which hovers around 270 nodes.

Is it likely this continuous traffic is OLSR updates? Is there any way to manually mitigate how often this occurs on these remote devices to decrease the data usage?

Controlled test case is a HAP with no devices, tunneled into the network (single connection so no traffic should be routed through the node).
Downloading 3MB/5min and uploading 200KB/5min.

![image](https://user-images.githubusercontent.com/24758209/173131386-034d65c5-3e24-4704-a92a-491af2dcce7a.png)

Nathan, AI7NC

**Comment by VA2XJM** [comment]
Our group have an LTE backup link at one site. To mitigate this, we enable the tunnel link to that site ONLY when it is needed and for the shorter amount of time possible due to cost and bandwidth limitation. In our case, the remote LTE site tunnel is always active and we can enable/disable the link from the main tunnel "server" device whenever it is needed.

**Comment by dman776** [comment]
Do you have mesh gateway enabled on this node?  (Ie.   Allow nodes on the mesh to access my wan connection?)

Thanks,
Darryl

**Comment by nathantcampbell** [comment]
Negative, plus there are no devices connected to the HAP. 

![image](https://user-images.githubusercontent.com/24758209/173136852-1ad859a4-2450-4c85-931f-daaf595ea434.png)

**Comment by aanon4** [comment]
Back of the envelope calculations, OLSR will send ~ 2 MB of traffic across a link per node on the network per day. It's the way the protocol works I'm afraid. So with 270 nodes my math puts it lower than you're observing, but clearly in the right ballpark.

**Comment by nathantcampbell** [comment]
Gotcha, is the traffic pushed or pulled based on parameters set on the node? Just thinking around if there's an option to decrease the update schedule if it's a pull.

**Comment by aanon4** [comment]
You can reduce the traffic, but as it's pushed from each node, you'd have to do that at every node.

**Comment by nathantcampbell** [comment]
Ok well I think that's plenty of evidence to pin this on OLSR updates, bummer it's pushed so the only way to control it for these sites is to have the link disabled. Thanks for the help everyone, we can close the issue.
