### ISSUE TITLE
AREDNMESH.org Online Map doesn't accept updates and removes existing node entry - 3.22.6.0

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#394]
The AREDNMESH.org online map isn't accepting Map Publishes from nodes running the past few nightlies nor the latest Production Firmware 3.22.6.0.  The nodes "seem" to publish, but the online map entries are removed for same node and don't appear anywhere to be on the map.

**Comment by dman776** [comment]
I'll check on this next week when I am back home

**Comment by dman776** [comment]
The maps have been corrected.
