### ISSUE TITLE
latest ARDEN MESH firmware update vs Ubiquity PBE M5 300

### ISSUE THREAD

**Issue by kk4ib** [aredn/aredn#395]
Just flashed the PowerBeam M5 300 with 3.22.1.0-ar71xx-generic-ubnt-loco-m-xw-squashfs-sysupgrade.bin;  and now the Status page won't populate; all other pages work fine and the PBE joined the network via router port and via RF.
[supportdata-KK4IB-PBE-M5-202206131806.zip](https://github.com/aredn/aredn/files/8893916/supportdata-KK4IB-PBE-M5-202206131806.zip)
![IMG_3601](https://user-images.githubusercontent.com/107429659/173431363-a7cda1d8-2371-4a06-8b39-ae87b3634fee.jpeg)

**Comment by dman776** [comment]
Try it with the latest production release 3.22.6.0

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/396
This fixes unknown radio models being displayed. I'll leave the actually support of this model to @ae6xe

**Comment by ae6xe** [comment]
Same comment - Ref:  https://github.com/aredn/documentation/issues/172#issuecomment-1154389350

**Comment by kk4ib** [comment]
This issue was FIXED with Nightly Build 3.22.6.1; the PBE M5 300 is working properly.

**Comment by kk4ib** [comment]
That’s what I did to cause the issue. Using 3.22.1.0 it works fine.

It actually works fine with "22.6” also, just won’t populate the Status page.

sparks



On Jun 13, 2022, at 4:45 PM, dman776 ***@***.***> wrote:


Try it with the latest production release 3.22.6.0
