### ISSUE TITLE
New Mikrotik HAP AC3 - Model Support Request

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#401]
Request to add Mikrotik HAP AC3 to AREDN.  It is supported by OpenWRT.
ipq40xx: add support for MikroTik hAP ac3
This adds support for the MikroTik RouterBOARD RBD53iG-5HacD2HnD (hAP ac³), a indoor dual band, dual-radio 802.11ac wireless AP with external omnidirectional antennae, USB port, five 10/100/1000 Mbps Ethernet ports and PoE passthrough.
See https://mikrotik.com/product/hap_ac3 for more info.

**Comment by ae6xe** [comment]
The HAP AC3 is on the list along with many 802.11ac devices.    I have very early images on this device now.  However, there remains work to get the 802.11ac wireless working as the code is proprietary and there is  a need to work with 3rd parties that have NDAs and rights to make changes.   So all 802.11ac devices are in this category.

**Comment by k1ky** [comment]
Shall I change the title to broaden the description or is there another issue already covering this??

**Comment by k1ky** [comment]
It appears that we have some model support in the nightlies - do we keep this issue open until Production release?

**Comment by aanon4** [comment]
I think we'll close this now as it's stable in nightly. Helps us track what's pending before the next release.
