### ISSUE TITLE
Can't enable RF 

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#402]
Got this error when trying to re-enable RF on a node.  Running NB 1404.  Attached Support Data file (renamed as .zip to allow attachment.

![image](https://user-images.githubusercontent.com/1124405/174393164-9a353a9d-9b8e-4860-bbd1-8a9a8839a501.png)
[supportdata-K6PVR-VC-SimiEast-2G-202206171957.zip](https://github.com/aredn/aredn/files/8931057/supportdata-K6PVR-VC-SimiEast-2G-202206171957.zip)

**Comment by aanon4** [comment]
Temporary fix is to hit apply on the lqm settings. Will look at a proper fix

**Comment by Orv** [comment]
That works - thanks!

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/403 (proper fix)

**Comment by Orv** [comment]
Fixed.
