### ISSUE TITLE
Wi-Fi client cannot connect to open Access Point

### ISSUE THREAD

**Issue by nc8q** [aredn/aredn#424]
An AREDN node in Wi-Fi client mode cannot connect to open Access Point.
A zero length passphrase/password is not allowed.

**Comment by ab7pa** [comment]
Is this a duplicate of Issue #421 which was fixed in yesterday's nightly build, or is there a new issue with the WAN Wifi Client?

**Comment by nc8q** [comment]
Yes, it is a duplicate.
Sorry, I am not familiar with navigating github.
