### ISSUE TITLE
Spectral view not working on Rocket M3 with nightly 1479

### ISSUE THREAD

**Issue by k6ccc** [aredn/aredn#425]
Spectral display blank on Rocket M3 XM
BTW, looks great on all the other nodes I have updated.
![image](https://user-images.githubusercontent.com/36935831/177010701-80c855c1-9480-4b46-b08e-47f48e26ae10.png)

**Comment by k6ccc** [comment]
Note that all three of my M3 Rockets are the same way.  M5 Rockets (both XM and XW) are fine.

**Comment by k6ccc** [comment]
One more thing, I have a support data file, but can't upload that file type here.
Posted it to:  http://k6ccc.org/AREDN/supportdata-K6CCC-RocM3-1-1-202207021040.tgz

**Comment by k1ky** [comment]
@k6ccc to upload .tgz file, I believe I either rename it or zip it to a .z extension.  Sure would be nice if this platform supported a .tgz extension.

**Comment by k1ky** [comment]
I also get a blank spectral screen display with Nanostation M5 (XM) and Nanobridge M5.  No registration marks or spectrum, just a blank box as you depicted above.

**Comment by ae6xe** [comment]
support dump shows this error on the K6CCC-RocM3-1-1 device: 

Sat Jul  2 10:25:34 2022 daemon.err uhttpd[1006]: /usr/bin/lua: /www/cgi-bin/scan:353: attempt to get length of local 'bucket' (a nil value)
Sat Jul  2 10:25:34 2022 daemon.err uhttpd[1006]: stack traceback:
Sat Jul  2 10:25:34 2022 daemon.err uhttpd[1006]: 	/www/cgi-bin/scan:353: in main chunk
Sat Jul  2 10:25:34 2022 daemon.err uhttpd[1006]: 	[C]: ?

**Comment by k1ky** [comment]
I have another Nanobridge M5 with only 3 active connections that does have a functional spectral display.

**Comment by aanon4** [comment]
This should be fixed in https://github.com/aredn/aredn/pull/429

**Comment by k1ky** [comment]
All of my Nanobridges are functioning now with Nightly 1510.  No display issues with any devices known at this time.  Still wondering if the active frequencies are being displayed in the proper places?
