### ISSUE TITLE
DtD links not shown in Neighbor Status Occasionally - NB 1479

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#428]
I noticed that on a few nodes, the Neighbor Status omits the DtD links that are shown in the Mesh Status.  It doesn't seem to be band related; I've seen it on both 2 GHz and 3 GHz so far.  Here's an example:

![image](https://user-images.githubusercontent.com/1124405/178119446-2bf32821-f81f-43f1-b8bf-65eeb0565dca.png)

![image](https://user-images.githubusercontent.com/1124405/178119456-b0f3f93c-0c2f-40fb-9967-41096a0a6b2f.png)

Support data file from this particular node is attached (.tgz manually renamed to .gz)

[supportdata-W6BI-VC-SIMINORTH-3G-202207091206.gz](https://github.com/aredn/aredn/files/9077743/supportdata-W6BI-VC-SIMINORTH-3G-202207091206.gz)

**Comment by aanon4** [comment]
If you have a node like this, can you attach the output from the following command:

**Comment by Orv** [comment]
Here you go:

root@W6BI-VC-SIMINORTH-3G:~# cat /proc/net/arp
IP address       HW type     Flags       HW address            Mask     Device
10.106.154.60    0x1         0x2         68:72:51:6a:9a:3c     *        wlan0
10.111.33.194    0x1         0x2         14:cc:20:6f:21:c2     *        br-dtdlink
10.112.167.69    0x1         0x0         00:00:00:00:00:00     *        br-dtdlink
10.246.107.9     0x1         0x2         24:a4:3c:f6:6b:09     *        wlan0
10.65.50.70      0x1         0x0         00:00:00:00:00:00     *        br-dtdlink
10.15.20.232     0x1         0x2         44:d9:e7:0f:14:e8     *        br-dtdlink
10.246.107.9     0x1         0x0         00:00:00:00:00:00     *        br-dtdlink
10.112.167.65    0x1         0x0         00:00:00:00:00:00     *        br-dtdlink

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/431

**Comment by Orv** [comment]
Nightly build 1503 resolves this issue
