### ISSUE TITLE
Spectral View displaying blank chart in Mikrotik LHGs and SXTs

### ISSUE THREAD

**Issue by nc8q** [aredn/aredn#433]
On my Mikrotik LHGs and SXTs: 
Nightlies, 1479, 1490, and 1503 have no chart data.
Nightly 1503's Spectral View is blank save for a legend insert.

My Ubiquiti PBE-M5-400 displays a chart with data. :-)
So far, all of my GL-iNet devices display 2.4 GHz spectral view data. :-)

**Comment by aanon4** [comment]
How do the Mikrotik's look on 1510?

**Comment by nc8q** [comment]
Spectral View works with Mikrotik LHG and SXTsq in Nightly Build 1510.
:-) Thanks Tim.
Chuck
