### ISSUE TITLE
NB 1520 - Mesh Status Normal, Neighbor Status Blank

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#438]
![sulphur-to-oxnard_Mesh_status](https://user-images.githubusercontent.com/1124405/179837526-10e8668a-59ed-4388-b031-646e4df6da13.png)
![sulphur-to-oxnard_Neighbor_status](https://user-images.githubusercontent.com/1124405/179837553-7af152b9-5aec-4b17-a4d5-84d160df0d02.png)
[supportdata-K6PVR-VC-Sulphur-to-Oxnard-5G-202207191256.gz](https://github.com/aredn/aredn/files/9144277/supportdata-K6PVR-VC-Sulphur-to-Oxnard-5G-202207191256.gz)

First NB 1520 I've loaded.  Will look at others soon.

**Comment by Orv** [comment]
Works properly on second node (different hardware).

**Comment by aanon4** [comment]
Odd. No errors that I can see in the logs files. If you reboot does it "fix" things?

**Comment by Orv** [comment]
I know what went wrong; rebooting it did in fact fix the issue.  Disregard!
