### ISSUE TITLE
New installation on AR300M16 defaults to Channel -2 Bandwidth 20 MHz

### ISSUE THREAD

**Issue by pmilazzo** [aredn/aredn#446]
When installing AREDN on a new AR300M16 (2.4 GHz), the node initially defaults to Channel -2, which is correct, but with a bandwidth of 20 MHz, which is not. I observed this behavior with both 3.22.6.0 and nightly 1510-ba55aed.

**Comment by aanon4** [comment]
I think it's the old perl thinks 10 == "10" while in lua 10 ~= "10" problem.

**Comment by aanon4** [comment]
Booted up a brand new AR300M and it came up with bw of 10.
