### ISSUE TITLE
Event Mode - White List - nodes authorized to communicate 

### ISSUE THREAD

**Issue by ae6xe** [aredn/aredn#46]
Ability to select a list of mesh nodes that may participate in an event.  Traffic from other mesh nodes would be blocked.   Selected on node by node basis for overlapping groups to limit communications.

**Comment by ab7pa** [comment]
Seems like the features available in LQM (link quality manager) help to resolve this issue.

**Comment by VA2XJM** [comment]
> Seems like the features available in LQM (link quality manager) help to resolve this issue.

You are right. It was my submission on the previous repository. So it can be closed.

**Comment by dman776** [comment]
LQM solved the blacklist issue, but, we can close this too if you want

**Comment by ab7pa** [comment]
LQM has a **whitelist** feature too, so this has been resolved.  THX

**Comment by km6lslf** [comment]
How do we use the whitelist feature with LQM?

**Comment by ab7pa** [comment]
Explained in the documentation:
https://docs.arednmesh.org/en/latest/arednGettingStarted/advanced_config.html#link-quality-manager-lqm-settings
