### ISSUE TITLE
[Feature Request] Indicate whether WAN is coming from wifi or hardwired.

### ISSUE THREAD

**Issue by aanon4** [aredn/aredn#467]
Tweak the language on the main page to indicate whether the WAN is wifi or handwired.

**Comment by ae6xe** [comment]
bundled with this request, or possibly with another issue request...    The internet path may be down upstream, e.g. a home network router or the service provider may be the failure point.  The WAN gateway may still attempt to route traffic to the internet, but it never reaches.    A periodic check to e.g. 8.8.8.8 or other reliable internet service to determine if the internet is still reachable could be used to turn the gateway advertisement on/off and automatically reroute the traffic to  another gateway.

**Comment by aanon4** [comment]
> bundled with this request, or possibly with another issue request... The internet path may be down upstream, e.g. a home network router or the service provider may be the failure point. The WAN gateway may still attempt to route traffic to the internet, but it never reaches. A periodic check to e.g. 8.8.8.8 or other reliable internet service to determine if the internet is still reachable could be used to turn the gateway advertisement on/off and automatically reroute the traffic to another gateway.

Making this its own issue.
