### ISSUE TITLE
We dont actually prevent traffic between LAN and WAN when "Prevent LAN devices from accessing WAN" is enabled

### ISSUE THREAD

**Issue by aanon4** [aredn/aredn#475]
See https://github.com/aredn/aredn/issues/474 for more details, but it seems we don't actually prevent traffic between the LAN and the WAN when you check the "Prevent LAN devices from accessing WAN" box. All that does is decide whether to hand a default route to the LAN client. The LAN client can set its own default route and happily access the WAN. We should add a firewall rule to prevent this.

Problem validated on version 3.22.6.0 using an AR750 connected to the WAN with a Mac as a LAN client and a hand-set default route to the AR750.

**Comment by WZ0C** [comment]
This is related to issue #26.
