### ISSUE TITLE
Mystery Device

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#479]
I have a Ubiquiti  "Rocket M5 Titanium Ti GPS".   It's not listed in the Nightly Build README file and both the Rocket M and Rocket M XS software packages yield "[!!!! UNSUPPORTED DEVICE !!!!". 
For some reason I'm unable to attach the support data file.   Contact me for it.

**Comment by aanon4** [comment]
This is the important snippet:
```
========== /usr/local/bin/get_hardwaretype ==========
rocket-m-xw
========== /usr/local/bin/get_boardid ==========
0xffff
========== /usr/local/bin/get_model ==========
Ubiquiti Rocket M XW
========== /usr/local/bin/get_hardware_mfg ==========
Ubiquiti
```
I'm concerned that the boardid comes back as 0xffff ... which is worrying non-specific. Does anyone know what the official Ubiquiti board id of this radio is?

**Comment by Orv** [comment]
OK - this came to me used with a comment "Missing MAC?"   That lines up with the all ones board id, I think.  I'm closing this incident and tossing this device in the eWaste bin.

**Comment by aanon4** [comment]
I went and looked at all the MACs. They are all 00:02:03:05:05:06 which seems a bit wrong.

**Comment by Orv** [comment]
Closing this issue.
