### ISSUE TITLE
A node will not communicate its name.  Neighbors display the IP address only.

### ISSUE THREAD

**Issue by ae6xe** [aredn/aredn#48]
Ref:  https://www.arednmesh.org/content/occasional-dns-resolutionbroadcast-failures-new-release 

After booting, a node does not communicate its name to neighbors.    These neighbors will display an IP address only.    This functionality is part of the OLSR Nameservices plugin.      

If this situation is encountered after the node is booted, then boot again or restart olsrd - "/etc/init.d/olsrd restart".  This action is taken on the node with the IP address showing on its neighbors' mesh status. 

This node can be reached by using the IP address, e.g.  "http://1.2.3.4:8080"

**Comment by dman776** [comment]
re-test with 3.22.1.0.   a number of OLSR issues where patched in that release which could affect this issue.

**Comment by mpannen1979** [comment]
So far so good with 3.22.1.0+
