### ISSUE TITLE
[Feature Request] Configure static routes that are persistent across reboots and firmware upgrades

### ISSUE THREAD

**Issue by dranch** [aredn/aredn#482]
Creating this issue by request from KN6PLV to make sure it's not lost:

Request:  Is there a place that I can configure static routes on a HaP running AREDN that will be reloaded upon reboot as well across firmware updates?  

Tim response: There’s a file “/etc/local/mesh-firewall/59-custom-rules” which is just a shell script executed when the firewall is reloaded.
It’s preserved across upgrades - you could pop stuff in there but … kind of ..  bit messy.  There’s probably a more official openwrt way to do it involving files in /etc/config … but we mess with those quite extensively so off the top of my head I couldn’t say if custom changes are preserved or not

**Comment by aanon4** [comment]
This appears to be the official way to add static routes - https://openwrt.org/docs/guide-user/network/routing/routes_configuration - so I just need to implement a mechanism so we can include extra routes when we regenerate our /etc/config/network file. I think we already have a way include files in our config files so probably not too hard.
