### ISSUE TITLE
Mesh Status forgets about links that are still working

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#486]
I've seen this a couple of times before.  A high-level node says it's no longer seeing any RF neighbors, yet obviously it's working as my node is able to connect to it.   Going to any other page and returning to mesh status restores the expected display.

![k6pvr-vc-simieast-5g_mesh_status](https://user-images.githubusercontent.com/1124405/186805523-44e2f512-acfe-4cb4-a3ed-0698aad0383b.png)
[supportdata-K6PVR-VC-SimiEast-5G-202208251833.gz](https://github.com/aredn/aredn/files/9429359/supportdata-K6PVR-VC-SimiEast-5G-202208251833.gz)

**Comment by aanon4** [comment]
So this is probably another case of OLSR updating a file and it being incomplete when this display is being generated .. which is why it then looks okay if you come back to it a moment later. We've seen this manifest in a couple of ways now so I should probably find a way to deal with it.

**Comment by AJ6GZ** [comment]
Other behaviors seen: OLSR 0 Total / 0 Nodes on Node Status screen, and all-IP-only current neighbor entries on Mesh Status screen.  As noted above, both go back to normal upon refresh.

**Comment by aanon4** [comment]
Did the recent nightly fix this for you?

**Comment by Orv** [comment]
Looks OK, but doesn't occur routinely.  Will monitor.  Suggest closing issue for now.  Will open a new one if it reoccurs.

**Comment by Orv** [comment]
This has been resolved in the nightly builds.
