### ISSUE TITLE
Dropdown for Download Firmware on node doesn't show latest firmware.

### ISSUE THREAD

**Issue by AJ6GZ** [aredn/aredn#489]
I don't use this feature, but it was brought to my attention... I don't know how long it's been broken.

On the Administration / Firmware Update section, after a refresh, the dropdown for Download Firmware does not contain recent firmware versions on several different node models (tested NSM, PowerBeam) and for some it does (SXT, possibly other MikroTiks).

![image](https://user-images.githubusercontent.com/42795596/187012826-a02e432c-d86e-4fe5-af6e-2cd74a0fc890.png)

**Comment by aanon4** [comment]
If you reboot the node then hit refresh again does the problem persist?

**Comment by AJ6GZ** [comment]
Same result after reboot.

**Comment by dman776** [comment]
What is the download path on the advanced config page for firmware?   You may want to reset to default and re-save

**Comment by AJ6GZ** [comment]
It was set to http://downloads.arednmesh.org/firmware/ubnt
Setting default changed to http://downloads.arednmesh.org/firmware/ 
Newer MikroTik already had this path.
Rebooted/Refresh and OK now.   Holdover from many upgrades ago I guess...
Will pass it on!
