### ISSUE TITLE
BUG! Now run an hourly check on published service and “unpublish” any which aren’t really available.  Re-enabled services will be republished automatically.

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn#490]
All of the links I've set up to reach the Edgeswitches, look to be ghosted off the list. They must not respond to the check???

**Comment by aanon4** [comment]
Can you add the support data for a node with this issue? Thanks.

**Comment by mathisono** [comment]
Every hub that's got a edgeswitch linked, has had it dropped...  
[supportdata-KJ6DZB-PBR-10-202208271030.gz](https://github.com/aredn/aredn/files/9438411/supportdata-KJ6DZB-PBR-10-202208271030.gz)

**Comment by aanon4** [comment]
So the problem appears to be HTTPS. You have a link which redirect to an https://.... link, and of course we don't support encrypted communications on the mesh, so this link isn't published.

**Comment by aanon4** [comment]
Consensus is https links should be considered valid.
Fix: https://github.com/aredn/aredn/pull/491

**Comment by aanon4** [comment]
@mathisono Can you verify this is fixed in the latest nightly?

**Comment by aanon4** [comment]
Closing this as fixed in nightly.
