### ISSUE TITLE
Node names showing as IP addresses after update to 3.22.8.0

### ISSUE THREAD

**Issue by ai6bx** [aredn/aredn#493]
After updating, all neighbor nodes show as IP addresses with link type as a question mark. A couple refreshes brings the node names back. Going back to the node shortly after, the nodes show as IP addresses again.

**Comment by aanon4** [comment]
Closing as a known issue (already tracked).

**Comment by Orv** [comment]
Doesn't occur routinely.  Will monitor.  Suggest closing ticket and opening new one if it reoccurs.

**Comment by ai6bx** [comment]
This is happening quite frequently on my nodes.

**Comment by aanon4** [comment]
@ai6bx Could you try the current nightly and see if it improves?

**Comment by ai6bx** [comment]
Sure. I have attached the latest support file as well.

 

From: Tim Wilkinson ***@***.***>
Reply-To: aredn/aredn ***@***.***>
Date: Friday, September 9, 2022 at 9:19 PM
To: aredn/aredn ***@***.***>
Cc: ai6bx ***@***.***>, Mention ***@***.***>
Subject: Re: [aredn/aredn] Node names showing as IP addresses after update to 3.22.8.0 (Issue #493)

 

@ai6bx Could you try the current nightly and see if it improves?

**Comment by ai6bx** [comment]
Same with nightly.

 

From: Tim Wilkinson ***@***.***>
Reply-To: aredn/aredn ***@***.***>
Date: Friday, September 9, 2022 at 9:19 PM
To: aredn/aredn ***@***.***>
Cc: ai6bx ***@***.***>, Mention ***@***.***>
Subject: Re: [aredn/aredn] Node names showing as IP addresses after update to 3.22.8.0 (Issue #493)

 

@ai6bx Could you try the current nightly and see if it improves?

**Comment by aanon4** [comment]
Could you attach a screen shot and the nightly version you observe this on? Thanks.

**Comment by ai6bx** [comment]
Here you go.

 

From: Tim Wilkinson ***@***.***>
Reply-To: aredn/aredn ***@***.***>
Date: Saturday, September 10, 2022 at 9:22 AM
To: aredn/aredn ***@***.***>
Cc: ai6bx ***@***.***>, Mention ***@***.***>
Subject: Re: [aredn/aredn] Node names showing as IP addresses after update to 3.22.8.0 (Issue #493)

 

Could you attach a screen shot and the nightly version you observe this on? Thanks.

**Comment by aanon4** [comment]
I'm afraid I dont see any screenshots.

**Comment by ai6bx** [comment]
Try this one.

 

From: Tim Wilkinson ***@***.***>
Reply-To: aredn/aredn ***@***.***>
Date: Saturday, September 10, 2022 at 5:24 PM
To: aredn/aredn ***@***.***>
Cc: ai6bx ***@***.***>, Mention ***@***.***>
Subject: Re: [aredn/aredn] Node names showing as IP addresses after update to 3.22.8.0 (Issue #493)

 

I'm afraid I dont see any screenshots.

**Comment by aanon4** [comment]
Possibly you need to do this on github rather than via email?

**Comment by ai6bx** [comment]
Just uploaded under the issue request.
