### ISSUE TITLE
Mikrotik hAP Ac Lite How to recover password

### ISSUE THREAD

**Issue by sauerteig** [aredn/aredn#565]
Hi,
after flashing the device using pxesrv and and updating with aredn-3.22.8.0 I did some  basic setup including password. 
Now I lost the password.
I started the flash procedure again with pxesrv. While connected to the Microtik and klicking on SETUP I'm prompted for the password. But root / Hsmm doesn't work any more.
Who can help?
Found solution: Use Failsafe feature
Problem fixed
73 Martin DG6MS

**Comment by Orv** [comment]
Good deal.  Please close this Issue it it's fully resolved.
Orv W6BI
