### ISSUE TITLE
Iperfspeed 0.6 Lua not displaying available nodes in Server or Client list with Nightly 2017+

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#589]
Iperfspeed 0.6 Lua doesn't display any available nodes in the Server or Client list with the new OpenWRT N-2017+ Nightly upgrades.

**Comment by aanon4** [comment]
Please try this version: https://github.com/kn6plv/iperfspeed/raw/master/iperfspeed_0.7_all.ipk

**Comment by k1ky** [comment]
Looks like it works with 2023 on a GLUSB-150.  Is this version downward compatible if installed on older Firmware versions?

**Comment by aanon4** [comment]
Yes.

**Comment by k1ky** [comment]
Excellent - You da man!

**Comment by aanon4** [comment]
Going to close this one then - thanks!

**Comment by k1ky** [comment]
Having issues with Server side talking to clients.  It appears that it works in reverse.

**Comment by aanon4** [comment]
The only change to make it work was deleting a library reference which wasn't being used - not sure how it can have reversed

**Comment by k1ky** [comment]
I think it needs more work.  See notes in issue.

    On Sunday, December 25, 2022 at 02:25:26 AM CST, Tim Wilkinson ***@***.***> wrote:  
 
 


Going to close this one then - thanks!

**Comment by aanon4** [comment]
See note above - nothing has changed about how the program runs - only a library reference which isn't being used was removed. I've reopened for now, but dont see how it can be working in reverse compared to before.

**Comment by kc2cbd** [comment]
On my GLUSB150 it can't be a server but works fine as a client.

**Comment by k1ky** [comment]
And now they are all working on my GLUSB150 and AR750.  Let's let this one soak for a little while and revisit.

**Comment by k1ky** [comment]
No further issues with 0.7 at this time. Closing this issue.
