### ISSUE TITLE
MeshChat 2.2 doesn't communicate - new OpenWRT Nightlies 2017+

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#590]
MeshChat 2.2 does not see or communicate with any stations in Zone when installed on new OpenWRT Nightly 2017+ updates

**Comment by aanon4** [comment]
Please try - https://github.com/kn6plv/meshchat/raw/master/meshchat-api_2.3_all.ipk

**Comment by k1ky** [comment]
2.3 Doesn't seem to pick up on the Correct Zone as set up - continuing to test.

**Comment by k1ky** [comment]
Attempts to save changes in the Port Forwarding area returns a Bad Gateway message.

**Comment by aanon4** [comment]
That ones separate from MeshChat :-(
Looks like there's still more to do on MeshChat as well.

**Comment by aanon4** [comment]
Try 2.4

**Comment by k1ky** [comment]
Version 2.4 appears to be working!

**Comment by k1ky** [comment]
I may still be experiencing some issues with 2.4 Syncing with Zone.

**Comment by aanon4** [comment]
Can you attach the support tool data dump?

**Comment by k1ky** [comment]
Done - this appears to be a one-way outgoing issue from the new Openwrt firmware.  I installed 2.4 MeshChat on a TPLink CPE510 and it is working both ways and sees all of the stations within the Zone.

**Comment by k1ky** [comment]
Looks like MeshChat v2.5 took care of it.  Compatability back to units running v2.2 has been tested. Installed on GLINET AR-750 running N-2031.

**Comment by k1ky** [comment]
No further issues with version 2.5 - closing this issue.
