### ISSUE TITLE
mikrotik rb-912uag-5hpnd firmware file not valid

### ISSUE THREAD

**Issue by kc2cbd** [aredn/aredn#619]
Trying to upgrade a node to 2096 and also tried 2024.
Node says 
Firmware CANNOT be updated
firmware file is not valid

![W4WTN-Basebox5-Fail](https://user-images.githubusercontent.com/25018130/210869763-de951080-1480-403b-b7dd-c5c36854b7af.png)

**Comment by aanon4** [comment]
Could you log into the node and send me the output when you run the following:

```for i in /tmp/sysinfo/* ; do echo $i ; cat $i; do```

Thanks

**Comment by aanon4** [comment]
Also, please confirm the specific firmware filename you were loading.

**Comment by kc2cbd** [comment]
Firmware that I was using was aredn-2096-fce9629-ath79-mikrotik-mikrotik_routerboard-912uag-5hpnd-squashfs-sysupgrade.bin
![W4WTN-putty](https://user-images.githubusercontent.com/25018130/210891176-24992a3b-6628-4e24-82d4-cc0880186a50.png)

**Comment by kc2cbd** [comment]
If we were able to get the newer firmware on this device, would it upgrade fine after that?

**Comment by aanon4** [comment]
Yes - it's just the transition which is the limitation.

**Comment by aanon4** [comment]
Closing as an upgrade path from 3.22.12.0 to the next release will not be possible. A re-install must be done and then upgrades can continue.
