### ISSUE TITLE
Mikrotik routerboard-952ui-5ac2nd firmware failed

### ISSUE THREAD

**Issue by kc2cbd** [aredn/aredn#625]
The ability for the hAP to go back to older firmware is now broken.
Firmware CANNOT be updated
firmware file is not valid: platform check image failed
using the firmware aredn-2089-bc77ff8-ath79-mikrotik-mikrotik_routerboard-952ui-5ac2nd-squashfs-sysupgrade.bin

**Comment by aanon4** [comment]
Can you confirm which firmware you running and which you are trying to revert to?

**Comment by kc2cbd** [comment]
Currently on aredn-2103-5214d35-ath79-mikrotik-mikrotik_routerboard-952ui-5ac2nd-squashfs-sysupgrade.bin

**Comment by kc2cbd** [comment]
The USB150 won't go back to and older firmware either.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/626

**Comment by aanon4** [comment]
The fix for the moment:
Log into your node:
type:
```echo "#!/bin/true" > /usr/local/bin/firmwarecheck.sh```

**Comment by kc2cbd** [comment]
That allowed my nodes to go back to an older firmware
