### ISSUE TITLE
Package Management shows ~40 options to download 'Package version' in 2131 build

### ISSUE THREAD

**Issue by ae6xe** [aredn/aredn#637]
on Mikrotik ac2, after refreshing the 'download packages', there were ~40 selection entries to download 'package version'.  The actual package names are not showing, except 'kmod*' and 'block-mount*'.   I was looking for tcpdump to help debug some issues.  On 2131 nightly build image.  The refresh occurred before the next nightly build.

**Comment by dman776** [comment]
may be specfic to the ipq40xx architecture.    It works find on my hAP AC Lite (generic/mikrotik)

**Comment by dman776** [comment]
what are the values in your AdvConfig firmware paths?   are they correct for the arm_cortex..... packages?

**Comment by dman776** [comment]
it’s hard coded in the advandedconfig page in the defaultPackageRepos() function around line 77
need to pull that value from “/etc/openwrt_release DISTRIB_ARCH” instead

**Comment by ae6xe** [comment]
Confirmed, all the paths on the hap ac2 need to have changed in the download paths:  from "mips_24kc", to "arm_cortex-a7_neon-vfpv4".

**Comment by dman776** [comment]
fixed by #672
