### ISSUE TITLE
Mikrotik LDF5 Not upgrading

### ISSUE THREAD

**Issue by kc2cbd** [aredn/aredn#640]
Tried to use the new firmware for the LDF5 and it doesn't upgrade

`for i in /tmp/sysinfo/* ; do echo $i ; cat $i; done`
produces
`root@KC2CBD-LDF5-151-CKV-50TWR-106:~# for i in /tmp/sysinfo/* ; do echo $i ; cat $i; done`
`/tmp/sysinfo/board_name`
`rb-ldf-5nd`
`/tmp/sysinfo/boardid`
`MikroTik RouterBOARD LDF-5nD`
`/tmp/sysinfo/hardware_mfg`
`MikroTik`
`/tmp/sysinfo/model`
`MikroTik RouterBOARD LDF-5nD`

Is this going to be another that will have to be upgraded as if it's a new device and than it will work from there?

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/639

**Comment by kc2cbd** [comment]
Still not upgrading from Firmware 2002

**Comment by aanon4** [comment]
The PR has not been merged yet.

**Comment by kc2cbd** [comment]
Upgrade successful and appears to be functioning correctly,
