### ISSUE TITLE
UBNT AirRouter doesn't allow Wi-Fi AP or WAN Nightly tiny 2274

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#694]
Running Nightly 2274 doesn't have the RF Wi-Fi AP nor WAN selections available on units previuosly configured for such operation.
<img width="568" alt="image" src="https://user-images.githubusercontent.com/42675931/216683076-2b474144-abdf-468c-bc01-6d66b12f04e8.png">

**Comment by aanon4** [comment]
Tiny builds no longer include support for AP access by default due to the lack of space. The packages can be installed separately if you're in a small enough mesh environment where this wont cause problems. I'll make a note in the README.

**Comment by k1ky** [comment]
OK - Kinda figured that.  Can you point me to which module(s) I need to load in order to restore this function? At least the Wi-Fi AP mode as it is driving our Weather station at one of my repeater sites.

**Comment by aanon4** [comment]
Look for "wpad-mini" ... not the most obvious name.

**Comment by k1ky** [comment]
The wpad-mini install did the trick.  It also retained my previous AP setting and my Weather Station has reconnected and is reporting properly. On another note, I was able to "revert" another AirRouter tunning N-2074 back to N-2002, which restored the AP capability running the older Nightly firmware.  Thanks for the response.  Should I wait to close this until you update the README file?  This should be a "warning" to folks upgrading to the new OpenWRT tiny nightlies when loss of funtion is involved.

**Comment by aanon4** [comment]
Let's wait until this PR is merged:
https://github.com/aredn/aredn/pull/695

**Comment by k1ky** [comment]
Please be as specific as possible on critical module functions lost.  I'm aware of Tunnel and now the Wi-Fi AP and WAN functions.

**Comment by aanon4** [comment]
I'll talk to Steve about adding something to the docs about this - dont want to start listing all the potential packages for various scenarios here.

**Comment by ab7pa** [comment]
That information goes into the **Release Notes**.  The online docs do not contain any information about specific firmware builds or packages -- all of that information is always maintained in the _Release Notes_.

**Comment by ae6xe** [comment]
We document the port usage per device in the github README.    Wherever we
put device specific information, we should try to keep it all together.
 Note, device specific details are relevant across many releases.     It
doesn't seem to be the best place to put in the notes of a specific
release.  Is github the best place?

**Comment by k1ky** [comment]
Ready to close this one?

**Comment by aanon4** [comment]
Yes. I've moved copies of the release notes we post online into the git so people can easily refer to them here. We'll add appropriate notes when we do the final release.
