### ISSUE TITLE
Migrate OpenWRT hwmode to new band parameter

### ISSUE THREAD

**Issue by ab7pa** [aredn/aredn#699]
Evidently a couple of years ago OpenWRT deprecated the legacy `hwmode` parameter in favor of the new and more intuitive `band` parameter.  This may be a good thing for our firmware to migrate to as well.

![hwmode](https://user-images.githubusercontent.com/69524416/217587143-7adfe565-8faa-43ca-918f-38748b92ffda.png)

**Comment by Orv** [comment]
Is the 3 GHz band supported with band?

**Comment by ae6xe** [comment]
3GHz devices are 5GHz motherboards, with -2GHz down converters.   Linux and the Qualcom wifi chip only have awareness of 5GHz.   Thus, the band is 5g. We have to detect in the model or board ID that it is a 3GHz device and set UI info accordingly.

Same for 900MHz devices, a 2GHz motherboard with a downconverter.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1630
