### ISSUE TITLE
NB 2339 on hAP removes AP band selection if Mesh RF is on - 2 GHz only

### ISSUE THREAD

**Issue by k6ccc** [aredn/aredn#720]
On Nightly build 2339 on a hAP lite, if Mesh RF is enabled on a node that has the WiFi AP enabled on 5 GHz, the band selection for the AP is removed and the channels are forced to 2 GHz.  Then the node complains that you can't have Mesh RF and LAN AP on the same wireless card.
This screen capture is before I made any changes:
![hAP_2339_issue-1](https://user-images.githubusercontent.com/36935831/219881562-d4c2648a-ac6c-4888-b052-3049807df39b.png)

After enabling Mesh RF, AP Band selection is not longer there and only 2 GHz channels available for selection.
![hAP_2339_issue-2](https://user-images.githubusercontent.com/36935831/219881704-3724f60f-8085-4350-8ea9-883f446c2655.png)

After hitting Save, it bitches about Mesh and LAN AP trying to use the same wireless.
![hAP_2339_issue-3](https://user-images.githubusercontent.com/36935831/219881734-7ff61053-8c31-4bc2-848b-34b8769e47f7.png)

After disabling Mesh RF and saving, the Band selection for the LAN AP returns.

**Comment by k6ccc** [comment]
Similar problem on GL iNet AR750.  This node prior to upgrade to 2339 had the LAN AP enabled on 5 GHz and Mesh RF enabled on 2.4 GHz.  After updating to 2339, this is what I see on the basic setup page.  According to a WiFi analyzer on my phone, the AR750 really is operating the AP on channel 44 on 5 GHz - not channel 1 as indicated.
![AR750_2339_issue-1](https://user-images.githubusercontent.com/36935831/219901146-c3942935-0690-44ef-b7a7-28f34aa7ba60.png)

**Comment by k1ky** [comment]
It appears to work ok if MESH RF is NOT enabled, but otherwise pretty messed up when MESH RF is enabled.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/724

**Comment by k6ccc** [comment]
Looks like it is fixed on NB 2347 - tested on both hAP lite and iNet AR750.

**Comment by aanon4** [comment]
Thanks!

**Comment by k6ccc** [comment]
Well, not so fast.  I was able to update my newer hAP ac3 to NB 2347 and when enabling Mesh RF, the AP is locked to 2GHz.

**Comment by aanon4** [comment]
Let's keep the AP discussion over here (the other issue is just for the update process).
Pinging you on mattermost to ask some questions.

**Comment by aanon4** [comment]
This is what my hAP ac3 looks like with 2347 on it:
<img width="804" alt="Screenshot 2023-02-20 at 10 41 05 AM" src="https://user-images.githubusercontent.com/751258/220179820-40f95938-95d3-4829-8646-cfdc28704a56.png">

**Comment by aanon4** [comment]
If you're up for changing one line by hand to test something, that'd be fantastic?

File: /www/cgi-bin/setup
Currently:
```local alt_phy = phy == "phy0" and "phy1" or "phy0"```
Change to:
```local alt_phy = (not phy or phy == "phy0") and "phy1" or "phy0"```
And see how that changes things

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/728

**Comment by k6ccc** [comment]
To be honest Tim, editing a 1487 line file in vi is getting beyond my comfort level.  I can barely manage to use vi with an online help on another screen.
Unless the nodes have a more friendly editor.

**Comment by aanon4** [comment]
Not to worry - This should take care of the problem and I know you'll test the change once it hits nightly - much appreciated as ever.

**Comment by k6ccc** [comment]
Fixed a rev or two ago.
