### ISSUE TITLE
hAP ac3: PoE Passthrough Active In “Advanced Configuration” Menu

### ISSUE THREAD

**Issue by jksnake** [aredn/aredn#737]
When I graduated from the ac Lite to the ac3, I simply transferred my settings from the Lite, on which I used PoE Passthrough to power the Rocket M5.  It worked fine on the ac3 for about a month but the node has been malfunctioning for a couple of weeks.  It went completely dark this morning so, after turning the feature off, I placed a PoE injector in the Rthernet and everything works fine.

I then remembered hearing that PoE Passthrough is not available on the ac3…but it was!
![Uploading B4E3C537-179C-48C1-907E-8E7940013570.png…]()

Kevin Sherwood, AJ7C
![Screen Shot, hAP ac3 Advanced Config](https://user-images.githubusercontent.com/41887175/221924778-5c48d6dc-97c6-4640-b70d-1ff6dad754f4.jpg)

**Comment by aanon4** [comment]
In case anyone comes looking here, the PoE option is available on the AC3 but *not* the AC2. Also worth noting that the amount of power you can get from this PoE out is limited.

**Comment by jksnake** [comment]
Thanks for the info, Tim.Kevin Sherwood, AJ7CSent from my iPadOn Feb 28, 2023, at 09:43, Tim Wilkinson ***@***.***> wrote:﻿
In case anyone comes looking here, the PoE option is available on the AC3 but not the AC2. Also worth noting that the amount of power you can get from this PoE out is limited.
