### ISSUE TITLE
BPDU packets and also dhcp leaking to the (WAN)

### ISSUE THREAD

**Issue by mathisono** [aredn/aredn#746]
MY device has been kicked from the Campus network again! 

GL-AR750 
[supportdata-W6BB-RFS-HUB4-202303100946.gz](https://github.com/aredn/aredn/files/10944653/supportdata-W6BB-RFS-HUB4-202303100946.gz)

Im trying to Narrow down when this started with logs from campus. (likely unavailable because of equipment failure /replacement) If it was present before Dec 2022? This could be a problem with the Stable release, as that I upgraded hub4 to the nighty builds. I only know from the current switch that is going on after the network was restored in January 2023. It was then that Campus started monitoring for alerts generated by switches after January 2023. The BPDU packets and dhcp offers are coming from MAC 94:83:c4:0e:8a:e9, Device Name W6BBHUB4. The campus network is now alerting IT admins. The alert was described as "every couple days!" 

I dont know if Ive made a mistake in by upgrading this Node to nighty builds, and not leaving this equipment on 3.22.12.0 FW.   

This is a tunnel server with NUMBER of USERS!!! I need this ONLINE and ON the internet at this site. Im willing to salvage all of the tunnel server connection, and revert to  3.22.12.0 FW???

Is this related to https://github.com/aredn/aredn/pull/650

-------The note from IT------------
MAC 94:83:c4:0e:8a:e9, Device Name W6BBHUB4.

We're seeing two things we shouldn't, BPDU packets and also dhcp offers (something is acting as a dhcp server).  If you have a nat router it's possible that it has been bridged to the campus network on it's lan side, which would explain things.  Just to make it more interesting, this bpdu behavior is clearly intermittent and infrequent, it can go for days before triggering the uplink shutdown.  
-----------------------------

HELP!!!

**Comment by aanon4** [comment]
Could you also provide how this device connects to the campus setup? Is there a switch(s) involved? Any custom vlans? Anything about how it integrates would be useful

**Comment by mathisono** [comment]
![netweork problems ar rfs](https://user-images.githubusercontent.com/618284/224408231-4fc2a43c-bf91-4d1a-a157-6a61f4552df4.png)

**Comment by mathisono** [comment]
![netweork problems ar rfs vlans](https://user-images.githubusercontent.com/618284/224409752-7e5bef7b-d5ff-44d7-b7d9-0b0a03b2096c.png)

**Comment by aanon4** [comment]
Thanks! Unfortunately I'll probably have to setup a duplicate environment for this when I'm back home (so mid week).

**Comment by mathisono** [comment]
Your welcome to the device.  Next week of course!  

Other possible culprits: The hAP2ac or the edgeswitch it's self.

**Comment by aanon4** [comment]
That's okay. I have the devices already.

**Comment by ae6xe** [comment]
shot in the dark... this could be explained if the device in use has an ar8216 internal switch chip (or a chip in this family).   The below patch may cause this behavior if linux is configured to know and use the internal switch.     The Device would need to be configured for linux to only think there is one interface and  vlan 1  and 2 would be on both ports (it's a dumb switch).   Can't configure the switch on a device with this patch -- not compatible.

https://github.com/aredn/aredn/blob/main/patches/711-aredn-ports-dumbswitch-ar8216.patch

**Comment by aanon4** [comment]
@mathisono Looking through the current configuration in nightly, the STP (which uses BPDU packets) is disabled on all the internal bridges. But that's just for generating traffic, not for forwarding it. I wondered if you could check the configuration of the STP on each of the ports on the EdgeSwitch and - as I think its enabled by default - disable it? If it's already disabled, that'd be good to know.

As for the DHCP leaks, can we disable the DHCP server on this device?The tunnels dont use it, and there's no local devices. I'm assuming it's for local hotspot access, but can we disable that too for the moment?

This is not a fix for the issue (obviously) so much as trying to get more data on the problem and - maybe - get the tunnels back online.

**Comment by mathisono** [comment]
Yes DHCP is now disabled. I dont use this as a hot spot, and now I dont host lan devices.

STP has always been off. Tho I wonder??? If The switch is leaking? The setting looks "Global" in the gui for this EdgeSwitch. 

-------JAY----------
So the earliest we can say for sure was Feb, but I'm guessing that it may have been masked by unrelated issues earlier than that, but not a whole lot earlier.  

So I'm guessing that your theory of the new code having an issue is probably correct.  
-----------------

Right now Im air gaped, I dont want to chance the ar750 on the network...  Until this traffic replicated.

**Comment by mathisono** [comment]
I no longer the endorse the gl AR750!!!!  I've swapped the device out for an hAP2... THEN...

--------------------
Good to hear that one issue is resolved, we still have a rogue dhcp server issue however.  94:83:c4:0e:8a:e9 is emitting dhcpoffers, e.g. it's acting as a dhcp server.  

The campus network is hardened against this, so effectively the impact is that it floods the switch logs, which isn't good but won't impact service directly.  I thought you should know, since it may also indicate a larger issue of leakage, or a misconfiguration.  It's definitely something that needs resolution in the near-ish future, but isn't a total crisis.  
-Jay
---------------

Ive disabled the DHCP server on the new device...

**Comment by aanon4** [comment]
Thought it would be too good to be true. Thanks for switching to the hAP ac2 though. I'll take a look at the DHCPD config.

**Comment by aanon4** [comment]
Any chance they could send you the logs? It's odd that the node is sending dhcpoffers as there's nothing connected to that node which is asking for an address. More information would be really helpful.

**Comment by aanon4** [comment]
Could you paste these lines onto the node:
```
nft 'add chain ip fw4 postrouting { type filter hook postrouting priority filter; policy accept; }'
nft 'add rule ip fw4 postrouting oifname "br-wan" udp sport 67 drop'
```
Re-enable DHCP and see if UC complain?

**Comment by mathisono** [comment]
complete...  waiting...

**Comment by mathisono** [comment]
That seems to have done the trick, last entry was at: Mar 21 16:31:56

Thanks!

-Jay

**Comment by aanon4** [comment]
Just to confirm - those firewall rules were added, DHCP re-enabled, and the problem has gone - yes? I'll make the PR tomorrow (have to wait for the power to come back so I can run it though my test setup)

**Comment by mathisono** [comment]
firewall rules were added YES!

DHCP re-enabled YES!

The problem has gone? It would appear so!!!

**Comment by mathisono** [comment]
No signs of leaking post patch, and on a post merged nighty build running on an hAP2.
