### ISSUE TITLE
ERR_NAME_NOT_RESOLVED when using GL-inet AR-300Ms

### ISSUE THREAD

**Issue by convolved-KY4G** [aredn/aredn#748]
I have two GL-inet AR-300Ms in an AREDN testbed.  The two are connected via the mesh network and can be seen by each other by clicking the mesh status button.  The connection sometimes shows a link of the name of the other node (e.g KY4G-GLAR300 which resolves to http://ky4g-glar300.local.mesh:8080/) and sometimes shows a link to its IP address (e.g. 10.23.85.83 which resolves to http://10.23.85.83:8080/cgi-bin/mesh).  If the IP address is shown, it can be clicked on and successfully goes to the status page of the other node.  If the name of the other node is shown, when you click on the name it says ERR_NAME_NOT_RESOLVED.  This happens consistently between the two nodes.  If you manually enter the IP address directly into a browser, it navigates to the status page just fine.  This seems like a bug.  I am running firmware 3.22.12.0 on both nodes.  There are three images below to further show what I am seeing.

![Capture1](https://user-images.githubusercontent.com/102929961/224749564-ac6a3a81-aa58-43af-aea3-fecf3d27b6ab.PNG)
![Capture2](https://user-images.githubusercontent.com/102929961/224749935-d4912009-66f3-473b-8b93-afd8f851cf0d.PNG)
![Capture3](https://user-images.githubusercontent.com/102929961/224750782-800dd3c5-1c35-4ab6-9479-6ab600f3aa0d.PNG)

**Comment by aanon4** [comment]
Are you running a release or a nightly. This should be fixed in the nightly build.

**Comment by convolved-KY4G** [comment]
I was running the latest release.  I thought the nightly build only fixed an issue specific to the AR150s.  I upgraded the nodes and it did indeed fix it for the AR300s too.
