### ISSUE TITLE
Gateway error when going to SETUP 

### ISSUE THREAD

**Issue by KenHorse** [aredn/aredn#763]
I just flashed 2 PBE-5AC-400 with the latest nightly build (dated today). All went fine but when trying to get to SETUP, I'm prompted for credentials (which I enter) and then I'm greeted with a "Bad Gateway The process did not produce any response" error.

This is happening on 2 of 2 units

**Comment by aanon4** [comment]
Can you post a screenshot of the main status page immediately before hitting 'setup'?

**Comment by aanon4** [comment]
Note that this hardware is not in the support list.

**Comment by KenHorse** [comment]
![20230324_171248](https://user-images.githubusercontent.com/16281605/227666327-792ecde9-a0d1-4c0a-a6ed-720953df78d6.jpg)
![20230324_171255](https://user-images.githubusercontent.com/16281605/227666341-27fdca7f-c5c3-4d75-9510-5eaca6651c78.jpg)

**Comment by KenHorse** [comment]
Oh? There's a difference between it and a Gen2?

**Comment by aanon4** [comment]
Please click on the text reading "!!!! UNSUPPORTED DEVICE !!!!" and post the information it should display. It's probably easy to add this.

**Comment by KenHorse** [comment]
Oh duh..the banner..

node: NOCALL-80-102-111
model: 0xe7f5

!!!! UNSUPPORTED DEVICE !!!!
boardid: 0xe7f5
Device HAS BEEN TESTED AS UNSUPPORTED

br-lan F0:9F:C2:51:66:6F
eth0   F0:9F:C2:51:66:6F
eth0.1 F0:9F:C2:51:66:6F
eth0.2 F0:9F:C2:51:66:6F
tunl0  00-00-00-00-00-00-00-44-00-00-00-00-00-00-00-00
wlan0  F0:9F:C2:50:66:6F

/proc/cpuinfo
system type		: Atheros AR9342 rev 2
machine			: Ubiquiti PowerBeam 5AC Gen2
processor		: 0
cpu model		: MIPS 74Kc V4.12
BogoMIPS		: 266.64
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp dsp2
Options implemented	: tlb 4kex 4k_cache prefetch mcheck ejtag llsc dc_aliases perf_cntr_intr_bit perf
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available


nvram
hsmmmesh.settings=settings
hsmmmesh.settings.wifimac='f0:9f:c2:50:66:6f'
hsmmmesh.settings.mac2='80.102.111'
hsmmmesh.settings.node='NOCALL-80-102-111'
hsmmmesh.settings.dtdmac='81.102.111'

**Comment by KenHorse** [comment]
BTW, the firmware is clearly shown at the selector webpage. That's where I got it

**Comment by aanon4** [comment]
While I see "Ubiquiti PowerBeam 5AC Gen2" and the "Ubiquiti PowerBeam 5AC 500" in the selector, I do not see the 400 variant listed.

**Comment by KenHorse** [comment]
Am I mistaken that the hardware reports itself as "machine : Ubiquiti PowerBeam 5AC Gen2"

**Comment by aanon4** [comment]
That's reporting what the firmware loaded onto the device is, not the device itself which is identified by the hex code boardid.

**Comment by KenHorse** [comment]
I saw /proc/cpuinfo and assumed it read the info from there

OK, well guess I'll wait for the built

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/765

**Comment by aanon4** [comment]
A build should now be available. If you could verify that'd be fantastic.

**Comment by KenArck** [comment]
Really sorry for the delay. Yes, all is working fine with the new build
