### ISSUE TITLE
UBNT Nanobeam AC Gen2 - Unspported Device

### ISSUE THREAD

**Issue by wu2s** [aredn/aredn#768]
After closing issue #757 I browsed to the device to begin configuring it.
Device showed Unsupported device message this is detailed below. Attempts to get to the Setup page resulted in error message "Bad gateway"
![Screenshot UBNT 20230329](https://user-images.githubusercontent.com/35403478/228599363-b3214f6f-c1c7-427d-b5aa-4530d3fe9e98.png)

**Comment by Orv** [comment]
Randy, the screenshot shows it as a Nanostation AC Gen1.  That may be different enough from the Gen2 to cause these symptoms,

**Comment by aanon4** [comment]
I'm building a new image for this device as we speak.

**Comment by aanon4** [comment]
New build submitted here - https://github.com/aredn/aredn/pull/770
Would be good to get this tested as its a bit of a guess in places.

**Comment by wu2s** [comment]
So what it shows INTERNALLY is not what it shows externally.
The box it came in and the device itself are labelled as Nanobeam AC GEN2

Weird. Look at that test date: April 25, 2017 

-Randy

￼

￼

￼

**Comment by aanon4** [comment]
The name we display is what device firmware we load onto the device, not what the device actually is. Bit confusing.

**Comment by wu2s** [comment]
Tried loading the new (NB 2475) Gen 2 build, That did not work. Loaded the NanoBeam AC Gen 1 firmware and that was successful. Able to configure and run normally. Very annoying that the labels on the device show Gen2 very clearly but this is actually a Gen 1 device.

**Comment by aanon4** [comment]
Hmm. I should still make that gen 2 build work. How did it fail?
