### ISSUE TITLE
Port forwarding - allow a range such as 6000-7999

### ISSUE THREAD

**Issue by km6lslf** [aredn/aredn#774]
Can the ability to forward ranges of ports be added? Or if it's already there, what syntax needs to be used? 

Being able to label or name port forwarding rules would be great, too

**Comment by VA2XJM** [comment]
It is already in there. Use nightly, since there was a bug few release ago when the code has been translated from perl to lua that broke the thing. The fix I pushed will come in the next release however.

You must set the external port as "6000-7999" and the internal port as "6000".
