### ISSUE TITLE
Mikrotik list of products shown in AFS omit SXT boards

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#789]
When using AFS 1.0 to locate appropriate software, the list of Mikrotik products doesn't list any SXT devices.   They're in AFS; you can find them by just typing sxt.  But they're somehow not linked to the Mikrotik brand:

![AFS_bug](https://user-images.githubusercontent.com/1124405/232590191-b8104484-7ab4-4b60-875d-e6bd2416663b.png)

**Comment by aanon4** [comment]
As the AFS will only show so many matches, it's better if you're more specific in what you type:

<img width="1101" alt="Screenshot 2023-04-17 at 1 04 48 PM" src="https://user-images.githubusercontent.com/751258/232598057-613fa8ed-61c5-4fea-99c5-ba5af950bda1.png">

**Comment by aanon4** [comment]
Visually, the ... at the end of the list it trying to indicate there's more which isn't shown.

**Comment by Orv** [comment]
Explained this to the user.  Closing ticket.
