### ISSUE TITLE
GL-AR300M seemingly dead

### ISSUE THREAD

**Issue by rustyb78** [aredn/aredn#804]
Yesterday, I logged into my nodes and updated them to the newest firmware.

I updated two AR300M devices and both are no longer able to aquire a DHCP lease from the DHCP server (which is my pfsense router).

I do have one AR300M that I did not upgrade and it works perfectly.

**Comment by rustyb78** [comment]
Update:

I am able to connect a computer to the LAN side of my AR300M and can communicate with the device. 

After trying Static and DHCP WAN settings, I've determined that, for some reason, there is no connection on the WAN side. This is preventing the AR300M from communicating with the internet which also means it will not connect to any tunnel servers that it previously could connect to.

I've changed the VLAN from 1, to anything else and then back to 1 (default). That doesn't work or clear the problem.

So far, this node is basically dead and is no longer useful if it will not connect on the WAN side.

**Comment by aanon4** [comment]
Another thing to check, as noted https://github.com/aredn/aredn/issues/802, the MAC address on the WAN port may have changed with this release. Please check your pfsense configuration in case a new mac address is problematic.

**Comment by gerner** [comment]
I'm also having trouble getting my GL-AR300M16 to connect to my home router via the WAN port. I can connect to my laptop via the LAN port, I can see it on another mesh node via RF. I've gotten it to connect to my home wifi by disabling mesh RF. But the WAN port does not seem to request an ip address via DHCP. I've also checked this by running dnsmasq on my laptop and connecting my laptop via the WAN port and observing nothing in the logs, no DHCP in a wireshark capture.

I tried adding a static ip address in the same range my router would assign, with the router as gateway, no connectivity.

I tried the latest nightly build, no difference.

I tried the suggested workaround of removing the `/etc/local/mesh-firewall/03-dhcp-wan-block` and that did not seem to make any difference. I'm happy to provide any more debug info or try any other workaround.

**Comment by gerner** [comment]
I did notice that discover messages were going out on the LAN port with all the options from udhcpc. Hope we get this in a nightly build soon :)

Thanks!

**Comment by aanon4** [comment]
It'll go in tonight.

**Comment by aanon4** [comment]
Unfortunately there was a syntax error in the build last night. We're re-fixing and testing at the moment.

**Comment by gerner** [comment]
I'm happy to test :) thanks for the response (and all the hard work to maintain AREDN!)

**Comment by aanon4** [comment]
Let's try that again:
https://github.com/aredn/aredn/pull/808

**Comment by gerner** [comment]
I just loaded the new firmware `aredn-2603-e148f10-ath79-generic-glinet_gl-ar300m16-squashfs-sysupgrade.bin` to my ar300m16 and it appears to work! I'm not connected to my local mesh (just one other node) and to my home wifi. And I'm able to connect directly to the node from my computer via the LAN port.

It's pretty amazing that my config survived all this process too. Thanks a million.

Now it's time to work on connecting to the rest of the mesh in my neighborhood!

**Comment by aanon4** [comment]
Appears to be fixed.
