### ISSUE TITLE
NB 2603 Frequency error on 5GHz nodes

### ISSUE THREAD

**Issue by k6ccc** [aredn/aredn#810]
Noticed on all my 5GHz nodes, the channel listing on the Status page is showing a 3 GHz frequency.  This screen capture is from a Mikrotik LHG 5nd, but I have observed the same issue on Rocket M5, Rocket M5-XW, and MT LHG 5HPnD-XL.

![NB-2603_Frequency-error](https://user-images.githubusercontent.com/36935831/235249684-861e71cd-43ee-4a41-9138-257feb6ff19d.png)

**Comment by k6ccc** [comment]
[supportdata-K6CCC-RB-LHG-5nD-202304281335.gz](https://github.com/aredn/aredn/files/11357173/supportdata-K6CCC-RB-LHG-5nD-202304281335.gz)

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/811

**Comment by k6ccc** [comment]
Looks like it is fixed.
Thanks
