### ISSUE TITLE
x86 Support

### ISSUE THREAD

**Issue by TagWolf** [aredn/aredn#844]
Can this be built on x86 hardware such as running on a linux or bsd distribution so we can use custom built hardware? I have some extra servers laying around and this would be a cool thing to setup provided it can interact with a particular NIC or access point.

**Comment by aanon4** [comment]
I mean .. maybe the image would run? But we dont really want to get into the business of support lots of random hardware.

**Comment by kc2cbd** [comment]
What is the x86 target used for?

**Comment by aanon4** [comment]
Virtualization hosts.
