### ISSUE TITLE
NB 20230526-158773f doesn't display properly on ac2

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#851]
![ac2](https://github.com/aredn/aredn/assets/1124405/dc69f234-533c-4ac3-9b5d-caf30aec12e2)
[supportdata-W6BI-SHACK-NODE-202305262059.gz](https://github.com/aredn/aredn/files/11579887/supportdata-W6BI-SHACK-NODE-202305262059.gz)

hAP ac2 with NB 20230526-158773f doesn't display Basic Setup page as expected.  Also gets Bad Gateway when attempting to save that page.  Note - was upgraded from 20230506 with both internal radios disabled.

Attached:  Screenshot & support data file

**Comment by aanon4** [comment]
@Orv Quick question - was the wifi disabled on this device?

**Comment by Orv** [comment]
It was.

**Comment by aanon4** [comment]
Fix is in. Give the nightly a whirl tomorrow.

**Comment by Orv** [comment]
Roger wilco.

**Comment by Orv** [comment]
Nightly Build 20230528 resolves this issue - the Setup page now displays as expected.
