### ISSUE TITLE
Dual Band Devices Don't detect 5GHz non-mesh Wi-Fi devices Wi-Fi Scan in 5GHz Mesh Mode when Connected to another 5GHz Mesh Node

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#859]
With the new 5GHz Mesh feature in the recent nightlies, Dual-Band devices with the new 5GHz Mesh feature activated do not detect non-mesh regular Wi-Fi devices, showing only 5GHz Mesh devices when connected to another 5GHz Mesh device.  thus not giving a true picture of band usage in 20MHz bandwidth mode.  Doesn't matter if both radios are active. (2.4GHz Wi-Fi AP activated.  They do seem to work fine in 2.4GHz Mesh Mode @20Mhz bandwidth.  Single-Band 5 GHz Mesh MESH (non-AC) devices do show both MESH and Wi-Fi devices using 20MHz bandwidth.  Problem verified on  both HAP AC Lite and GL-INET AR750 (Creta) devices in 5GHz Mesh Mode.  The 2.4 GHz Mesh mode does show both MESH and regular Wi-Fi devices on these models while connected to other 2.4GHz Mesh nodes.

**Comment by aanon4** [comment]
This is what I get running nightly on my HAP with the mesh radio set to 5GHZ/20MHz:

<img width="697" alt="Screenshot 2023-06-01 at 11 44 31 PM" src="https://github.com/aredn/aredn/assets/751258/8a3eb7b1-6373-49e1-9d17-b017c3b7c99c">

The only observation I can make is that I had to refresh the screen a few times to get this - it certainly didnt come up every time. But I've found that to be the case with wifi scanners in general so this isn't something new.

**Comment by k1ky** [comment]
I put it on "auto" still no joy on AR750 Creta. I have both radios enabled - 2.4GHz is operating as Wi-Fi AP and 5GHz Mesh..  Is that how you are operating?  Continuing to evaluate with Nightly 0602.

**Comment by k1ky** [comment]
I changed the MESH Channel to an unoccupied channel 36 and got a big Wi-Fi station list on auto for 1 second and then it went back to showing only the host node and no other stations. HAP AC Lite. Nightly 20230602

**Comment by aanon4** [comment]
I think we have to conclude this is a limitation of some of the hardware. If you type the scan command by hand:

```iw wlan0 scan```

Then you'll see a (usually) short list. There's nothing much I can do about this if the hardware doesnt report more.

**Comment by k1ky** [comment]
Verified that 5GHz Wi-Fi scan shows all devices when 2.4GHz radio is disabled and node is connected to a computer via Ethernet.

**Comment by k1ky** [comment]
I updated the description and text in the opening statement based on further data collected.  Seems that the 5GHz Wi-Fi scan doesn't show non-Mesh devices only when "Connected" to another 5GHz Mesh node. If there is no Mesh connection, then the 5GHz WI-Fi scan will show all devices in the band, Wi-Fi or Mesh.

**Comment by k1ky** [comment]
The Mikrotik HAP3 is able to display ALL 5GHz stations - Mesh and Non-Mesh. 
<img width="621" alt="image" src="https://github.com/aredn/aredn/assets/42675931/75e3ad5c-524e-40f7-8cb9-d9cd9bb8bc1f">
