### ISSUE TITLE
Support for Ubiquiti Edgerouters

### ISSUE THREAD

**Issue by CoolAEW** [aredn/aredn#911]
Could you add support for the Edgerouter series?
I have a ERPoe-5 I'd like to use.

**Comment by Orv** [comment]
Is it supported by OpenWrt?  If not, chances are slim that AREDN can support it.

**Comment by CoolAEW** [comment]
I'm not sure. It does not appear on the Table of Hardware, but it should be fairly similar to the Edgerouter Lite which is present on the ToH. Might not have been tested or the PoE ports is causing trouble for support.

**Comment by aanon4** [comment]
I dont think we can support routers.
