### ISSUE TITLE
Nightly Build fails Winlink Express version check

### ISSUE THREAD

**Issue by sirrated** [aredn/aredn#966]
I just upgraded my hAP from 3.23.8.0 to 20131018-d6f6c4b (nightly).  Under Telnet Post Office session in Winlink Express, when attempting to update the AREDN MESH Node List, I receive the following popup error:

Error getting master node info

Unable to get info from master node
Your computer must be connected to an AREDN MESH node
running firmware version 3.17.1.0RC1 or later.

Let me know if more info is needed!

**Comment by Orv** [comment]
That's likely a Winlink Express error; looks like it's not recognizing the nightly build format.  I'll check mine and confirm it.

**Comment by aanon4** [comment]
Could you provide some screenshots of the error, plus information about your browser and host computer?  Thanks.

**Comment by Orv** [comment]
I'm running 20231013-a8c6ac9.
Here's the response that I get and it's normal.
![image](https://github.com/aredn/aredn/assets/1124405/8a3cd8ef-5ab0-4981-8dad-670afb911936)

**Comment by sirrated** [comment]
Screenshot:
![Screenshot 2023-10-22 184129](https://github.com/aredn/aredn/assets/57431653/b8fad5ff-cc95-460b-9587-10780af33879)

Local host computer: Windows 10 Pro, Firefox 118.0.2, connected to hAP via 5 gHz wifi.

**Comment by sirrated** [comment]
I solved my issue.  My hAP had run out of DHCP addresses (5 host Direct).  Once my Windows PC had a an IP address, I did not have any issues updating the list of Telnet Post Office servers.  Thank you!
